// Gear catalog, Augmentations chunk (cyberware/bioware) - fifth in the
// Companion PACKs-aligned sequence (see gear.ts's header for the full
// rationale and chunk ordering).
//
// Transcribed from SR6_Core_RuleBook_noimg.pdf, book pp. 282-293: Headware,
// Eyeware, Earware, Bodyware, Cyberlimbs, Cyberlimb Accessories, Cyber
// Implant Weapons, Bioware, Cultured Bioware. Unlike every prior chunk, the
// README's original page estimate (282-293) held exactly - confirmed
// against the book's own table of contents, not just assumed.
//
// This is the chunk that was blocked on Essence tracking (see essenceCost on
// GearCatalogEntry and client/src/deriveEssence.ts) - every item below that
// costs Essence has it set, so buying it correctly reduces the character's
// Essence and caps their Magic/Resonance per the core rulebook formula.
//
// Stat-block numbers are transcribed as printed; flavor text is paraphrased
// in our own words, same convention as qualities.ts/gear.ts/armor.ts/
// generalGear.ts/electronics.ts.
//
// Known gaps in this pass, flagged rather than guessed at:
// - Implant Grades (book p. 282): cyberware/bioware also come in Used/
//   Alphaware/Betaware/Deltaware grades, each applying a multiplier to
//   Essence cost, nuyen cost, and Availability versus the standard-grade
//   prices below (e.g. Alphaware is x0.8 Essence/x1.2 cost/+1 Avail). Not
//   modeled - every entry below is standard grade only. A future pass could
//   add a `grades` picker analogous to `levels`, but that's new
//   infrastructure, not a data-transcription gap, so it's deferred rather
//   than attempted here.
// - Surgery/recovery (book p. 282): installing an augmentation deals
//   Physical and Stun damage equal to (Essence Cost x 3, min 1 box) to the
//   character. Not automated - the app doesn't model "installation" as a
//   distinct event from "purchase," so this would need to be applied
//   manually (e.g. via the Live Play damage tracker) if a GM wants to
//   enforce it.
// - Six items print a flat Essence cost that does NOT scale with the item's
//   own rating, while their nuyen cost does scale (Rating x N¥) - Datalock
//   (rating 1-12), Olfactory Booster / Taste Booster / Voice Modulator
//   (rating 1-3), Internal Air Tank (rating 1-4), Retinal Duplication
//   (rating 1-6), and Select Sound Filter (rating 1-6). This catalog's
//   `levels` mechanism scales `cost` AND `essenceCost` together per level
//   (same convention, see gear.ts's GearCatalogEntry), so it can't represent
//   "cost scales, Essence doesn't" as a single leveled entry without
//   mispricing Essence at higher ratings. Each is catalogued at its Rating 1
//   price only, with the per-rating cost formula noted in its summary for
//   manual pricing at higher ratings - same treatment as generalGear.ts's
//   Tranq Patch (quadratic pricing) gap.
// - Cyberjack, Cybereyes basic system, and Cyberears basic system print a
//   nuyen cost that does NOT scale linearly with rating (e.g. Cybereyes
//   Rating 1-5 costs 1,000/4,000/6,000/10,000/16,000¥, not a flat
//   per-rating multiple) - each rating is catalogued as its own flat entry
//   rather than forced into a `levels` range that would mysprice most
//   ratings.
// - Symbiotes (bioware) also require Rating x 200¥/month in upkeep food
//   cost (waived at High Lifestyle+) - not modeled as a recurring expense,
//   same precedent as generalGear.ts's DocWagon Contracts.
// - Cyber Implant Weapon "slots" (Hold-out Pistol through Grenade Launcher)
//   only buy the implanted mounting space for a firearm - the firearm
//   itself must be purchased separately from gear.ts's Weapons catalog, per
//   the book's own text. Noted in each entry's summary, not automatically
//   linked.

import type { GearCatalogEntry } from "./gear.js";
import type { StatModifier } from "./modifiers.js";

export const augmentationsGear: GearCatalogEntry[] = [
  // --- Headware (book p. 283-284) ---
  {
    id: "headware-commlink",
    name: "Headware Commlink",
    category: "augmentation",
    subcategory: "Headware",
    cost: 2000,
    availability: "2",
    essenceCost: 0.2,
    summary:
      "Implanted commlink with a built-in sim module at no extra cost. Price is for the implant slot only - add the cost of the commlink itself.",
  },
  {
    id: "control-rig",
    name: "Control Rig",
    category: "augmentation",
    subcategory: "Headware",
    cost: 30000,
    availability: "4L",
    essenceCost: 1,
    levels: { min: 1, max: 3 },
    summary:
      "Harnesses the brain's data-coordination power to directly manipulate rigged vehicles/drones. Provides its rating as a dice pool bonus (and threshold reduction) on vehicle operation tests, plus a bonus point of Edge. Includes a built-in sim module and functions as a datajack.",
  },
  {
    id: "cortex-kink-bomb",
    name: "Cortex Kink Bomb",
    category: "augmentation",
    subcategory: "Headware",
    cost: 10000,
    availability: "6I",
    summary:
      "Illegal coercion device. Damages specific headware or causes targeted brain trauma (blindness, stuttering, hearing loss) - 5P resisted with Body.",
  },
  {
    id: "cortex-microbomb",
    name: "Cortex Microbomb",
    category: "augmentation",
    subcategory: "Headware",
    cost: 25000,
    availability: "6I",
    summary: "Illegal coercion device powerful enough to kill the bearer - 18P resisted with Body.",
  },
  {
    id: "cortex-area-bomb",
    name: "Cortex Area Bomb",
    category: "augmentation",
    subcategory: "Headware",
    cost: 40000,
    availability: "6I",
    summary:
      "Illegal coercion device: kills the bearer (microbomb damage) and also affects a blast area like a fragmentation grenade, resisted separately.",
  },
  {
    id: "headware-cyberdeck",
    name: "Headware Cyberdeck",
    category: "augmentation",
    subcategory: "Headware",
    cost: 5000,
    availability: "4L",
    essenceCost: 0.4,
    summary: "Convenient for hackers on the go. Bricking causes 8P damage resisted with Body. Add the cost of the cyberdeck itself.",
  },
  {
    id: "datajack",
    name: "Datajack",
    category: "augmentation",
    subcategory: "Headware",
    cost: 1000,
    availability: "2",
    essenceCost: 0.1,
    summary:
      "Direct neural interface with a retractable micro-cable and universal access cable, plus its own storage cache. Two datajack users can string a private cable for interception-proof mental communication.",
  },
  {
    id: "datalock",
    name: "Datalock",
    category: "augmentation",
    subcategory: "Headware",
    cost: 1000,
    availability: "4",
    essenceCost: 0.1,
    summary:
      "Turns the bearer into a walking data safe with a Device Rating equal to its own rating; not wireless-enabled. Rating 1-12, cost is Rating x 1,000¥ (Essence cost stays flat at 0.1 regardless of rating) - priced here at Rating 1.",
  },
  {
    id: "cyberjack-rating-1",
    name: "Cyberjack (Rating 1)",
    category: "augmentation",
    subcategory: "Headware",
    cost: 45000,
    availability: "3L",
    essenceCost: 1,
    stats: { attributesDF: "4/3", "VR Matrix Init Dice": "+1" },
    summary: "A decker's primary anti-hacking defense, providing Data Processing and Firewall ratings and functioning as a datajack.",
  },
  {
    id: "cyberjack-rating-2",
    name: "Cyberjack (Rating 2)",
    category: "augmentation",
    subcategory: "Headware",
    cost: 65000,
    availability: "3L",
    essenceCost: 1.5,
    stats: { attributesDF: "5/4", "VR Matrix Init Dice": "+1" },
    summary: "A decker's primary anti-hacking defense, providing Data Processing and Firewall ratings and functioning as a datajack.",
  },
  {
    id: "cyberjack-rating-3",
    name: "Cyberjack (Rating 3)",
    category: "augmentation",
    subcategory: "Headware",
    cost: 80000,
    availability: "3L",
    essenceCost: 2,
    stats: { attributesDF: "6/5", "VR Matrix Init Dice": "+1" },
    summary: "A decker's primary anti-hacking defense, providing Data Processing and Firewall ratings and functioning as a datajack.",
  },
  {
    id: "cyberjack-rating-4",
    name: "Cyberjack (Rating 4)",
    category: "augmentation",
    subcategory: "Headware",
    cost: 95000,
    availability: "4L",
    essenceCost: 2.3,
    stats: { attributesDF: "7/6", "VR Matrix Init Dice": "+2" },
    summary: "A decker's primary anti-hacking defense, providing Data Processing and Firewall ratings and functioning as a datajack.",
  },
  {
    id: "cyberjack-rating-5",
    name: "Cyberjack (Rating 5)",
    category: "augmentation",
    subcategory: "Headware",
    cost: 140000,
    availability: "5L",
    essenceCost: 2.6,
    stats: { attributesDF: "8/7", "VR Matrix Init Dice": "+2" },
    summary: "A decker's primary anti-hacking defense, providing Data Processing and Firewall ratings and functioning as a datajack.",
  },
  {
    id: "cyberjack-rating-6",
    name: "Cyberjack (Rating 6)",
    category: "augmentation",
    subcategory: "Headware",
    cost: 210000,
    availability: "6L",
    essenceCost: 3,
    stats: { attributesDF: "9/8", "VR Matrix Init Dice": "+2" },
    summary: "A decker's primary anti-hacking defense, providing Data Processing and Firewall ratings and functioning as a datajack.",
  },
  {
    id: "olfactory-booster",
    name: "Olfactory Booster",
    category: "augmentation",
    subcategory: "Headware",
    cost: 4000,
    availability: "3",
    essenceCost: 0.2,
    summary:
      "Enhances, identifies, and records smells; grants a bonus Edge on scent-based Perception tests. Rating 1-3, cost is Rating x 4,000¥ (Essence stays flat at 0.2) - priced here at Rating 1.",
  },
  {
    id: "simrig-headware",
    name: "Simrig (Headware)",
    category: "augmentation",
    subcategory: "Headware",
    cost: 4000,
    availability: "4L",
    essenceCost: 0.2,
    summary: "Implanted version of the simrig; records sensory data for later replay or sale.",
  },
  {
    id: "skilljack",
    name: "Skilljack",
    category: "augmentation",
    subcategory: "Headware",
    cost: 20000,
    availability: "4",
    essenceCost: 0.1,
    levels: { min: 1, max: 6 },
    summary:
      "Interprets knowsofts/linguasofts as though they were your own skill. Can run activesofts too, but they only count as Knowledge Skills unless paired with skillwires. Total running skills capped at rating x2; single-skill cap is the skilljack's rating.",
  },
  {
    id: "taste-booster",
    name: "Taste Booster",
    category: "augmentation",
    subcategory: "Headware",
    cost: 3000,
    availability: "3",
    essenceCost: 0.2,
    summary:
      "Enhances taste buds and lets you experience AR/VR gustatory data; grants a bonus Edge on taste-based Perception tests. Rating 1-3, cost is Rating x 3,000¥ (Essence stays flat at 0.2) - priced here at Rating 1.",
  },
  {
    id: "tooth-compartment",
    name: "Tooth Compartment",
    category: "augmentation",
    subcategory: "Headware",
    cost: 800,
    availability: "4",
    summary: "Hollow tooth for smuggling tiny contraband (storage model) or triggering a linked effect on bite/wireless signal (breakable model).",
  },
  {
    id: "ultrasound-sensor-headware",
    name: "Ultrasound Sensor (Headware)",
    category: "augmentation",
    subcategory: "Headware",
    cost: 3600,
    availability: "4",
    essenceCost: 0.3,
    summary: "Replaces normal vision with ultrasound when active; switchable between active sonar, passive sonar, and off.",
  },
  {
    id: "voice-modulator",
    name: "Voice Modulator",
    category: "augmentation",
    subcategory: "Headware",
    cost: 5000,
    availability: "4L",
    essenceCost: 0.2,
    summary:
      "Perfect pitch, vocal distortion, and playback of recorded voices; grants a bonus Edge on sound-based Con tests. Rating 1-3, cost is Rating x 5,000¥ (Essence stays flat at 0.2) - priced here at Rating 1.",
  },

  // --- Eyeware (book p. 285) ---
  {
    id: "cybereyes-rating-1",
    name: "Cybereyes (Rating 1)",
    category: "augmentation",
    subcategory: "Eyeware",
    cost: 1000,
    availability: "2",
    essenceCost: 0.1,
    stats: { Capacity: "1" },
    summary: "Basic cybereyes: 20/20 vision for both eyes, image link, built-in camera, and Capacity for vision enhancements.",
  },
  {
    id: "cybereyes-rating-2",
    name: "Cybereyes (Rating 2)",
    category: "augmentation",
    subcategory: "Eyeware",
    cost: 4000,
    availability: "2",
    essenceCost: 0.2,
    stats: { Capacity: "4" },
    summary: "Basic cybereyes: 20/20 vision for both eyes, image link, built-in camera, and Capacity for vision enhancements.",
  },
  {
    id: "cybereyes-rating-3",
    name: "Cybereyes (Rating 3)",
    category: "augmentation",
    subcategory: "Eyeware",
    cost: 6000,
    availability: "3",
    essenceCost: 0.3,
    stats: { Capacity: "8" },
    summary: "Basic cybereyes: 20/20 vision for both eyes, image link, built-in camera, and Capacity for vision enhancements.",
  },
  {
    id: "cybereyes-rating-4",
    name: "Cybereyes (Rating 4)",
    category: "augmentation",
    subcategory: "Eyeware",
    cost: 10000,
    availability: "3",
    essenceCost: 0.4,
    stats: { Capacity: "12" },
    summary: "Basic cybereyes: 20/20 vision for both eyes, image link, built-in camera, and Capacity for vision enhancements.",
  },
  {
    id: "cybereyes-rating-5",
    name: "Cybereyes (Rating 5)",
    category: "augmentation",
    subcategory: "Eyeware",
    cost: 16000,
    availability: "3",
    essenceCost: 0.5,
    stats: { Capacity: "16" },
    summary: "Basic cybereyes: 20/20 vision for both eyes, image link, built-in camera, and Capacity for vision enhancements.",
  },
  {
    id: "flare-compensation-eye",
    name: "Flare Compensation (Cybereye)",
    category: "augmentation",
    subcategory: "Eyeware",
    cost: 1000,
    availability: "2",
    essenceCost: 0.1,
    summary: "Implanted version of the flare compensation vision enhancement.",
  },
  {
    id: "image-link-eye",
    name: "Image Link (Cybereye)",
    category: "augmentation",
    subcategory: "Eyeware",
    cost: 800,
    availability: "2",
    essenceCost: 0.1,
    summary: "Implanted version of the image link enhancement.",
  },
  {
    id: "low-light-vision-eye",
    name: "Low-Light Vision (Cybereye)",
    category: "augmentation",
    subcategory: "Eyeware",
    cost: 1500,
    availability: "2",
    essenceCost: 0.1,
    summary: "Implanted version of the low-light vision enhancement.",
  },
  {
    id: "ocular-drone",
    name: "Ocular Drone",
    category: "augmentation",
    subcategory: "Eyeware",
    cost: 6000,
    availability: "3",
    essenceCost: 0.3,
    summary:
      "A small drone (treat as a Horizon Flying Eye) placed in the ocular cavity, functioning as a cybereye until removed and piloted as a drone. Affects only one eye per purchase; imposes Blindness Status while operating apart from you, and is obviously fake.",
  },
  {
    id: "retinal-duplication",
    name: "Retinal Duplication",
    category: "augmentation",
    subcategory: "Eyeware",
    cost: 20000,
    availability: "5I",
    essenceCost: 0.1,
    summary:
      "Highly illegal - loads a recording of someone else's retina for an Opposed test against retinal scanners. Rating 1-6, cost is Rating x 20,000¥ (Essence stays flat at 0.1) - priced here at Rating 1. Can store a number of retinas equal to its rating.",
  },
  {
    id: "smartlink-eye",
    name: "Smartlink (Cybereye)",
    category: "augmentation",
    subcategory: "Eyeware",
    cost: 4000,
    availability: "3L",
    essenceCost: 0.2,
    summary: "Implanted version of the smartlink vision enhancement.",
  },
  {
    id: "thermographic-vision-eye",
    name: "Thermographic Vision (Cybereye)",
    category: "augmentation",
    subcategory: "Eyeware",
    cost: 2000,
    availability: "2",
    essenceCost: 0.1,
    summary: "Implanted version of the thermographic vision enhancement.",
  },
  {
    id: "vision-enhancement-eye",
    name: "Vision Enhancement (Cybereye)",
    category: "augmentation",
    subcategory: "Eyeware",
    cost: 4000,
    availability: "3",
    essenceCost: 0.1,
    summary: "Implanted version of vision enhancement.",
  },
  {
    id: "vision-magnification-eye",
    name: "Vision Magnification (Cybereye)",
    category: "augmentation",
    subcategory: "Eyeware",
    cost: 2000,
    availability: "3",
    essenceCost: 0.1,
    summary: "Implanted version of the vision magnification enhancement.",
  },

  // --- Earware (book p. 286) ---
  {
    id: "cyberears-rating-1",
    name: "Cyberears (Rating 1)",
    category: "augmentation",
    subcategory: "Earware",
    cost: 1000,
    availability: "2",
    essenceCost: 0.1,
    stats: { Capacity: "1" },
    summary:
      "Basic cyberears: omnidirectional hearing, sound link, and Capacity for modifications. Grants a bonus Edge vs. a target with interfered hearing (lost if not used immediately).",
  },
  {
    id: "cyberears-rating-2",
    name: "Cyberears (Rating 2)",
    category: "augmentation",
    subcategory: "Earware",
    cost: 3000,
    availability: "2",
    essenceCost: 0.2,
    stats: { Capacity: "4" },
    summary:
      "Basic cyberears: omnidirectional hearing, sound link, and Capacity for modifications. Grants a bonus Edge vs. a target with interfered hearing (lost if not used immediately).",
  },
  {
    id: "cyberears-rating-3",
    name: "Cyberears (Rating 3)",
    category: "augmentation",
    subcategory: "Earware",
    cost: 4500,
    availability: "3",
    essenceCost: 0.3,
    stats: { Capacity: "8" },
    summary:
      "Basic cyberears: omnidirectional hearing, sound link, and Capacity for modifications. Grants a bonus Edge vs. a target with interfered hearing (lost if not used immediately).",
  },
  {
    id: "cyberears-rating-4",
    name: "Cyberears (Rating 4)",
    category: "augmentation",
    subcategory: "Earware",
    cost: 7500,
    availability: "3",
    essenceCost: 0.4,
    stats: { Capacity: "12" },
    summary:
      "Basic cyberears: omnidirectional hearing, sound link, and Capacity for modifications. Grants a bonus Edge vs. a target with interfered hearing (lost if not used immediately).",
  },
  {
    id: "cyberears-rating-5",
    name: "Cyberears (Rating 5)",
    category: "augmentation",
    subcategory: "Earware",
    cost: 11000,
    availability: "3",
    essenceCost: 0.5,
    stats: { Capacity: "16" },
    summary:
      "Basic cyberears: omnidirectional hearing, sound link, and Capacity for modifications. Grants a bonus Edge vs. a target with interfered hearing (lost if not used immediately).",
  },
  {
    id: "audio-enhancement-ear",
    name: "Audio Enhancement (Cyberear)",
    category: "augmentation",
    subcategory: "Earware",
    cost: 4000,
    availability: "2",
    essenceCost: 0.1,
    summary: "Implanted version of audio enhancement.",
  },
  {
    id: "balance-augmenter",
    name: "Balance Augmenter",
    category: "augmentation",
    subcategory: "Earware",
    cost: 8000,
    availability: "3",
    essenceCost: 0.1,
    summary: "Enhances the inner ear's balance mechanism. One bonus die on tests involving balance (climbing, narrow platforms, landing jumps, etc.).",
  },
  {
    id: "damper",
    name: "Damper",
    category: "augmentation",
    subcategory: "Earware",
    cost: 2250,
    availability: "2",
    essenceCost: 0.1,
    summary: "Protects against sudden loud noise; diminishes the Deafened status by 1 level per instance inflicted.",
  },
  {
    id: "select-sound-filter-ear",
    name: "Select Sound Filter (Cyberear)",
    category: "augmentation",
    subcategory: "Earware",
    cost: 3500,
    availability: "4",
    essenceCost: 0.1,
    summary:
      "Implanted version of the select sound filter enhancement, capped at rating 6 (vs. rating 3 for the electronics version). Rating 1-6, cost is Rating x 3,500¥ (Essence stays flat at 0.1) - priced here at Rating 1.",
  },
  {
    id: "sound-link-ear",
    name: "Sound Link (Cyberear)",
    category: "augmentation",
    subcategory: "Earware",
    cost: 1000,
    availability: "2",
    essenceCost: 0.1,
    summary: "Audio equivalent of image link; plays audio from linked sources within your PAN directly into your cyberears.",
  },
  {
    id: "spatial-recognizer-ear",
    name: "Spatial Recognizer (Cyberear)",
    category: "augmentation",
    subcategory: "Earware",
    cost: 4000,
    availability: "3",
    essenceCost: 0.1,
    summary: "Implanted version of the spatial recognizer enhancement.",
  },

  // --- Bodyware (book p. 286-288) ---
  {
    id: "bone-lacing-plastic",
    name: "Bone Lacing (Plastic)",
    category: "augmentation",
    subcategory: "Bodyware",
    cost: 8000,
    availability: "3L",
    essenceCost: 0.5,
    stats: { "Body Bonus": "+1", "Defense Bonus": "+1", "Unarmed DV": "3P", "Unarmed AR": "+1" },
    summary:
      "Reinforcing lattice chains through your bones. Changes unarmed combat damage to Physical. Incompatible with other bone-altering augmentations (only one lacing type at a time).",
  },
  {
    id: "bone-lacing-aluminum",
    name: "Bone Lacing (Aluminum)",
    category: "augmentation",
    subcategory: "Bodyware",
    cost: 18000,
    availability: "4L",
    essenceCost: 1,
    stats: { "Body Bonus": "+2", "Defense Bonus": "+1", "Unarmed DV": "4P", "Unarmed AR": "+2" },
    modifiers: [
      { target: "body", amount: 2, stackingGroup: "bone-lacing" },
      { target: "armor", amount: 1, stackingGroup: "bone-lacing" },
    ],
    summary:
      "Reinforcing lattice chains through your bones. Changes unarmed combat damage to Physical. Incompatible with other bone-altering augmentations (only one lacing type at a time).",
  },
  {
    id: "bone-lacing-titanium",
    name: "Bone Lacing (Titanium)",
    category: "augmentation",
    subcategory: "Bodyware",
    cost: 30000,
    availability: "6L",
    essenceCost: 1.5,
    stats: { "Body Bonus": "+2", "Defense Bonus": "+2", "Unarmed DV": "4P", "Unarmed AR": "+3" },
    modifiers: [
      { target: "body", amount: 2, stackingGroup: "bone-lacing" },
      { target: "armor", amount: 2, stackingGroup: "bone-lacing" },
    ],
    summary:
      "Reinforcing lattice chains through your bones. Changes unarmed combat damage to Physical. Incompatible with other bone-altering augmentations (only one lacing type at a time).",
  },
  {
    id: "dermal-plating",
    name: "Dermal Plating",
    category: "augmentation",
    subcategory: "Bodyware",
    cost: 4000,
    availability: "4L",
    essenceCost: 0.3,
    levels: { min: 1, max: 4 },
    modifiers: [{ target: "armor", amount: "rating", stackingGroup: "skin-armor" }],
    summary:
      "Hard plastic/ceramic-fiber plates bonded to your skin, visibly and tactilely obvious. Grants a Defense Rating bonus equal to its rating. Incompatible with other skin augmentations, including orthoskin.",
  },
  {
    id: "fingertip-compartment",
    name: "Fingertip Compartment",
    category: "augmentation",
    subcategory: "Bodyware",
    cost: 3000,
    availability: "2",
    essenceCost: 0.1,
    summary:
      "Hidden compartment in a hollowed-out fingertip for micro-sized items (Concealability threshold 8). A popular trick: hold a monofilament whip's control weight here.",
  },
  {
    id: "grapple-gun-implant",
    name: "Grapple Gun (Implant)",
    category: "augmentation",
    subcategory: "Bodyware",
    cost: 5000,
    availability: "3",
    essenceCost: 0.5,
    summary: "Implanted version of the grapple gun, with internal storage holding sixty meters of microwire.",
  },
  {
    id: "internal-air-tank",
    name: "Internal Air Tank",
    category: "augmentation",
    subcategory: "Bodyware",
    cost: 4500,
    availability: "2",
    essenceCost: 0.25,
    summary:
      "Replaces part of one lung with pressurized air, letting you hold your breath for up to (rating) hours and ignore Inhalation-vector toxins while holding it. Rating 1-4, cost is Rating x 4,500¥ (Essence stays flat at 0.25) - priced here at Rating 1.",
  },
  {
    id: "muscle-replacement",
    name: "Muscle Replacement",
    category: "augmentation",
    subcategory: "Bodyware",
    cost: 30000,
    availability: "3L",
    essenceCost: 0.7,
    levels: { min: 1, max: 4 },
    modifiers: [
      { target: "strength", amount: "rating", stackingGroup: "strength-boost" },
      { target: "agility", amount: "rating", stackingGroup: "agility-boost" },
    ],
    summary:
      "Vat-grown synthetic muscle plus skeletal reinforcement. Increases Strength and Agility by its rating. Incompatible with other muscle augmentations (muscle augmentation/toner bioware).",
  },
  {
    id: "reaction-enhancers",
    name: "Reaction Enhancers",
    category: "augmentation",
    subcategory: "Bodyware",
    cost: 15000,
    availability: "4L",
    essenceCost: 0.3,
    levels: { min: 1, max: 4 },
    modifiers: [{ target: "reaction", amount: "rating", stackingGroup: "reflex-boost" }],
    summary:
      "Superconducting spinal segments quicken your reactions. Adds its rating to Reaction (adjust Initiative Score accordingly). Incompatible with all other Reaction enhancements, including wired reflexes.",
  },
  {
    id: "skillwires",
    name: "Skillwires",
    category: "augmentation",
    subcategory: "Bodyware",
    cost: 20000,
    availability: "4",
    essenceCost: 0.1,
    levels: { min: 1, max: 6 },
    summary:
      "Neuromuscular controllers overlaying your nervous system, letting you run activesofts (via a skilljack) up to your skillwire's rating.",
  },
  {
    id: "smuggling-compartment-bodyware",
    name: "Smuggling Compartment (Bodyware)",
    category: "augmentation",
    subcategory: "Bodyware",
    cost: 7500,
    availability: "3",
    essenceCost: 0.2,
    summary:
      "Hollowed-out ribs, hip bones, or shoulder blades for storing small/miniature items (nothing bigger than a light pistol). Concealability threshold 8.",
  },
  {
    id: "wired-reflexes-1",
    name: "Wired Reflexes 1",
    category: "augmentation",
    subcategory: "Bodyware",
    cost: 40000,
    availability: "3L",
    essenceCost: 1,
    stats: { Reaction: "+1", "Initiative Dice": "+1" },
    modifiers: [
      { target: "reaction", amount: 1, stackingGroup: "reflex-boost" },
      { target: "initiativeDice", amount: 1, stackingGroup: "reflex-boost" },
    ],
    summary:
      "Invasive neural boosters and adrenaline stimulators. Each rating gives +1 Reaction and +1 Initiative Die when active. Incompatible with augmentations affecting Reaction or Initiative.",
  },
  {
    id: "wired-reflexes-2",
    name: "Wired Reflexes 2",
    category: "augmentation",
    subcategory: "Bodyware",
    cost: 150000,
    availability: "3L",
    essenceCost: 2,
    stats: { Reaction: "+2", "Initiative Dice": "+2" },
    modifiers: [
      { target: "reaction", amount: 2, stackingGroup: "reflex-boost" },
      { target: "initiativeDice", amount: 2, stackingGroup: "reflex-boost" },
    ],
    summary:
      "Invasive neural boosters and adrenaline stimulators. Each rating gives +1 Reaction and +1 Initiative Die when active. Incompatible with augmentations affecting Reaction or Initiative.",
  },
  {
    id: "wired-reflexes-3",
    name: "Wired Reflexes 3",
    category: "augmentation",
    subcategory: "Bodyware",
    cost: 250000,
    availability: "4I",
    essenceCost: 3,
    stats: { Reaction: "+3", "Initiative Dice": "+3" },
    modifiers: [
      { target: "reaction", amount: 3, stackingGroup: "reflex-boost" },
      { target: "initiativeDice", amount: 3, stackingGroup: "reflex-boost" },
    ],
    summary:
      "Invasive neural boosters and adrenaline stimulators. Each rating gives +1 Reaction and +1 Initiative Die when active. Incompatible with augmentations affecting Reaction or Initiative.",
  },
  {
    id: "wired-reflexes-4",
    name: "Wired Reflexes 4",
    category: "augmentation",
    subcategory: "Bodyware",
    cost: 400000,
    availability: "6I",
    essenceCost: 4,
    stats: { Reaction: "+4", "Initiative Dice": "+4" },
    modifiers: [
      { target: "reaction", amount: 4, stackingGroup: "reflex-boost" },
      { target: "initiativeDice", amount: 4, stackingGroup: "reflex-boost" },
    ],
    summary:
      "Invasive neural boosters and adrenaline stimulators. Each rating gives +1 Reaction and +1 Initiative Die when active. Incompatible with augmentations affecting Reaction or Initiative.",
  },

  // --- Cyberlimbs (book p. 288-289) ---
  {
    id: "cyberlimb-skull-synthetic",
    name: "Cyberlimb: Skull (Synthetic)",
    category: "augmentation",
    subcategory: "Cyberlimbs",
    cost: 15000,
    availability: "5",
    essenceCost: 0.75,
    stats: { Capacity: "2" },
    summary: "Replaces the bones and muscles of the head, face, and neck; includes a cyberjaw with a powerful bite. Synthetic: passes for natural.",
  },
  {
    id: "cyberlimb-skull-obvious",
    name: "Cyberlimb: Skull (Obvious)",
    category: "augmentation",
    subcategory: "Cyberlimbs",
    cost: 10000,
    availability: "5",
    essenceCost: 0.75,
    stats: { Capacity: "4" },
    summary: "Replaces the bones and muscles of the head, face, and neck; includes a cyberjaw with a powerful bite. Obvious: cold metal, visible pistons.",
  },
  {
    id: "cyberlimb-torso-synthetic",
    name: "Cyberlimb: Torso (Synthetic)",
    category: "augmentation",
    subcategory: "Cyberlimbs",
    cost: 25000,
    availability: "4",
    essenceCost: 1.5,
    stats: { Capacity: "5" },
    summary: "Replaces the bones and muscles of the body's core. Internal organs stay, individually protected. Synthetic: passes for natural.",
  },
  {
    id: "cyberlimb-torso-obvious",
    name: "Cyberlimb: Torso (Obvious)",
    category: "augmentation",
    subcategory: "Cyberlimbs",
    cost: 20000,
    availability: "4",
    essenceCost: 1.5,
    stats: { Capacity: "10" },
    summary: "Replaces the bones and muscles of the body's core; removes genitalia/function (excretion unaffected). Obvious: cold metal, visible pistons.",
  },
  {
    id: "cyberlimb-arm-synthetic",
    name: "Cyberlimb: Arm (Synthetic)",
    category: "augmentation",
    subcategory: "Cyberlimbs",
    cost: 20000,
    availability: "4",
    essenceCost: 1,
    stats: { Capacity: "8" },
    summary: "Full arm replacement from the shoulder joint down. Synthetic: passes for natural.",
  },
  {
    id: "cyberlimb-arm-obvious",
    name: "Cyberlimb: Arm (Obvious)",
    category: "augmentation",
    subcategory: "Cyberlimbs",
    cost: 15000,
    availability: "4",
    essenceCost: 1,
    stats: { Capacity: "15" },
    summary: "Full arm replacement from the shoulder joint down. Obvious: cold metal, visible pistons.",
  },
  {
    id: "cyberlimb-forearm-synthetic",
    name: "Cyberlimb: Forearm (Synthetic)",
    category: "augmentation",
    subcategory: "Cyberlimbs",
    cost: 12000,
    availability: "3",
    essenceCost: 0.45,
    stats: { Capacity: "5" },
    summary: "Partial arm replacement below the elbow. Must match or exceed the rest of the limb's attributes. Synthetic: passes for natural.",
  },
  {
    id: "cyberlimb-forearm-obvious",
    name: "Cyberlimb: Forearm (Obvious)",
    category: "augmentation",
    subcategory: "Cyberlimbs",
    cost: 10000,
    availability: "3",
    essenceCost: 0.45,
    stats: { Capacity: "10" },
    summary: "Partial arm replacement below the elbow. Must match or exceed the rest of the limb's attributes. Obvious: cold metal, visible pistons.",
  },
  {
    id: "cyberlimb-hand-synthetic",
    name: "Cyberlimb: Hand (Synthetic)",
    category: "augmentation",
    subcategory: "Cyberlimbs",
    cost: 6000,
    availability: "3",
    essenceCost: 0.25,
    stats: { Capacity: "2" },
    summary: "Hand-only replacement. Must match or exceed the rest of the limb's attributes. Synthetic: passes for natural.",
  },
  {
    id: "cyberlimb-hand-obvious",
    name: "Cyberlimb: Hand (Obvious)",
    category: "augmentation",
    subcategory: "Cyberlimbs",
    cost: 5000,
    availability: "3",
    essenceCost: 0.25,
    stats: { Capacity: "4" },
    summary: "Hand-only replacement. Must match or exceed the rest of the limb's attributes. Obvious: cold metal, visible pistons.",
  },
  {
    id: "cyberlimb-leg-synthetic",
    name: "Cyberlimb: Leg (Synthetic)",
    category: "augmentation",
    subcategory: "Cyberlimbs",
    cost: 20000,
    availability: "4",
    essenceCost: 1,
    stats: { Capacity: "10" },
    summary: "Full leg replacement from the hip joint down. Synthetic: passes for natural.",
  },
  {
    id: "cyberlimb-leg-obvious",
    name: "Cyberlimb: Leg (Obvious)",
    category: "augmentation",
    subcategory: "Cyberlimbs",
    cost: 15000,
    availability: "4",
    essenceCost: 1,
    stats: { Capacity: "20" },
    summary: "Full leg replacement from the hip joint down. Obvious: cold metal, visible pistons.",
  },
  {
    id: "cyberlimb-lower-leg-synthetic",
    name: "Cyberlimb: Lower Leg (Synthetic)",
    category: "augmentation",
    subcategory: "Cyberlimbs",
    cost: 12000,
    availability: "4",
    essenceCost: 0.45,
    stats: { Capacity: "6" },
    summary: "Partial leg replacement below the knee. Must match or exceed the rest of the limb's attributes. Synthetic: passes for natural.",
  },
  {
    id: "cyberlimb-lower-leg-obvious",
    name: "Cyberlimb: Lower Leg (Obvious)",
    category: "augmentation",
    subcategory: "Cyberlimbs",
    cost: 10000,
    availability: "4",
    essenceCost: 0.45,
    stats: { Capacity: "12" },
    summary: "Partial leg replacement below the knee. Must match or exceed the rest of the limb's attributes. Obvious: cold metal, visible pistons.",
  },
  {
    id: "cyberlimb-foot-synthetic",
    name: "Cyberlimb: Foot (Synthetic)",
    category: "augmentation",
    subcategory: "Cyberlimbs",
    cost: 6000,
    availability: "4",
    essenceCost: 0.25,
    stats: { Capacity: "2" },
    summary: "Foot-only replacement. Must match or exceed the rest of the limb's attributes. Synthetic: passes for natural.",
  },
  {
    id: "cyberlimb-foot-obvious",
    name: "Cyberlimb: Foot (Obvious)",
    category: "augmentation",
    subcategory: "Cyberlimbs",
    cost: 5000,
    availability: "4",
    essenceCost: 0.25,
    stats: { Capacity: "4" },
    summary: "Foot-only replacement. Must match or exceed the rest of the limb's attributes. Obvious: cold metal, visible pistons.",
  },

  // --- Cyberlimb Accessories (book p. 289) - drawn from cyberlimb Capacity, no Essence cost of their own ---
  {
    id: "cyberlimb-acc-armor",
    name: "Cyberlimb Armor",
    category: "augmentation",
    subcategory: "Cyberlimb Accessories",
    cost: 5000,
    availability: "1",
    levels: { min: 1, max: 6 },
    summary:
      "Increases the limb's contribution to Defense Rating at all times. No printed maximum rating in the book - capped here at 6 as an inferred ceiling, consistent with this chapter's usual rating caps; raise manually via a custom item if your table allows higher.",
  },
  {
    id: "cyberlimb-acc-attribute-increase",
    name: "Cyberlimb Attribute Increase",
    category: "augmentation",
    subcategory: "Cyberlimb Accessories",
    cost: 5000,
    availability: "1",
    levels: { min: 1, max: 4 },
    summary:
      "Boosts the limb's Agility or Strength (or Armor, via the separate Armor accessory). Capped at 4 per the augmented-maximum rule - buying higher is a waste per the book's own text. Only applies when the limb itself is used in the action.",
  },
  {
    id: "cyberlimb-acc-gyromount",
    name: "Cyberlimb Gyromount",
    category: "augmentation",
    subcategory: "Cyberlimb Accessories",
    cost: 6000,
    availability: "5I",
    summary: "Functions the same as the gyro mount weapon accessory.",
  },
  {
    id: "cyberlimb-acc-slide",
    name: "Cyberlimb Slide",
    category: "augmentation",
    subcategory: "Cyberlimb Accessories",
    cost: 3000,
    availability: "5L",
    summary: "Functions the same as a hidden arm slide.",
  },
  {
    id: "cyberlimb-acc-holster",
    name: "Cyberlimb Holster",
    category: "augmentation",
    subcategory: "Cyberlimb Accessories",
    cost: 2000,
    availability: "4",
    summary: "Holds a weapon for convenience, not concealment.",
  },
  {
    id: "cyberlimb-acc-hydraulic-jacks",
    name: "Cyberlimb Hydraulic Jacks",
    category: "augmentation",
    subcategory: "Cyberlimb Accessories",
    cost: 2500,
    availability: "4",
    levels: { min: 1, max: 6 },
    summary:
      "Requires one in each leg with identical ratings. Subtracts its rating from the threshold of jumping tests (Athletics + Strength), minimum threshold 1. No printed maximum rating in the book - capped here at 6 as an inferred ceiling.",
  },
  {
    id: "cyberlimb-acc-smuggling-compartment",
    name: "Cyberlimb Smuggling Compartment",
    category: "augmentation",
    subcategory: "Cyberlimb Accessories",
    cost: 6000,
    availability: "2",
    summary: "Functions like the bodyware smuggling compartment.",
  },

  // --- Cyber Implant Weapons (book p. 290) ---
  {
    id: "implant-cyberjaw",
    name: "Cyberjaw (Weapon)",
    category: "augmentation",
    subcategory: "Cyber Implant Weapons",
    cost: 1500,
    availability: "2",
    essenceCost: 0.1,
    stats: { Type: "Unarmed", DV: "5P", "Attack Ratings": "2/-/-/-/-" },
    summary: "Extra biting power for close-in violence, delivered through a cyberskull.",
  },
  {
    id: "implant-hardening",
    name: "Hardening",
    category: "augmentation",
    subcategory: "Cyber Implant Weapons",
    cost: 2500,
    availability: "2",
    essenceCost: 0.1,
    stats: { Type: "Unarmed", DV: "3P (4P if Strength 7+)", "Attack Ratings": "6/-/-/-/-" },
    summary: "Hardens the skin/limb into a club-like striking surface for unarmed attacks.",
  },
  {
    id: "implant-shock-limb",
    name: "Shock Limb",
    category: "augmentation",
    subcategory: "Cyber Implant Weapons",
    cost: 5000,
    availability: "3",
    essenceCost: 0.25,
    stats: { Type: "Unarmed", DV: "4S(e)", "Attack Ratings": "5/-/-/-/-" },
    summary: "Built-in electrodes deliver a taser-like jolt, customarily via hands but sometimes via a shock kick or head butt.",
  },
  {
    id: "implant-handblade",
    name: "Handblade",
    category: "augmentation",
    subcategory: "Cyber Implant Weapons",
    cost: 2000,
    availability: "4I",
    essenceCost: 0.15,
    stats: { Type: "Blades", DV: "3P", "Attack Ratings": "6/-/-/-/-" },
    summary: "A simple blade built into the hand opposite the thumb, for a swinging cut.",
  },
  {
    id: "implant-retractable-handblade",
    name: "Retractable Handblade",
    category: "augmentation",
    subcategory: "Cyber Implant Weapons",
    cost: 2500,
    availability: "4I",
    essenceCost: 0.25,
    stats: { Type: "Blades", DV: "3P", "Attack Ratings": "6/-/-/-/-" },
    summary: "Retractable version of the handblade; Concealability threshold 8 when retracted.",
  },
  {
    id: "implant-hand-razors",
    name: "Hand Razors",
    category: "augmentation",
    subcategory: "Cyber Implant Weapons",
    cost: 1000,
    availability: "3I",
    essenceCost: 0.15,
    stats: { Type: "Blades", DV: "2P", "Attack Ratings": "6/-/-/-/-" },
    summary: "Blades under the fingernails or replacing them, for clawing.",
  },
  {
    id: "implant-retractable-hand-razors",
    name: "Retractable Hand Razors",
    category: "augmentation",
    subcategory: "Cyber Implant Weapons",
    cost: 1250,
    availability: "3I",
    essenceCost: 0.25,
    stats: { Type: "Blades", DV: "2P", "Attack Ratings": "6/-/-/-/-" },
    summary: "Retractable version of hand razors; Concealability threshold 8 when retracted.",
  },
  {
    id: "implant-spurs",
    name: "Spurs",
    category: "augmentation",
    subcategory: "Cyber Implant Weapons",
    cost: 3000,
    availability: "4I",
    essenceCost: 0.15,
    stats: { Type: "Blades", DV: "3P", "Attack Ratings": "7/-/-/-/-" },
    summary: "Spikes on the wrist or knuckles for a stabbing punch or slap.",
  },
  {
    id: "implant-retractable-spurs",
    name: "Retractable Spurs",
    category: "augmentation",
    subcategory: "Cyber Implant Weapons",
    cost: 5000,
    availability: "4I",
    essenceCost: 0.25,
    stats: { Type: "Blades", DV: "3P", "Attack Ratings": "7/-/-/-/-" },
    summary: "Retractable version of spurs; Concealability threshold 8 when retracted.",
  },
  {
    id: "implant-slot-holdout-pistol",
    name: "Cyberweapon Slot (Hold-out Pistol)",
    category: "augmentation",
    subcategory: "Cyber Implant Weapons",
    cost: 2000,
    availability: "3L",
    essenceCost: 0.1,
    summary: "Implants mounting space for a hold-out pistol (buy the firearm separately from the Weapons catalog). Implanted pistols gain +2 Concealability.",
  },
  {
    id: "implant-slot-light-pistol",
    name: "Cyberweapon Slot (Light Pistol)",
    category: "augmentation",
    subcategory: "Cyber Implant Weapons",
    cost: 3000,
    availability: "3L",
    essenceCost: 0.25,
    summary: "Implants mounting space for a light pistol (buy the firearm separately from the Weapons catalog). Implanted pistols gain +2 Concealability.",
  },
  {
    id: "implant-slot-machine-pistol",
    name: "Cyberweapon Slot (Machine Pistol)",
    category: "augmentation",
    subcategory: "Cyber Implant Weapons",
    cost: 3500,
    availability: "4L",
    essenceCost: 0.5,
    summary: "Implants mounting space for a machine pistol (buy the firearm separately from the Weapons catalog). Implanted pistols gain +2 Concealability.",
  },
  {
    id: "implant-slot-heavy-pistol",
    name: "Cyberweapon Slot (Heavy Pistol)",
    category: "augmentation",
    subcategory: "Cyber Implant Weapons",
    cost: 4300,
    availability: "4L",
    essenceCost: 0.5,
    summary: "Implants mounting space for a heavy pistol (buy the firearm separately from the Weapons catalog). Implanted pistols gain +2 Concealability.",
  },
  {
    id: "implant-slot-smg",
    name: "Cyberweapon Slot (SMG)",
    category: "augmentation",
    subcategory: "Cyber Implant Weapons",
    cost: 4800,
    availability: "5L",
    essenceCost: 1,
    summary: "Implants mounting space for a submachine gun (buy the firearm separately from the Weapons catalog).",
  },
  {
    id: "implant-slot-shotgun",
    name: "Cyberweapon Slot (Shotgun)",
    category: "augmentation",
    subcategory: "Cyber Implant Weapons",
    cost: 8500,
    availability: "5L",
    essenceCost: 1.25,
    summary: "Implants mounting space for a shotgun (buy the firearm separately from the Weapons catalog).",
  },
  {
    id: "implant-slot-grenade-launcher",
    name: "Cyberweapon Slot (Grenade Launcher)",
    category: "augmentation",
    subcategory: "Cyber Implant Weapons",
    cost: 24000,
    availability: "6I",
    essenceCost: 1.5,
    summary: "Implants mounting space for a grenade launcher (buy the firearm separately from the Weapons catalog).",
  },
  {
    id: "implant-weapon-external-clip-port",
    name: "External Clip Port",
    category: "augmentation",
    subcategory: "Cyber Implant Weapons",
    cost: 1000,
    availability: "1",
    essenceCost: 0.1,
    summary: "Accessory for an implanted firearm - one of the only modifications implanted weapons can accept.",
  },
  {
    id: "implant-weapon-laser-sight",
    name: "Laser Sight (Implant)",
    category: "augmentation",
    subcategory: "Cyber Implant Weapons",
    cost: 1000,
    availability: "1",
    essenceCost: 0.1,
    summary: "Accessory for an implanted firearm - one of the only modifications implanted weapons can accept.",
  },
  {
    id: "implant-weapon-silencer",
    name: "Silencer/Suppressor (Implant)",
    category: "augmentation",
    subcategory: "Cyber Implant Weapons",
    cost: 1000,
    availability: "4I",
    essenceCost: 0.1,
    summary: "Accessory for an implanted firearm - one of the only modifications implanted weapons can accept.",
  },

  // --- Bioware (book p. 291-293) ---
  {
    id: "adrenaline-pump",
    name: "Adrenaline Pump",
    category: "augmentation",
    subcategory: "Bioware",
    cost: 55000,
    availability: "5I",
    essenceCost: 0.75,
    levels: { min: 1, max: 3 },
    summary:
      "Implanted gland that floods the body with adrenaline when activated (or on a failed Composure test): ignore injury modifiers, can't fall unconscious from Stun, adds its rating to Strength/Agility/Reaction/Willpower for (rating x 1D6) rounds, then crashes with Stun damage. One hour to regenerate after use.",
  },
  {
    id: "bone-density-augmentation",
    name: "Bone Density Augmentation",
    category: "augmentation",
    subcategory: "Bioware",
    cost: 5000,
    availability: "4L",
    essenceCost: 0.3,
    levels: { min: 1, max: 4 },
    summary:
      "Denser, stronger bones (and 15% more body weight). Grants extra Body resisting physical damage equal to its rating; unarmed damage becomes Physical with a rating-based DV/AR bonus. Incompatible with other bone augmentations, including bone lacing.",
  },
  {
    id: "cats-eyes",
    name: "Cat's Eyes",
    category: "augmentation",
    subcategory: "Bioware",
    cost: 4000,
    availability: "3",
    essenceCost: 0.1,
    summary:
      "Transgenic vat-grown implants providing low-light vision, slit and reflective like a cat's. Not compatible with cyberware eye replacements, but individual vision enhancements can still be bought.",
  },
  {
    id: "enhanced-articulation",
    name: "Enhanced Articulation",
    category: "augmentation",
    subcategory: "Bioware",
    cost: 30000,
    availability: "4",
    essenceCost: 0.2,
    modifiers: [{ target: "agility", amount: 1, stackingGroup: "agility-boost" }],
    summary: "Joint-surface coating, re-lubrication, and tendon/ligament work for fluid movement. +1 Agility and a bonus Edge moving through cramped spaces.",
  },
  {
    id: "muscle-augmentation",
    name: "Muscle Augmentation",
    category: "augmentation",
    subcategory: "Bioware",
    cost: 31000,
    availability: "4L",
    essenceCost: 0.2,
    levels: { min: 1, max: 4 },
    modifiers: [{ target: "strength", amount: "rating", stackingGroup: "strength-boost" }],
    summary:
      "Woven muscle cables enhance mass and brute strength. Adds its rating to Strength. Incompatible with other Strength-increasing augmentations, including muscle replacement cyberware.",
  },
  {
    id: "muscle-toner",
    name: "Muscle Toner",
    category: "augmentation",
    subcategory: "Bioware",
    cost: 32000,
    availability: "4L",
    essenceCost: 0.2,
    levels: { min: 1, max: 4 },
    modifiers: [{ target: "agility", amount: "rating", stackingGroup: "agility-boost" }],
    summary:
      "Increases muscle-fiber elasticity for a smooth, ropy physique. Adds its rating to Agility. Incompatible with other Agility-increasing augmentations, including muscle replacement cyberware and enhanced articulation.",
  },
  {
    id: "orthoskin",
    name: "Orthoskin",
    category: "augmentation",
    subcategory: "Bioware",
    cost: 6000,
    availability: "4L",
    essenceCost: 0.25,
    levels: { min: 1, max: 4 },
    modifiers: [{ target: "armor", amount: "rating", stackingGroup: "skin-armor" }],
    summary:
      "A web of biofibers in the skin, virtually indistinguishable from natural skin. Grants a Defense Rating bonus equal to its rating. Incompatible with skin augmentations, including dermal plating.",
  },
  {
    id: "platelet-factories",
    name: "Platelet Factories",
    category: "augmentation",
    subcategory: "Bioware",
    cost: 17000,
    availability: "4",
    essenceCost: 0.2,
    summary: "Accelerates platelet production. Any time you'd take 2+ boxes of Physical damage, reduce it by 1 box.",
  },
  {
    id: "skin-pocket",
    name: "Skin Pocket",
    category: "augmentation",
    subcategory: "Bioware",
    cost: 12000,
    availability: "4",
    essenceCost: 0.1,
    summary: "A nerveless flap of flesh hiding a small object - a bioware smuggling compartment. Concealability threshold 10.",
  },
  {
    id: "suprathyroid-gland",
    name: "Suprathyroid Gland",
    category: "augmentation",
    subcategory: "Bioware",
    cost: 140000,
    availability: "5L",
    essenceCost: 0.7,
    modifiers: [
      { target: "agility", amount: 1 },
      { target: "body", amount: 1 },
      { target: "reaction", amount: 1 },
      { target: "strength", amount: 1 },
    ],
    summary: "Supercharges your metabolism: +1 Agility, Body, Reaction, and Strength, plus a 25% Lifestyle cost increase to fuel the extra energy needs.",
  },
  {
    id: "symbiotes",
    name: "Symbiotes",
    category: "augmentation",
    subcategory: "Bioware",
    cost: 3500,
    availability: "4",
    essenceCost: 0.2,
    levels: { min: 1, max: 4 },
    summary:
      "Tailored micro-organisms enhancing healing: add its rating as a dice pool modifier on Physical/Stun healing tests. Requires Rating x 200¥/month in special food (waived at High Lifestyle+) or they die within a month - upkeep not tracked by this app.",
  },
  {
    id: "synthacardium",
    name: "Synthacardium",
    category: "augmentation",
    subcategory: "Bioware",
    cost: 30000,
    availability: "3",
    essenceCost: 0.1,
    levels: { min: 1, max: 3 },
    summary: "Enhanced myocardium keeps blood better oxygenated. Adds its rating as a dice pool bonus to Athletics tests for running, swimming, and climbing.",
  },
  {
    id: "tailored-pheromones",
    name: "Tailored Pheromones",
    category: "augmentation",
    subcategory: "Bioware",
    cost: 31000,
    availability: "4L",
    essenceCost: 0.2,
    levels: { min: 1, max: 4 },
    summary:
      "Releasable pheromones that subtly influence others. Adds its rating to Charisma for Con/Influence tests, only within comfortable conversation range (they need to smell you). No effect on magical tests.",
  },
  {
    id: "toxin-extractor",
    name: "Toxin Extractor",
    category: "augmentation",
    subcategory: "Bioware",
    cost: 4800,
    availability: "4",
    essenceCost: 0.2,
    levels: { min: 1, max: 6 },
    summary: "Improved liver filtering. Subtracts its rating from the threshold of Toxin Resistance tests.",
  },
  {
    id: "tracheal-filter",
    name: "Tracheal Filter",
    category: "augmentation",
    subcategory: "Bioware",
    cost: 4500,
    availability: "4",
    essenceCost: 0.1,
    levels: { min: 1, max: 6 },
    summary: "Absorbs airborne impurities at the top of the trachea. Adds its rating as a dice pool bonus to Toxin Resistance tests vs. Inhalation-vector toxins.",
  },

  // --- Cultured Bioware (book p. 293-294) ---
  {
    id: "cerebral-booster",
    name: "Cerebral Booster",
    category: "augmentation",
    subcategory: "Cultured Bioware",
    cost: 31500,
    availability: "5",
    essenceCost: 0.2,
    levels: { min: 1, max: 3 },
    modifiers: [{ target: "logic", amount: "rating" }],
    summary: "Augments the cerebrum's convolutions and gyri, improving overall brain function. Increases Logic by its rating.",
  },
  {
    id: "damage-compensator",
    name: "Damage Compensator",
    category: "augmentation",
    subcategory: "Cultured Bioware",
    cost: 2000,
    availability: "5L",
    essenceCost: 0.1,
    levels: { min: 1, max: 12 },
    summary: "Nervous-pathway cutoffs blocking pain signals. Ignore a number of damage boxes (Physical, Stun, or split) equal to its rating before injury modifiers.",
  },
  {
    id: "mnemonic-enhancer",
    name: "Mnemonic Enhancer",
    category: "augmentation",
    subcategory: "Cultured Bioware",
    cost: 9000,
    availability: "5",
    essenceCost: 0.1,
    levels: { min: 1, max: 3 },
    summary: "Grey-matter growth attached to memory centers. Adds its rating as a dice pool bonus to Knowledge, Language, and memory-related tests.",
  },
  {
    id: "pain-editor",
    name: "Pain Editor",
    category: "augmentation",
    subcategory: "Cultured Bioware",
    cost: 48000,
    availability: "5I",
    essenceCost: 0.3,
    modifiers: [
      { target: "willpower", amount: 1 },
      { target: "intuition", amount: -1 },
    ],
    summary:
      "Filters sensory stimuli to ignore all injury modifiers and stay conscious with a full Stun Monitor. While active: +1 Willpower, -1 Intuition, and tactile Perception test thresholds +1.",
  },
  {
    id: "reflex-recorder",
    name: "Reflex Recorder",
    category: "augmentation",
    subcategory: "Cultured Bioware",
    cost: 14000,
    availability: "5",
    essenceCost: 0.1,
    summary:
      "Adds 1 to the rating of a skill linked to a Physical attribute (choose the skill at purchase - use the notes field). Buy multiple for multiple skills, but never two for the same skill.",
  },
  {
    id: "sleep-regulator",
    name: "Sleep Regulator",
    category: "augmentation",
    subcategory: "Cultured Bioware",
    cost: 12000,
    availability: "5",
    essenceCost: 0.1,
    summary: "Hypothalamus modification: get by on three hours of deep sleep, and stay awake twice as long before Fatigued. Healing rest hours unaffected.",
  },
  {
    id: "synaptic-booster",
    name: "Synaptic Booster",
    category: "augmentation",
    subcategory: "Cultured Bioware",
    cost: 95000,
    availability: "5L",
    essenceCost: 0.5,
    levels: { min: 1, max: 3 },
    modifiers: [
      { target: "reaction", amount: 1, stackingGroup: "reflex-boost" },
      { target: "initiativeDice", amount: 1, stackingGroup: "reflex-boost" },
    ],
    summary:
      "Broadened, replicated spinal nerve cells for faster reaction time: +1 Reaction and +1 Initiative Die, always on (can't be turned off). Cannot combine with any other Reaction/Initiative enhancement.",
  },
];
