// Body Shop chunk of the NPC template catalog - see npcTemplates.ts's header
// for the full rationale (same NpcTemplateEntry shape, split into its own
// file the same way critters.ts split off the Core Rulebook's Critters
// chapter).
//
// Transcribed from Body_Shop_compressed__noimg.pdf, "DIY Genetic
// Engineering" and "Dino-Technology" chapters, book pp. 156-165 (PDF page
// index = printed page + 1): "Baseline Mundane Critter Stat Blocks" (p.
// 156-158), "Critters for Sale" (p. 158-163, named corp-branded critters),
// and "Dino-Technology" (p. 163-165). Stat-block numbers are transcribed as
// printed - cross-checked with `pdftotext -layout -f <page> -l <page>`
// per-page extraction rather than trusted from a whole-document dump or a
// single visual read, since Body Shop's two-column layout scrambles reading
// order in both of those and produced at least one wrong digit on a first
// pass (Ares Warhound's CM misread as 10, actually 11). 31 entries total:
// 12 Baseline Mundane Critters, 13 Critters for Sale, 6 Dino-Technology.
//
// Known gaps/notes, flagged rather than guessed at:
// - Unlike some Core Rulebook critters (critters.ts), none of these print a
//   split Physical/Stun Condition Monitor - all 31 print one combined CM
//   value, same convention as Grunts (core rulebook p. 204).
// - `armor` maps to the printed "Defense Rating: N" total (not the
//   "(Armor: N)" sub-value in parentheses), matching critters.ts's existing
//   convention - the Powers "Armor N" figure is a different, lower number
//   and is kept in the `combat` text instead.
// - Evo Signal Plankton (p. 160) is described in flavor text only, no stat
//   block printed - not given an entry.
// - Wuxing Pied Piper (p. 163) prints Powers including Natural Weapon and
//   Venom but the book omits an "Attacks:" line entirely - transcribed as
//   printed (gap, not guessed at), flagged in its `notes`.
// - Ares Deinonychus's base (non-drone) stat block prints "Augmentations:
//   Text" - an obvious book typo/placeholder, not real content - omitted
//   here rather than transcribed literally.
// - Ares Triceratops Bio-Drone Prototype's flavor text calls its weapon an
//   "RPK machine gun" but its stat block prints the attack as "RPG machine
//   gun" - transcribed as printed (the stat line), discrepancy flagged in
//   `notes`.
// - Bio-drone prototypes (T-Rex/Triceratops/Deinonychus) print "Skillsofts"
//   in place of a Skills line, and their flavor text describes multi-rigger
//   turret-gunner mechanics beyond a flat Attack Rating - summarized in
//   `notes` rather than fully modeled, consistent with this roster's
//   lightweight/free-text design.
// - Dinosaurs are printed as unavailable for PC purchase and resistant to
//   taming (book p. 164) - included anyway since a GM roster has no such
//   restriction; noted for flavor only.

import type { NpcTemplateEntry } from "./npcTemplates.js";

const BODY_SHOP = "Body Shop";

/** "X/Y" printed Initiative rank/Initiative Dice -> "X + Yd6". */
function initiative(rank: number, dice: number): string {
  return `${rank} + ${dice}d6`;
}

const SHARED_CM_NOTE =
  "Condition Monitor is ONE combined Physical+Stun track, same convention as this book's Grunts (core rulebook p. 204) - treat the Physical and Stun trackers below as a single shared pool, not two separate ones.";

export const bodyShopCritterTemplates: NpcTemplateEntry[] = [
  // --- Baseline Mundane Critter Stat Blocks (book p. 156-158) ---
  {
    id: "npc-critter-bs-bear",
    name: "Bear",
    group: "Baseline Mundane Critters",
    summary: "A big, powerful omnivore - dangerous when startled or defending territory.",
    book: BODY_SHOP,
    data: {
      description: "Baseline Mundane Critter. A bear.",
      physicalMonitor: 12,
      stunMonitor: 12,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 12,
      initiative: initiative(6, 1),
      combat: [
        "B8 A3 R3 S7 W2 L1 I3 C2 ESS6",
        "AC: A1, I2",
        "Skills: Athletics 5, Close Combat 5, Influence 2 (Intimidation +2), Outdoors 4, Perception 4",
        "Powers: Armor 4, Enhanced Senses (Smell), Natural Weapon",
        "Attacks: Bite/Claws: DV 6P, Attack Ratings 12/—/—/—/—",
      ].join("\n"),
      notes: SHARED_CM_NOTE,
    },
  },
  {
    id: "npc-critter-bs-chimpanzee",
    name: "Chimpanzee",
    group: "Baseline Mundane Critters",
    summary: "A smart, agile primate - climbs well and can be trained, but bites hard when riled.",
    book: BODY_SHOP,
    data: {
      description: "Baseline Mundane Critter. A chimpanzee.",
      physicalMonitor: 10,
      stunMonitor: 10,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 6,
      initiative: initiative(7, 1),
      combat: [
        "B4 A4 R3 S5 W2 L2 I4 C3 ESS6",
        "AC: A1, I2",
        "Skills: Athletics 4 (Climbing +2), Close Combat 4, Influence 3, Outdoors 4, Perception 4",
        "Powers: Armor 2",
        "Attacks: Unarmed: DV 3S, Attack Ratings 8/—/—/—/—",
      ].join("\n"),
      notes: SHARED_CM_NOTE,
    },
  },
  {
    id: "npc-critter-bs-crocodile-gator",
    name: "Crocodile/Gator",
    group: "Baseline Mundane Critters",
    summary: "An armored ambush predator, deadly in and near water.",
    book: BODY_SHOP,
    data: {
      description: "Baseline Mundane Critter. A crocodile or alligator.",
      physicalMonitor: 12,
      stunMonitor: 12,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 13,
      initiative: initiative(6, 1),
      combat: [
        "B7 A3 R3 S7 W1 L1 I3 C1 ESS6",
        "AC: A1, I2",
        "Skills: Athletics 4 (Swimming +2), Close Combat 6 (Grappling +2), Outdoors 4, Perception 4, Stealth 4",
        "Powers: Armor 6, Enhanced Senses (Smell), Natural Weapon",
        "Attacks: Bite: DV 6P, Attack Ratings 12/—/—/—/—",
      ].join("\n"),
      notes: SHARED_CM_NOTE,
    },
  },
  {
    id: "npc-critter-bs-dog-small",
    name: "Dog, Small Breed",
    group: "Baseline Mundane Critters",
    summary: "A small dog - pet, alarm, or minor nuisance more than a real threat.",
    book: BODY_SHOP,
    data: {
      description: "Baseline Mundane Critter. A small-breed dog.",
      physicalMonitor: 9,
      stunMonitor: 9,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 2,
      initiative: initiative(6, 2),
      combat: [
        "B2 A3 R3 S1 W2 L2 I3 C3 ESS6",
        "AC: A1, I2",
        "Skills: Athletics 5, Close Combat 3, Influence 2 (Intimidation +2), Outdoors 4, Perception 5 (Smell +2)",
        "Powers: Enhanced Senses (Hearing, Smell), Natural Weapon",
        "Attack: Bite: DV 2P, Attack Ratings 4/—/—/—/—",
      ].join("\n"),
      notes: SHARED_CM_NOTE,
    },
  },
  {
    id: "npc-critter-bs-dog-large",
    name: "Dog, Large Breed",
    group: "Baseline Mundane Critters",
    summary: "A large dog - guard animal or genuine threat, good tracking nose.",
    book: BODY_SHOP,
    data: {
      description: "Baseline Mundane Critter. A large-breed dog.",
      physicalMonitor: 10,
      stunMonitor: 10,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 6,
      initiative: initiative(6, 1),
      combat: [
        "B4 A2 R3 S4 W2 L2 I3 C3 ESS6",
        "AC: A1, I2",
        "Skills: Athletics 5, Close Combat 4, Influence 2 (Intimidation +2), Outdoors 4 (Tracking +2), Perception 5 (Smell +2)",
        "Powers: Armor 2, Enhanced Senses (Hearing, Smell), Natural Weapon",
        "Attacks: Bite: DV 3P, Attack Ratings 5/—/—/—/—",
      ].join("\n"),
      notes: SHARED_CM_NOTE,
    },
  },
  {
    id: "npc-critter-bs-elephant",
    name: "Elephant",
    group: "Baseline Mundane Critters",
    summary: "Massive, thick-skinned, and dangerous if provoked - a tusk hit can flatten anyone.",
    book: BODY_SHOP,
    data: {
      description: "Baseline Mundane Critter. An elephant.",
      physicalMonitor: 14,
      stunMonitor: 14,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 20,
      initiative: initiative(7, 1),
      combat: [
        "B12 A4 R3 S18 W3 L2 I4 C3 ESS6",
        "AC: A1, I2",
        "Skills: Athletics 4, Close Combat 4, Influence 3 (Intimidation +2), Outdoors 4, Perception 5",
        "Powers: Armor 8, Enhanced Senses (Hearing), Natural Weapon",
        "Attacks: Tusks: DV 10P, Attack Ratings 21/—/—/—/—",
      ].join("\n"),
      notes: SHARED_CM_NOTE,
    },
  },
  {
    id: "npc-critter-bs-gorilla",
    name: "Gorilla",
    group: "Baseline Mundane Critters",
    summary: "A powerful great ape - climbs well, hits hard bare-handed.",
    book: BODY_SHOP,
    data: {
      description: "Baseline Mundane Critter. A gorilla.",
      physicalMonitor: 12,
      stunMonitor: 12,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 11,
      initiative: initiative(7, 1),
      combat: [
        "B7 A3 R3 S6 W2 L2 I4 C3 ESS6",
        "AC: A1, I2",
        "Skills: Athletics 4 (Climbing +2), Close Combat 6, Influence 3, Outdoors 4, Perception 4",
        "Powers: Armor 4",
        "Attacks: Unarmed: DV 4S, Attack Ratings 9/—/—/—/—",
      ].join("\n"),
      notes: SHARED_CM_NOTE,
    },
  },
  {
    id: "npc-critter-bs-house-cat",
    name: "House Cat",
    group: "Baseline Mundane Critters",
    summary: "A pet cat - fast, stealthy, and basically harmless in a fight.",
    book: BODY_SHOP,
    data: {
      description: "Baseline Mundane Critter. A house cat.",
      physicalMonitor: 9,
      stunMonitor: 9,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 2,
      initiative: initiative(8, 2),
      combat: [
        "B2 A5 R5 S1 W2 L2 I3 C4 ESS6",
        "AC: A1, I3",
        "Skills: Athletics 6 (Climbing +2), Close Combat 2, Outdoors 4, Perception 5 (Visual +2), Stealth 6",
        "Powers: Enhanced Senses (low-light vision, smell), Natural Weapon",
        "Attacks: Bite/Claws: DV 2P, Attack Ratings 6/—/—/—/—",
      ].join("\n"),
      notes: SHARED_CM_NOTE,
    },
  },
  {
    id: "npc-critter-bs-monkey",
    name: "Monkey",
    group: "Baseline Mundane Critters",
    summary: "A small, agile primate - quick and clever, but not much of a fighter.",
    book: BODY_SHOP,
    data: {
      description: "Baseline Mundane Critter. A monkey.",
      physicalMonitor: 9,
      stunMonitor: 9,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 3,
      initiative: initiative(7, 2),
      combat: [
        "B2 A4 R3 S1 W2 L2 I4 C3 ESS6",
        "AC: A1, I3",
        "Skills: Athletics 6 (Climbing +2), Close Combat 3, Influence 3, Outdoors 5, Perception 5",
        "Powers: Armor 1",
        "Attacks: Unarmed: DV 1S, Attack Ratings 4/—/—/—/—",
      ].join("\n"),
      notes: SHARED_CM_NOTE,
    },
  },
  {
    id: "npc-critter-bs-insect-spider",
    name: "Insect/Spider",
    group: "Baseline Mundane Critters",
    summary: "A bug or spider - trivially fragile, but its bite/sting can carry venom or disease.",
    book: BODY_SHOP,
    data: {
      description: "Baseline Mundane Critter. An insect or spider.",
      physicalMonitor: 1,
      stunMonitor: 1,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 0,
      initiative: initiative(7, 3),
      combat: [
        "B0 A5 R5 S0 W1 L1 I2 C1 ESS6",
        "AC: A1, I4",
        "MOVE: 5/10/+1",
        "Skills: Athletics 4, Close Combat 4, Outdoors 4, Perception 4, Stealth 4",
        "Attacks: Bite/Sting: DV 0S*, Attack Ratings 5/—/—/—/—",
        "*The DV for this attack is not increased by net hits, but one or more net hits is required to deliver a pathogen, venom, or cause an allergic reaction (when applicable).",
      ].join("\n"),
      notes: `${SHARED_CM_NOTE} Book explicitly calls out CM 1 as not a typo - any damage at all, even Stun, kills this critter.`,
    },
  },
  {
    id: "npc-critter-bs-raptor",
    name: "Raptor: Eagle, Hawk, Owl",
    group: "Baseline Mundane Critters",
    summary: "A bird of prey - excellent vision, fast flier, sharp beak and talons.",
    book: BODY_SHOP,
    data: {
      description: "Baseline Mundane Critter. A raptor (eagle, hawk, or owl).",
      physicalMonitor: 10,
      stunMonitor: 10,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 4,
      initiative: initiative(9, 3),
      combat: [
        "B3 A5 R5 S3 W2 L1 I4 C2 ESS6",
        "AC: A1, I4",
        "MOVE: 15/30/+3",
        "Skills: Athletics 6 (Flying +2), Close Combat 4 (Grappling +2), Outdoors 4, Perception 5 (Vision +2)",
        "Powers: Armor 1, Enhanced Senses (Vision enhancement, vision magnification), Natural Weapon",
        "Attacks: Beak/Talons: DV 4P, Attack Ratings 5/—/—/—/—",
      ].join("\n"),
      notes: SHARED_CM_NOTE,
    },
  },
  {
    id: "npc-critter-bs-tiny-animal",
    name: "Tiny Animal: Bird, Fish, Rodent, Lizard, Snake, etc.",
    group: "Baseline Mundane Critters",
    summary: "A small animal - generic stat block for birds, fish, rodents, lizards, snakes, and the like.",
    book: BODY_SHOP,
    data: {
      description: "Baseline Mundane Critter. Generic small animal (bird, fish, rodent, lizard, snake, etc.).",
      physicalMonitor: 9,
      stunMonitor: 9,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 1,
      initiative: initiative(6, 2),
      combat: [
        "B1 A3 R3 S1 W1 L1 I3 C2 ESS6",
        "AC: A1, I3",
        "Skills: Athletics 6, Close Combat 2, Outdoors 4, Perception 4, Stealth 6",
        "Powers: Enhanced Senses (Hearing, Smell), Natural Weapon",
        "Attacks: Bite/Claws: DV 1P, Attack Ratings 4/—/—/—/—",
      ].join("\n"),
      notes: `${SHARED_CM_NOTE} Book's own suggestion: for anything not covered by a printed stat block, reuse/modify the closest match - e.g. a raccoon can just use the Dog stat block, or a grizzly bear can use Bear with +2 Body/Strength (+1 DV to its natural weapon).`,
    },
  },

  // --- Critters for Sale (book p. 158-163, named corp-branded critters) ---
  {
    id: "npc-critter-bs-ares-warhound",
    name: "Ares Warhound",
    group: "Critters for Sale",
    summary: "Ares Macrotechnology's genetically enhanced hellhound - breathes fire, eager to obey.",
    book: BODY_SHOP,
    data: {
      description: "Critters for Sale (Ares Macrotechnology). Genetically enhanced Awakened hellhound with a flaming breath attack.",
      physicalMonitor: 11,
      stunMonitor: 11,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 10,
      initiative: initiative(9, 2),
      combat: [
        "B6 A4 R5 S4 W3 L2 I4 C3 M6 ESS6",
        "AC: A1, I3",
        "Skills: Athletics 7, Close Combat 4, Influence 4 (Intimidation +2), Outdoors 5, Perception 3, Stealth 5",
        "Powers: Armor 4, Elemental Attack (Fire), Enhanced Senses (Hearing, Low-Light Vision, Smell), Fear, Immunity to Fire, Natural Weapon",
        "Augmentations: Awakened critter power enhancement 6 (elemental attack), critter awakening 1, severing (dual natured), natural bioware (mnemonic enhancer 3), unnatural instinct (elemental attack, trigger: point at target and shout \"Ares!\")",
        "Attacks: Bite: DV 3P, Attack Ratings 9/—/—/—/—; Elemental attack (fire): DV 12P, Augmented dice pool 16, Attack Ratings 12/10/4/2/—",
        "Genetic Mishaps Roll: 2D6+8 (2 weaknesses)",
        "Common Weaknesses: Dietary requirement (hellhound meat), Vulnerability (toxins)",
        "Availability: 7(L)",
        "Cost: 117,500¥ (-10% for each weakness)",
      ].join("\n"),
      notes: SHARED_CM_NOTE,
    },
  },
  {
    id: "npc-critter-bs-hard-corps-cyber-mammoth",
    name: "Hard Corps Cyber-Mammoth",
    group: "Critters for Sale",
    summary: "Ares's cybernetic bio-drone elephant - heavily armored, built to soak fire and keep going.",
    book: BODY_SHOP,
    data: {
      description: "Critters for Sale (Ares Macrotechnology). Cybernetic bio-drone elephant, heavy close-combat tank.",
      physicalMonitor: 14,
      stunMonitor: 14,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 28,
      initiative: initiative(7, 4),
      combat: [
        "B12(+2) A4(8) R3 S18 W3 L2 I4 C3 ESS0.9",
        "AC: A1, I5",
        "Skills: Athletics 4, Close Combat 4, Influence 3 (Intimidation +2), Outdoors 4, Perception 5",
        "Autosofts: Activesoft: Athletics (rating 6), Activesoft: Close Combat (rating 6), Clearsight (rating 6)",
        "Powers: Armor 8, Enhanced Senses (Hearing), Natural Weapon",
        "Augmentations: Bio-drone harness (rating 6), kill switch (catastrophic bio-drone harness failure), natural bioware (muscle toner 4), natural weapon sheathing (rating 6), titanium exoframe (w/ hardened armor module rating 6), unnatural instinct (hardened armor exoframe module)",
        "Attacks: Tusks: DV 13P, Attack Ratings 27/—/—/—/—",
        "Genetic Mishaps Roll: 1D6+2 (0 weaknesses)",
        "Availability: 7(L)",
        "Cost: 239,500¥",
      ].join("\n"),
      notes: `${SHARED_CM_NOTE} Defense Rating 28 = Armor 14, 6 of which is Hardened.`,
    },
  },
  {
    id: "npc-critter-bs-stuffer-shack-super-steer",
    name: "Stuffer Shack Super Steer",
    group: "Critters for Sale",
    summary: "Aztechnology's genetically bulked-up cattle - enhanced livestock, not built for a fight.",
    book: BODY_SHOP,
    data: {
      description: "Critters for Sale (Aztechnology). Genetically enhanced livestock, oversized cattle.",
      physicalMonitor: 16,
      stunMonitor: 16,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 17,
      initiative: initiative(5, 1),
      combat: [
        "B16 A2 R3 S14 W2 L2 I2 C2 ESS4.8",
        "AC: A1, I2",
        "Skills: Athletics 7, Close Combat 1, Perception 3",
        "Powers: Armor 1, Enhanced Senses (Hearing), Natural Weapon",
        "Genetic Augmentations: Physical attribute enhancement (Body 6, Strength 6)",
        "Attacks: Horns: DV 9P, Attack Ratings 17/—/—/—/—",
        "Genetic Mishaps Roll: 1D6+2 (0 weaknesses)",
        "Availability: 6(L)",
        "Cost: 34,000¥",
      ].join("\n"),
      notes: SHARED_CM_NOTE,
    },
  },
  {
    id: "npc-critter-bs-stuffer-shack-chicken-taco",
    name: "Stuffer Shack Chicken Taco",
    group: "Critters for Sale",
    summary: "Aztechnology's genetically enhanced poultry - fast-growing enhanced livestock.",
    book: BODY_SHOP,
    data: {
      description: "Critters for Sale (Aztechnology). Genetically enhanced livestock, oversized chicken.",
      physicalMonitor: 10,
      stunMonitor: 10,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 4,
      initiative: initiative(9, 3),
      combat: [
        "B4 A5 R5 S4 W2 L1 I4 C2 ESS5.6",
        "AC: A1, I4",
        "MOVE: 15/30/+3",
        "Skills: Athletics 4, Close Combat 2, Perception 2",
        "Powers: Natural Weapon",
        "Genetic Augmentations: Physical attribute enhancement (Body 2, Strength 2)",
        "Attacks: Beak: DV 3P, Attack Ratings 9/—/—/—/—",
        "Genetic Mishaps Roll: 1D6+2 (0 weaknesses)",
        "Availability: 2(L)",
        "Cost: 11,000¥",
      ].join("\n"),
      notes: SHARED_CM_NOTE,
    },
  },
  {
    id: "npc-critter-bs-evo-pet-pal-puppy",
    name: "Evo Pet Pal Puppy",
    group: "Critters for Sale",
    summary: "Evo's talking pet dog - critterjack and critter comm implants let it hold a conversation.",
    book: BODY_SHOP,
    data: {
      description: "Critters for Sale (Evo). Small dog with critterjack/critter comm augmentations - can converse with its owner.",
      physicalMonitor: 9,
      stunMonitor: 9,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 2,
      initiative: initiative(6, 1),
      combat: [
        "B2 A3 R3 S1 W2 L2 I3 C5(+1) ESS4.8",
        "AC: A1, I2",
        "Skills: Athletics 5, Close Combat 2, Influence 2 (Intimidation +2), Outdoors 4, Perception 5 (Smell +2)",
        "Powers: Enhanced Senses (Hearing, Smell), Natural Weapon",
        "Augmentations: Critterjack (rating 5), critter comm (rating 5), mental attribute enhancement (Charisma 2), natural bioware (mnemonic enhancer 3, tailored pheromones 1)",
        "Attack: Bite: DV 2P, Attack Ratings 4/—/—/—/—",
        "Genetic Mishaps Roll: 1D6+3 (1 weakness if the 1D6 rolls a 6)",
        "Availability: 6(L)",
        "Cost: 35,000¥ (-10% for 1 weakness)",
      ].join("\n"),
      notes: SHARED_CM_NOTE,
    },
  },
  {
    id: "npc-critter-bs-evo-pet-pal-kitty",
    name: "Evo Pet Pal Kitty",
    group: "Critters for Sale",
    summary: "Evo's talking pet cat - critterjack and critter comm implants let it hold a conversation.",
    book: BODY_SHOP,
    data: {
      description: "Critters for Sale (Evo). House cat with critterjack/critter comm augmentations - can converse with its owner.",
      physicalMonitor: 9,
      stunMonitor: 9,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 2,
      initiative: initiative(8, 2),
      combat: [
        "B2 A5 R5 S1 W2 L2 I3 C6(+1) ESS4.8",
        "AC: A1, I3",
        "Skills: Athletics 6 (Climbing +2), Close Combat 3, Outdoors 4, Perception 5 (Visual +2), Stealth 6",
        "Powers: Enhanced Senses (Low-Light Vision, Smell), Natural Weapon",
        "Augmentations: Critterjack (rating 5), critter comm (rating 5), mental attribute enhancement (Charisma 2), natural bioware (mnemonic enhancer 3, tailored pheromones 1)",
        "Attacks: Bite/Claws: DV 2P, Attack Ratings 6/—/—/—/—",
        "Genetic Mishaps Roll: 1D6+3 (1 weakness if the 1D6 rolls a 6)",
        "Availability: 6(L)",
        "Cost: 35,000¥ (-10% for 1 weakness)",
      ].join("\n"),
      notes: SHARED_CM_NOTE,
    },
  },
  {
    id: "npc-critter-bs-renraku-best-boy",
    name: "Renraku Best Boy",
    group: "Critters for Sale",
    summary: "Renraku's augmented police dog - cover module and a remote-fired shotgun turret.",
    book: BODY_SHOP,
    data: {
      description: "Critters for Sale (Renraku). Police dog with a cover module and an attached, remotely-fired turret mount.",
      physicalMonitor: 11,
      stunMonitor: 11,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 8,
      initiative: initiative(7, 2),
      combat: [
        "B4(+2) A2 R3(4) S4 W2 L2 I3 C3 ESS3",
        "AC: A1, I3",
        "Skills: Athletics 5, Close Combat 4, Influence 2 (Intimidation +2), Outdoors 4 (Tracking +2), Perception 5 (Smell +2)",
        "Powers: Armor 2, Enhanced Senses (Hearing, Smell), Natural Weapon",
        "Augmentations: Critterjack (rating 6), critter comm (rating 6), natural bioware (mnemonic enhancer 3, synaptic accelerator 1), titanium exoframe (deployable cover module rating 4, flash module, large turret mount rating 6: Defiance T-250 shotgun, turret ammunition storage module), unnatural instinct (deployable cover module special training)",
        "Attacks: Bite: DV 3P, Attack Ratings 5/—/—/—/—; Defiance T-250 (turret): DV 4P, Attack Ratings 7/10/6/—/—*",
        "Genetic Mishaps Roll: 1D6+3 (0-1 weakness)",
        "Common Weaknesses: Allergy (Soy, Mild), Vulnerability (Lead)",
        "Availability: 6(L)",
        "Cost: 102,830¥ (-10% for 1 weakness)",
        "*Turret fires twice per combat round on its own actions with a dice pool of 12, commanded remotely via the Control Device Matrix Action - the dog itself has no control over it.",
      ].join("\n"),
      notes: SHARED_CM_NOTE,
    },
  },
  {
    id: "npc-critter-bs-mct-hk-jaws",
    name: "MCT HK-Jaws",
    group: "Critters for Sale",
    summary: "MCT's cybered-up shark - underwater security, hunts down and attacks intruders.",
    book: BODY_SHOP,
    data: {
      description: "Critters for Sale (MCT). Cybered shark bred for underwater security work.",
      physicalMonitor: 11,
      stunMonitor: 11,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 11,
      initiative: initiative(9, 1),
      combat: [
        "B5 A3(7) R5 S10 W2 L1 I4 C1 ESS3.5",
        "AC: A1, I2",
        "MOVE: 11/36/+3 (swimming)",
        "Skills: Athletics 6 (Swimming +2), Close Combat 8, Influence 5 (Intimidation +2), Perception 6 (Smell +2)",
        "Powers: Enhanced Senses (Smell), Hardened Armor 6, Natural Weapon",
        "Augmentations: Aquatic cybertail (alpha, obvious, agility enhancement 4, enhanced movement 6), critterjack (alpha, rating 5), lockjaw (alpha), natural bioware (mnemonic enhancer 3), natural weapon sheathing (alpha, rating 6), physical attribute enhancement (Strength 5), unnatural instinct (remain within 10km of its base of operations)",
        "Attacks: Bite: DV 9P, Attack Ratings 15/—/—/—/—",
        "Genetic Mishaps Roll: 1D6+3 (1 weakness if the 1D6 rolls a 6)",
        "Availability: 6(L)",
        "Cost: 136,300¥ (-10% for 1 weakness)",
      ].join("\n"),
      notes: `${SHARED_CM_NOTE} Armor is 6H (Hardened), not soft armor.`,
    },
  },
  {
    id: "npc-critter-bs-sk-astral-guardian-barghest",
    name: "S-K Astral Guardian Barghest",
    group: "Critters for Sale",
    summary: "Saeder-Krupp's Awakened security barghest, tuned to spot and respond to astral intruders.",
    book: BODY_SHOP,
    data: {
      description: "Critters for Sale (Saeder-Krupp). Awakened barghest specialized for astral security.",
      physicalMonitor: 12,
      stunMonitor: 12,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 11,
      initiative: initiative(10, 2),
      combat: [
        "B7 A4 R5 S5 W3 L2 I5 C5 M5 ESS6",
        "AC: A1, I3",
        "Skills: Astral 4, Athletics 5, Close Combat 8, Influence 5 (Intimidation +2), Outdoors 6, Perception 6",
        "Powers: Armor 4, Dual Natured, Enhanced Senses (Hearing, Smell, Sonar), Fear, Immunity (Barghest Howls), Natural Weapon, Paralyzing Howl",
        "Augmentations: Awakened critter power enhancement (paralyzing howl, rating 3), natural bioware (mnemonic enhancer 3), selective dampening (paralyzing howl, rating 6), unnatural instinct (deactivate selective dampening, trigger: special verbal command)",
        "Attacks: Claws/Bite*: DV 3P, Attack Ratings 10/—/—/—/—",
        "Genetic Mishaps Roll: 2D6+5 (1-2 weaknesses)",
        "Common Weaknesses: Vulnerability (Iron, Silver)",
        "Availability: 6(L)",
        "Cost: 112,500¥ (-10% per weakness)",
        "*Because barghests are dual natured, this attack can be used against purely astral targets as well.",
      ].join("\n"),
      notes: SHARED_CM_NOTE,
    },
  },
  {
    id: "npc-critter-bs-shiawase-warfare-gorilla",
    name: "Shiawase Warfare Gorilla",
    group: "Critters for Sale",
    summary: "Shiawase's heavily cybered gorilla - built for mobility and targeted violence.",
    book: BODY_SHOP,
    data: {
      description: "Critters for Sale (Shiawase). Heavily cybered combat gorilla.",
      physicalMonitor: 16,
      stunMonitor: 16,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 19,
      initiative: initiative(11, 3),
      combat: [
        "B7 A3(7) R3(7) S6 W2 L2(4) I4 C3 EDG4 ESS0.05",
        "AC: A1, I4",
        "Skills: Athletics 4 (Climbing +2), Close Combat 6(7), Influence 3, Outdoors 4, Perception 4",
        "Powers: Armor 4",
        "Augmentations: Augmented cyberarms (beta, obvious, agility enhancement 4, armor enhancement 4, gecko pads, retractable spurs), augmented cyberlegs (beta, obvious, agility enhancement 4, enhanced movement 5, gecko pads, hydraulic jacks 5), critterjack (beta, rating 5), critter comm (beta, rating 4), cybereyes (beta, rating 3, flare compensation, low-light vision, vision enhancement), cyberears (beta, rating 3, audio enhancement, balance augmenter, spatial recognizer), heuristic processor (beta, rating 4), natural bioware (cerebral booster 2, mnemonic enhancer 3, reflex recorder: close combat), reaction enhancers (beta, rating 2), wired reflexes (beta, rating 2)",
        "Attacks: Spurs: DV 3P, Attack Ratings 7/—/—/—/—",
        "Genetic Mishaps Roll: 1D6+3 (0 weaknesses)",
        "Common Weaknesses: None are permitted to survive",
        "Availability: 8(L)",
        "Cost: 632,000¥",
      ].join("\n"),
      notes: SHARED_CM_NOTE,
    },
  },
  {
    id: "npc-critter-bs-lusitano-melhor-horse",
    name: "Lusitano Melhor Horse",
    group: "Critters for Sale",
    summary: "Spinrad Global's genetically upgraded Lusitano horse - a rare, extravagant status mount.",
    book: BODY_SHOP,
    data: {
      description: "Critters for Sale (Spinrad Global). Genetically upgraded Lusitano horse breed.",
      physicalMonitor: 12,
      stunMonitor: 12,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 9,
      initiative: initiative(9, 1),
      combat: [
        "B8 A6(8) R4 S7 W3 L2 I5 C5 ESS5.5",
        "AC: A1, I2",
        "Skills: Athletics 7(10), Close Combat 1, Perception 3",
        "Powers: Armor 1, Enhanced Senses (Hearing), Natural Weapon",
        "Augmentations: Mental attribute enhancement (Charisma 2), natural bioware (mnemonic enhancer 3, muscle toner 2, synthacardium 3), physical attribute enhancement (Agility 3)",
        "Attacks: Hoof: DV 3S, Attack Ratings 11/—/—/—/—",
        "Genetic Mishaps Roll: 1D6+5 (0-2 weaknesses)",
        "Common Weaknesses: None with any weaknesses are permitted to survive",
        "Availability: 6(L)",
        "Cost: 150,000¥",
      ].join("\n"),
      notes: SHARED_CM_NOTE,
    },
  },
  {
    id: "npc-critter-bs-lusitano-pegasus",
    name: "Lusitano Pegasus",
    group: "Critters for Sale",
    summary: "A cybernetic, winged version of the Lusitano Melhor - can carry a rider into the sky.",
    book: BODY_SHOP,
    data: {
      description: "Critters for Sale (Spinrad Global). Cybernetic flying variant of the Lusitano Melhor Horse, with an exoframe and glider wings.",
      physicalMonitor: 12,
      stunMonitor: 12,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 10,
      initiative: initiative(9, 1),
      combat: [
        "B8(+2) A6(8) R4 S7 W3 L2 I5 C5 ESS3.22",
        "AC: A1, I2",
        "CM: 12 (13 while carrying the exoframe's flight load)",
        "Skills: Athletics 7(10), Close Combat 1, Perception 3",
        "Powers: Armor 1, Enhanced Senses (Hearing), Natural Weapon",
        "Augmentations: Aluminum exoframe (alpha, vector thrust wings rating 6), critterjack (alpha, rating 6), critter comm (rating 6), mental attribute enhancement (Charisma 2), natural bioware (mnemonic enhancer 3, muscle toner 2, synthacardium 3), physical attribute enhancement (Agility 3), unnatural instinct (vector thrust wings special training)",
        "Attacks: Hoof: DV 3S, Attack Ratings 11/—/—/—/—",
        "Genetic Mishaps Roll: 1D6+6 (0-2 weaknesses)",
        "Common Weaknesses: None with any weaknesses are permitted to survive",
        "Availability: 6(L)",
        "Cost: 250,000¥",
      ].join("\n"),
      notes: `${SHARED_CM_NOTE} Book prints CM as "12(13)" - the parenthetical (exoframe-boosted) figure isn't used here since physicalMonitor/stunMonitor take one flat number; see the combat text for both.`,
    },
  },
  {
    id: "npc-critter-bs-wuxing-pied-piper",
    name: "Wuxing Pied Piper",
    group: "Critters for Sale",
    summary: "Wuxing's genetically modified demon rat - rounds up rat infestations and herds them into containers.",
    book: BODY_SHOP,
    data: {
      description: "Critters for Sale (Wuxing). Modified demon rat bred for pest control, herds rats into containers.",
      physicalMonitor: 10,
      stunMonitor: 10,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 5,
      initiative: initiative(10, 2),
      combat: [
        "B3 A4 R5 S3 W3 L2 I5 C5 M4 ESS5.02",
        "AC: A1, I3",
        "MOVE: 5/10/+1",
        "Skills: Athletics 3 (Climbing +2), Close Combat 6, Perception 5, Stealth 7",
        "Powers: Armor 2, Animal Control (ordinary rats, devil rats, glitch rats), Concealment (self only), Immunity (toxins), Natural Weapon, Venom",
        "Augmentations: Critterjack (alpha, rating 6), critter comm (alpha, rating 5), image link, natural bioware (mnemonic enhancer rating 3)",
        "Genetic Mishaps Roll: 2D6+1 (1 weakness)",
        "Common Weakness: Dietary requirement (rats of any type, including devil rats, demon rats, and glitch rats)",
        "Availability: 6(L)",
        "Cost: 32,860¥",
      ].join("\n"),
      notes: `${SHARED_CM_NOTE} Book gap: prints Natural Weapon and Venom under Powers but omits an Attacks line entirely - not guessed at here; use judgment (a bite carrying its Venom power is the obvious read) if this comes up at the table.`,
    },
  },

  // --- Dino-Technology (book p. 163-165) ---
  {
    id: "npc-critter-bs-ares-t-rex",
    name: "Ares T-Rex",
    group: "Dino-Technology",
    summary: "A resurrected Tyrannosaurus rex - Ares's top priority dinosaur, huge and nearly untrainable.",
    book: BODY_SHOP,
    data: {
      description: "Dino-Technology (Ares Macrotechnology). Genetically resurrected Tyrannosaurus rex.",
      physicalMonitor: 17,
      stunMonitor: 17,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 24,
      initiative: initiative(6, 2),
      combat: [
        "B18 A4 R4 S28 W2 L1 I2 C2 ESS6",
        "AC: A1, I3",
        "Skills: Athletics 6, Close Combat 8, Influence 2 (Intimidation +2), Outdoors 4, Perception 4",
        "Powers: Hardened Armor 6, Enhanced Senses (Smell), Natural Weapon",
        "Attacks: Bite: DV 16P, Attack Ratings 32/—/—/—/—",
      ].join("\n"),
      notes:
        `${SHARED_CM_NOTE} Dinosaurs are unavailable for PC purchase and resist taming/training (roll Willpower+Intuition x2 to resist), per book flavor text - included in this GM roster regardless since it has no such restriction.`,
    },
  },
  {
    id: "npc-critter-bs-ares-t-rex-bio-drone",
    name: "Ares T-Rex Bio-Drone Prototype",
    group: "Dino-Technology",
    summary: "A T-Rex fitted with a bio-drone harness and dual heavy turrets - riggers jump in to pilot and gun it.",
    book: BODY_SHOP,
    data: {
      description: "Dino-Technology (Ares Macrotechnology). Bio-drone T-Rex with a titanium exoframe and twin heavy weapon turrets.",
      physicalMonitor: 17,
      stunMonitor: 17,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 26,
      initiative: initiative(6, 4),
      combat: [
        "B18(+2) A4 R4 S28 W2 L1 I2 C2 ESS0.1",
        "AC: A1, I5",
        "Skillsofts: Athletics 6, Clearsight, Close Combat 6",
        "Powers: Hardened Armor 6, Enhanced Senses (Smell), Natural Weapon",
        "Augmentations: Bio-drone harness (rating 6), cybereyes (rating 4, flare compensation, low-light vision, thermographic vision, vision enhancement, vision magnification), cyberears (rating 4, audio enhancement, balance augmenter, damper, select sound filter 4, spatial recognizer), kill switch (two explosives, one for the brain and one for the heart, detonates if the bio-drone harness catastrophically fails), natural weapon sheathing (rating 6), titanium exoframe (rating 6, double capacity, two heavy turret mounts: panther assault cannons, 8 ammunition storage modules)",
        "Attacks: Bite: DV 19P, Attack Ratings 38/—/—/—/—; Panther XXL (turret): DV 7P, Attack Ratings 1/9/12/8/6; Missile Launcher w/ Fragmentation Missiles (turret): 16P Ground Zero/12P Close/8P Near (30m blast), Attack Ratings —/4/10/9/6",
      ].join("\n"),
      notes:
        `${SHARED_CM_NOTE} CM prints as "17(18)" - the (18) is the bio-drone-harnessed figure; physicalMonitor/stunMonitor use the base 17. Operating independently, each turret mount fires twice per combat round with a dice pool of 12; with riggers jumped in, one pilots the T-Rex and one gunner per turret mount - not separately modeled here, summarized for GM reference.`,
    },
  },
  {
    id: "npc-critter-bs-ares-triceratops",
    name: "Ares Triceratops",
    group: "Dino-Technology",
    summary: "A resurrected Triceratops - armored hide, armored crest, and horns that can gore a vehicle.",
    book: BODY_SHOP,
    data: {
      description: "Dino-Technology (Ares Macrotechnology). Genetically resurrected Triceratops.",
      physicalMonitor: 16,
      stunMonitor: 16,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 24,
      initiative: initiative(6, 1),
      combat: [
        "B16 A4 R4 S24 W2 L1 I2 C2 ESS6",
        "AC: A1, I2",
        "Skills: Athletics 6, Close Combat 6, Influence 2 (Intimidation +2), Outdoors 4, Perception 2",
        "Powers: Hardened Armor 8, Natural Weapon",
        "Attacks: Horns: DV 14P, Attack Ratings 28/—/—/—/—",
      ].join("\n"),
      notes:
        `${SHARED_CM_NOTE} Dinosaurs are unavailable for PC purchase and resist taming/training, per book flavor text - included in this GM roster regardless since it has no such restriction.`,
    },
  },
  {
    id: "npc-critter-bs-ares-triceratops-bio-drone",
    name: "Ares Triceratops Bio-Drone Prototype",
    group: "Dino-Technology",
    summary: "A Triceratops fitted with a bio-drone harness, hardened plating, and a heavy machine gun turret.",
    book: BODY_SHOP,
    data: {
      description: "Dino-Technology (Ares Macrotechnology). Bio-drone Triceratops with a titanium exoframe and heavy machine gun turret.",
      physicalMonitor: 18,
      stunMonitor: 18,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 26,
      initiative: initiative(6, 1),
      combat: [
        "B16(+2) A4 R4 S24 W2 L1 I2 C2 ESS0.3",
        "AC: A1, I2",
        "Skillsofts: Athletics 6, Clearsight 6, Close Combat 6",
        "Powers: Hardened Armor 8, Natural Weapon",
        "Augmentations: Bio-drone harness (rating 6), cybereyes (rating 4, flare compensation, low-light vision, thermographic vision, vision enhancement, vision magnification), cyberears (rating 4, audio enhancement, balance augmenter, damper, select sound filter 4, spatial recognizer), kill switch (two explosives, detonates if the bio-drone harness catastrophically fails), titanium exoframe (rating 6, double capacity, hardened armor module rating 6, heavy turret mount with machine gun, 4 ammunition storage modules)",
        "Attacks: Horns: DV 17P, Attack Ratings 34/—/—/—/—; Turret machine gun: DV 6P, Attack Ratings 1/10/12/8/7",
      ].join("\n"),
      notes:
        `${SHARED_CM_NOTE} Book inconsistency: flavor text calls the turret weapon an "RPK machine gun" but the stat block's attack line prints "RPG machine gun" - transcribed as printed. Operating independently, the turret fires as its own separate drone with two attacks per combat round; with riggers jumped in, one pilots the Triceratops and one gunner for the turret - not separately modeled here.`,
    },
  },
  {
    id: "npc-critter-bs-ares-deinonychus",
    name: "Ares Deinonychus",
    group: "Dino-Technology",
    summary: "A smaller, bipedal dinosaur bred for urban hunting - agile enough to fit through metahuman-sized doorways.",
    book: BODY_SHOP,
    data: {
      description: "Dino-Technology (Ares Macrotechnology). Genetically resurrected Deinonychus, bred for urban reconnaissance and hunting.",
      physicalMonitor: 12,
      stunMonitor: 12,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 12,
      initiative: initiative(8, 3),
      combat: [
        "B8 A5 R5 S8 W2 L1 I3 C2 ESS6",
        "AC: A1, I4",
        "Skills: Athletics 7, Close Combat 7, Influence 2 (Intimidation +2), Outdoors 5 (Tracking +2), Perception 4, Stealth 4",
        "Powers: Hardened Armor 4, Enhanced Senses (Smell), Natural Weapon",
        "Attacks: Bite/Talons: DV 6P, Attack Ratings 13/—/—/—/—",
      ].join("\n"),
      notes:
        `${SHARED_CM_NOTE} Book prints "Augmentations: Text" here, an evident typo/placeholder with no real content - omitted rather than transcribed literally. Dinosaurs are unavailable for PC purchase and resist taming/training, per book flavor text.`,
    },
  },
  {
    id: "npc-critter-bs-ares-deinonychus-bio-drone",
    name: "Ares Deinonychus Bio-Drone Prototype",
    group: "Dino-Technology",
    summary: "A Deinonychus fitted with a bio-drone harness - designed to operate in packs for recon and surgical strikes.",
    book: BODY_SHOP,
    data: {
      description: "Dino-Technology (Ares Macrotechnology). Bio-drone Deinonychus, built lighter than its larger cousins for pack tactics.",
      physicalMonitor: 12,
      stunMonitor: 12,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 12,
      initiative: initiative(8, 3),
      combat: [
        "B8 A5(7) R5 S8(10) W2 L1 I3 C2 ESS0.7",
        "AC: A1, I4",
        "Skillsofts: Clearsight 6, Close Combat 6, Stealth 6",
        "Powers: Hardened Armor 4, Enhanced Senses (Smell), Natural Weapon",
        "Augmentations: Bio-drone harness (rating 6), cybereyes (rating 3, flare compensation, low-light vision, thermographic vision, vision enhancement), cyberears (rating 3, audio enhancement, damper, select sound filter 4, spatial recognizer), kill switch, muscle replacement 2, natural weapon sheathing (rating 6)",
        "Attacks: Bite/Talons: DV 10P, Attack Ratings 21/—/—/—/—",
      ].join("\n"),
      notes: `${SHARED_CM_NOTE} Designed to operate in packs for reconnaissance and surgical strikes - forgoes the exoframe augmentations of its larger dino-drone cousins in favor of muscle replacement for its smaller size.`,
    },
  },
];
