// Gear catalog, Drones + Rigger Command Consoles chunk - eighth and final
// individual-item chunk in the Companion PACKs-aligned sequence (see
// gear.ts's header for the full rationale and chunk ordering). Only the
// PACK-bundle-buying capstone (chunk 10) remains after this.
//
// Transcribed from SR6_Core_RuleBook_noimg.pdf:
// - Drones (book pp. 299-303): Microdrones, Minidrones, Small/Medium/Large
//   Drones - continues directly from the Vehicles chunk's stat table
//   sequence (drones "use the same statistical block as vehicles," per the
//   book's own Drone Rigging section, p. 199-200) - same Handling/
//   Acceleration/Speed Interval/Top Speed/Body/Armor/Pilot/Sensor/Seats
//   stat block, captured in the free-form `stats` field.
// - Rigger Command Console (book pp. 197-198): a Rigging-chapter table, not
//   part of the Gear chapter at all - found by searching the full book text
//   for "Rigger Command Console" rather than assumed to sit near Drones.
//
// Autosofts and RCC-mountable programs (Armor, Encryption, Signal Scrubber,
// Stealth, Toolbox, Virtual Machine - book p. 198) are NOT catalogued here:
// they're generic-priced programs already covered by the Electronics
// chunk's "Autosoft" (Rating 1-9, 500¥/level) and "Cyberprogram, Basic"
// (60¥) entries in electronics.ts - the book explicitly prices autosofts
// and RCC programs the same way it prices any other Matrix program, it
// doesn't have separate named/priced catalog entries for each one. Choose
// the specific autosoft/program via the notes field when purchasing, same
// convention as magicalEquipment.ts's Spell/Spirit Focus category choice.
//
// Stat-block numbers are transcribed as printed; flavor text is paraphrased
// in our own words, same convention as every prior chunk.
//
// Known gaps in this pass, flagged rather than guessed at:
// - Nissan Samurai/Oni (medium drone) and Federated Boeing Commuter/Osprey X
//   (already in vehicles.ts) are both printed as one table row covering two
//   variants with different stats - catalogued at the cheaper/base variant
//   (Samurai) with the pricier variant's stat deltas noted in the summary,
//   same treatment as the Weapons chunk's Colt Government/Manhunter
//   variant pricing.
// - The book's "Other Makes and Models" flavor table (rebadged equivalents
//   with identical stats, same as vehicles.ts's note) doesn't apply here -
//   no equivalent table was found for drones.

import type { GearCatalogEntry } from "./gear.js";

export const dronesGear: GearCatalogEntry[] = [
  // --- Microdrones (book p. 299) ---
  {
    id: "drone-gmc-micromachine",
    name: "GMC Micromachine",
    category: "vehicle",
    subcategory: "Microdrones",
    cost: 450,
    availability: "2",
    stats: {
      "Handling (On/Off-road)": "3/6",
      Acceleration: "5",
      "Speed Interval": "5",
      "Top Speed": "25",
      Body: "0",
      Armor: "0",
      Pilot: "1",
      Sensor: "1",
      Seats: "—",
    },
    summary: "A very sophisticated children's toy with interchangeable bodies and oversized self-righting wheels. Tiny, innocuous, and fun to race.",
  },
  {
    id: "drone-shiawase-kanmushi",
    name: "Shiawase Kanmushi",
    category: "vehicle",
    subcategory: "Microdrones",
    cost: 900,
    availability: "2",
    stats: {
      "Handling (On/Off-road)": "2/3",
      Acceleration: "4",
      "Speed Interval": "5",
      "Top Speed": "15",
      Body: "0",
      Armor: "0",
      Pilot: "3",
      Sensor: "2",
      Seats: "—",
    },
    summary:
      "A four-legged crawler drone that looks like a normal insect. Great for penetrating secure facilities with gecko-tipped extremities and light weight, but extremely fragile.",
  },
  {
    id: "drone-sikorsky-bell-microskimmer-xxs",
    name: "Sikorsky-Bell Microskimmer XXS",
    category: "vehicle",
    subcategory: "Microdrones",
    cost: 850,
    availability: "2",
    stats: {
      Handling: "2",
      Acceleration: "6",
      "Speed Interval": "10",
      "Top Speed": "35",
      Body: "0",
      Armor: "0",
      Pilot: "2",
      Sensor: "1",
      Seats: "—",
    },
    summary: "About the size and shape of a bottlecap, flying via weak hoverjets. Larger cousins (miniskimmer, skimmer) stack into a single drone rack slot.",
  },
  {
    id: "drone-mct-gnat",
    name: "MCT Gnat",
    category: "vehicle",
    subcategory: "Microdrones",
    cost: 800,
    availability: "2",
    stats: {
      Handling: "3",
      Acceleration: "4",
      "Speed Interval": "10",
      "Top Speed": "30",
      Body: "0",
      Armor: "0",
      Pilot: "2",
      Sensor: "1",
      Seats: "—",
    },
    summary: "Tiny, slow, and indistinguishable from an insect without magnification. Sold in packs of 10; often swarms a target carrying mini-slap patches on its feet.",
  },

  // --- Minidrones (book p. 299-300) ---
  {
    id: "drone-gm-nissan-flip-flop",
    name: "GM-Nissan Flip-Flop",
    category: "vehicle",
    subcategory: "Minidrones",
    cost: 1000,
    availability: "2",
    stats: {
      "Handling (On/Off-road)": "2/4",
      Acceleration: "8",
      "Speed Interval": "15",
      "Top Speed": "50",
      Body: "1",
      Armor: "0",
      Pilot: "2",
      Sensor: "1",
      Seats: "—",
    },
    summary: "A tracked drone about the size of an RC car with a gyroscopic center that keeps it upright even while tumbling. Great for all-terrain use.",
  },
  {
    id: "drone-shiawase-inu",
    name: "Shiawase Inu",
    category: "vehicle",
    subcategory: "Minidrones",
    cost: 1100,
    availability: "2",
    stats: {
      "Handling (On/Off-road)": "2/3",
      Acceleration: "6",
      "Speed Interval": "8",
      "Top Speed": "24",
      Body: "1",
      Armor: "0",
      Pilot: "2",
      Sensor: "2",
      Seats: "—",
    },
    summary: "A little four-legged friend with a furry suit for a more realistic look and feel. Better suits (500¥) look even more like a real dog.",
  },
  {
    id: "drone-horizon-flying-eye",
    name: "Horizon Flying Eye",
    category: "vehicle",
    subcategory: "Minidrones",
    cost: 2000,
    availability: "2",
    stats: {
      Handling: "3",
      Acceleration: "15",
      "Speed Interval": "15",
      "Top Speed": "40",
      Body: "1",
      Armor: "0",
      Pilot: "2",
      Sensor: "2",
      Seats: "—",
    },
    summary:
      "A spherical eyeball-sized flying drone using omnidirectional thrust nozzles, can also roll on the ground. Usually for surveillance; a flash-pak or smoke-grenade version costs +500¥.",
  },
  {
    id: "drone-mct-hornet",
    name: "MCT Hornet",
    category: "vehicle",
    subcategory: "Minidrones",
    cost: 2100,
    availability: "2",
    stats: {
      Handling: "3",
      Acceleration: "20",
      "Speed Interval": "15",
      "Top Speed": "35",
      Body: "1",
      Armor: "0",
      Pilot: "2",
      Sensor: "2",
      Seats: "—",
    },
    summary: "A bulkier kin of the Fly-Spy that achieves greater altitude, serving as an eye in the sky - or carrying a narrow injector dose for close work.",
  },

  // --- Small Drones (book p. 300) ---
  {
    id: "drone-chrysler-nissan-pursuit-v",
    name: "Chrysler-Nissan Pursuit V",
    category: "vehicle",
    subcategory: "Small Drones",
    cost: 11000,
    availability: "3",
    stats: {
      "Handling (On/Off-road)": "3/6",
      Acceleration: "30",
      "Speed Interval": "50",
      "Top Speed": "280",
      Body: "4",
      Armor: "2",
      Pilot: "4",
      Sensor: "3",
      Seats: "—",
    },
    summary: "Low, flat, heavy, and built for Formula One speeds - nothing with wheels outruns it.",
  },
  {
    id: "drone-aztechnology-crawler",
    name: "Aztechnology Crawler",
    category: "vehicle",
    subcategory: "Small Drones",
    cost: 4500,
    availability: "2",
    stats: {
      "Handling (On/Off-road)": "3/4",
      Acceleration: "8",
      "Speed Interval": "10",
      "Top Speed": "30",
      Body: "6",
      Armor: "2",
      Pilot: "2",
      Sensor: "2",
      Seats: "—",
    },
    summary: "A half-meter-wide multi-terrain drone designed for skittering up stairs and through underbrush - terrifying if you're not a fan of spiders.",
  },
  {
    id: "drone-cyberspace-designs-quadrotor",
    name: "Cyberspace Designs Quadrotor",
    category: "vehicle",
    subcategory: "Small Drones",
    cost: 5000,
    availability: "2",
    stats: {
      Handling: "2",
      Acceleration: "15",
      "Speed Interval": "20",
      "Top Speed": "120",
      Body: "3",
      Armor: "1",
      Pilot: "3",
      Sensor: "2",
      Seats: "—",
    },
    summary:
      "A small, lightweight quadcopter for aerial surveillance with some of the highest altitude on the market. Can only mount an air-powered crossbow (Projectile, DV 3P, Attack Ratings 2/10/4/2/—).",
  },
  {
    id: "drone-lockheed-optic-x2",
    name: "Lockheed Optic-X2",
    category: "vehicle",
    subcategory: "Small Drones",
    cost: 18000,
    availability: "3",
    stats: {
      Handling: "4",
      Acceleration: "15",
      "Speed Interval": "30",
      "Top Speed": "140",
      Body: "2",
      Armor: "4",
      Pilot: "4",
      Sensor: "4",
      Seats: "—",
    },
    summary: "Cyberdeck-sized with wings folded; deploys to hawk-size and arm-tosses into flight (VSTOL, can't hover). Hard to track and spot; a favorite of shadowrunners.",
  },

  // --- Medium Drones (book p. 300-301) ---
  {
    id: "drone-gm-nissan-doberman",
    name: "GM-Nissan Doberman",
    category: "vehicle",
    subcategory: "Medium Drones",
    cost: 6500,
    availability: "2",
    stats: {
      "Handling (On/Off-road)": "3/5",
      Acceleration: "10",
      "Speed Interval": "15",
      "Top Speed": "100",
      Body: "4",
      Armor: "6",
      Pilot: "2",
      Sensor: "3",
      Seats: "—",
    },
    summary: "A tracked perimeter-patrol drone with a solid sensor suite for day or night, unsuited for stairs. Comes with a standard weapon mount.",
  },
  {
    id: "drone-nissan-samurai",
    name: "Nissan Samurai",
    category: "vehicle",
    subcategory: "Medium Drones",
    cost: 4500,
    availability: "2",
    stats: {
      "Handling (On/Off-road)": "3/4",
      Acceleration: "10",
      "Speed Interval": "10",
      "Top Speed": "30",
      Body: "6",
      Armor: "6",
      Pilot: "3",
      Sensor: "2",
      Seats: "—",
    },
    summary:
      "A bipedal anthroform drone with retractable blades on arms and heels; each arm has a standard weapon mount fitting SMG-size or smaller with 50 rounds. Can bend for four-limbed movement but loses weapon access while doing so. A large-category military variant, the Oni, costs 6,700¥ with Speed Interval 8/Body 9/Armor 10 and rifle-sized (100-round) arm mounts.",
  },
  {
    id: "drone-mct-nissan-roto-drone",
    name: "MCT-Nissan Roto-Drone",
    category: "vehicle",
    subcategory: "Medium Drones",
    cost: 5000,
    availability: "2",
    stats: {
      Handling: "3",
      Acceleration: "20",
      "Speed Interval": "30",
      "Top Speed": "160",
      Body: "5",
      Armor: "6",
      Pilot: "3",
      Sensor: "2",
      Seats: "—",
    },
    summary:
      "A rotor-top drone over a customizable lower body - a camera drone swaps to an assault drone in under a minute. Treat Body as 3 higher when figuring weapon mounts/customizations.",
  },
  {
    id: "drone-federated-boeing-blackhawk",
    name: "Federated Boeing Blackhawk",
    category: "vehicle",
    subcategory: "Medium Drones",
    cost: 8000,
    availability: "3",
    stats: {
      Handling: "3",
      Acceleration: "35",
      "Speed Interval": "40",
      "Top Speed": "200",
      Body: "8",
      Armor: "6",
      Pilot: "3",
      Sensor: "3",
      Seats: "—",
    },
    summary: "A small-profile attack drone popular with Desert Wars teams, hard to tag. Tends to fly in coordinated packs leaving no escape.",
  },

  // --- Large Drones (book p. 301) ---
  {
    id: "drone-steel-lynx-combat",
    name: "Steel Lynx Combat Drone",
    category: "vehicle",
    subcategory: "Large Drones",
    cost: 25000,
    availability: "4",
    stats: {
      "Handling (On/Off-road)": "3/5",
      Acceleration: "15",
      "Speed Interval": "15",
      "Top Speed": "80",
      Body: "12",
      Armor: "16",
      Pilot: "4",
      Sensor: "4",
      Seats: "—",
    },
    summary: "What people mean by \"killing machine\" - armed and armored to the teeth on four telescoping wheeled limbs. Gains a bonus Minor Action when using Take Cover.",
  },
  {
    id: "drone-ares-packmule",
    name: "Ares Packmule",
    category: "vehicle",
    subcategory: "Large Drones",
    cost: 10000,
    availability: "3",
    stats: {
      "Handling (On/Off-road)": "3/4",
      Acceleration: "6",
      "Speed Interval": "5",
      "Top Speed": "30",
      Body: "8",
      Armor: "6",
      Pilot: "2",
      Sensor: "1",
      Seats: "—",
    },
    summary: "A four-legged cargo hauler ('Hauling Ass') for rough terrain. Spec-ops teams often ditch a line of cargo boxes for a gyro-mounted HMG turret instead.",
  },
  {
    id: "drone-cyberspace-designs-dalmatian",
    name: "Cyberspace Designs Dalmatian",
    category: "vehicle",
    subcategory: "Large Drones",
    cost: 10000,
    availability: "3",
    stats: {
      Handling: "3",
      Acceleration: "13",
      "Speed Interval": "20",
      "Top Speed": "130",
      Body: "6",
      Armor: "4",
      Pilot: "3",
      Sensor: "3",
      Seats: "—",
    },
    summary: "A VTOL recon drone that folds down to lawn-mower size for easy transport, frequently spotted on patrol/surveillance contracts.",
  },
  {
    id: "drone-ares-black-sky",
    name: "Ares Black Sky",
    category: "vehicle",
    subcategory: "Large Drones",
    cost: 43000,
    availability: "5",
    stats: {
      Handling: "2",
      Acceleration: "25",
      "Speed Interval": "50",
      "Top Speed": "300",
      Body: "8",
      Armor: "10",
      Pilot: "4",
      Sensor: "4",
      Seats: "—",
    },
    summary: "Ares' latest stealth air-to-ground support drone - drops supplies or rains down hell with minimal chance of detection.",
  },

  // --- Rigger Command Console (book p. 197-198) ---
  {
    id: "rcc-scratch-built-junk",
    name: "Scratch-built Junk (RCC)",
    category: "vehicle",
    subcategory: "Rigger Command Consoles",
    cost: 1400,
    availability: "1L",
    stats: { "Device Rating": "1", "Data Processing": "3", Firewall: "2" },
    summary: "Lets a rigger control multiple slaved drones/vehicles at once (rating x 3 slaved units) and issue one command to all as a Minor Action.",
  },
  {
    id: "rcc-allegiance-control-center",
    name: "Allegiance Control Center (RCC)",
    category: "vehicle",
    subcategory: "Rigger Command Consoles",
    cost: 8000,
    availability: "3L",
    stats: { "Device Rating": "2", "Data Processing": "3", Firewall: "3" },
    summary: "Lets a rigger control multiple slaved drones/vehicles at once (rating x 3 slaved units) and issue one command to all as a Minor Action.",
  },
  {
    id: "rcc-essy-motors-dronemaster",
    name: "Essy Motors DroneMaster (RCC)",
    category: "vehicle",
    subcategory: "Rigger Command Consoles",
    cost: 16000,
    availability: "3L",
    stats: { "Device Rating": "3", "Data Processing": "4", Firewall: "4" },
    summary: "Lets a rigger control multiple slaved drones/vehicles at once (rating x 3 slaved units) and issue one command to all as a Minor Action.",
  },
  {
    id: "rcc-horizon-overseer",
    name: "Horizon Overseer (RCC)",
    category: "vehicle",
    subcategory: "Rigger Command Consoles",
    cost: 32000,
    availability: "4L",
    stats: { "Device Rating": "4", "Data Processing": "5", Firewall: "4" },
    summary: "Lets a rigger control multiple slaved drones/vehicles at once (rating x 3 slaved units) and issue one command to all as a Minor Action.",
  },
  {
    id: "rcc-maersk-spider",
    name: "Maersk Spider (RCC)",
    category: "vehicle",
    subcategory: "Rigger Command Consoles",
    cost: 34000,
    availability: "5L",
    stats: { "Device Rating": "4", "Data Processing": "4", Firewall: "5" },
    summary: "Lets a rigger control multiple slaved drones/vehicles at once (rating x 3 slaved units) and issue one command to all as a Minor Action.",
  },
  {
    id: "rcc-vulcan-liegelord",
    name: "Vulcan Liegelord (RCC)",
    category: "vehicle",
    subcategory: "Rigger Command Consoles",
    cost: 66000,
    availability: "5L",
    stats: { "Device Rating": "5", "Data Processing": "6", Firewall: "5" },
    summary: "Lets a rigger control multiple slaved drones/vehicles at once (rating x 3 slaved units) and issue one command to all as a Minor Action.",
  },
  {
    id: "rcc-proteus-poseidon",
    name: "Proteus Poseidon (RCC)",
    category: "vehicle",
    subcategory: "Rigger Command Consoles",
    cost: 68000,
    availability: "6L",
    stats: { "Device Rating": "5", "Data Processing": "5", Firewall: "6" },
    summary: "Lets a rigger control multiple slaved drones/vehicles at once (rating x 3 slaved units) and issue one command to all as a Minor Action.",
  },
  {
    id: "rcc-transys-eidolon",
    name: "Transys Eidolon (RCC)",
    category: "vehicle",
    subcategory: "Rigger Command Consoles",
    cost: 75000,
    availability: "7L",
    stats: { "Device Rating": "6", "Data Processing": "6", Firewall: "5" },
    summary: "Lets a rigger control multiple slaved drones/vehicles at once (rating x 3 slaved units) and issue one command to all as a Minor Action.",
  },
  {
    id: "rcc-ares-red-dog-series",
    name: "Ares Red Dog Series (RCC)",
    category: "vehicle",
    subcategory: "Rigger Command Consoles",
    cost: 95000,
    availability: "8L",
    stats: { "Device Rating": "6", "Data Processing": "7", Firewall: "6" },
    summary: "Lets a rigger control multiple slaved drones/vehicles at once (rating x 3 slaved units) and issue one command to all as a Minor Action.",
  },
  {
    id: "rcc-aztechnology-tlaloc",
    name: "Aztechnology Tlaloc (RCC)",
    category: "vehicle",
    subcategory: "Rigger Command Consoles",
    cost: 140000,
    availability: "9L",
    stats: { "Device Rating": "6", "Data Processing": "8", Firewall: "7" },
    summary: "Lets a rigger control multiple slaved drones/vehicles at once (rating x 3 slaved units) and issue one command to all as a Minor Action.",
  },
];
