// Gear catalog, Electronics & software chunk - fourth in the Companion
// PACKs-aligned sequence (see gear.ts's header for the full rationale and
// chunk ordering).
//
// Transcribed from SR6_Core_RuleBook_noimg.pdf, book pp. 267-277 (PDF pp.
// 268-278): Commlinks, Cyberdecks, Accessories, RFID Tags, Communications
// and Countermeasures, Software, ID and Credit, Tools, Optical and Imaging
// Devices, Visual Enhancements, Auditory Devices, Audio Enhancements, and
// Sensors. Substantially bigger than the README's original "pp. 267-273"
// estimate - the optics/audio/sensor sections (pp. 274-277) weren't named in
// that scoping at all, discovered only by reading the pages directly, same
// as every other chunk so far.
//
// This also resolves part of a gap flagged in generalGear.ts's header: the
// priced Sensors table cross-referenced from that chunk (book p. 276) is
// catalogued here (Sensor housings, arrays, single sensors). What's still
// NOT catalogued, deliberately: "Sensor Packages" (book p. 277, a reference
// table of max sensor rating per housing type) and "Sensor Functions" (book
// pp. 277-278, function/max-range only, no cost) are selection references
// for configuring a purchased sensor, not separately priced items of their
// own - there is no per-function cost printed anywhere.
//
// Stat-block numbers are transcribed as printed; flavor text is paraphrased
// in our own words, same convention as qualities.ts/gear.ts/armor.ts/
// generalGear.ts.
//
// Known gaps in this pass:
// - "Biometric reader" is printed twice in the book with identical stats -
//   once in this chapter's Accessories table (p. 268) and once in
//   generalGear.ts's Security and Restraints table (p. 278). Catalogued
//   once only, in generalGear.ts, to avoid a duplicate purchasable entry for
//   the same real-world item.
// - "Select Sound Filter" here (book p. 276) is the base electronics
//   accessory version, rating-capped at 3 per its own text; a separate,
//   higher-capped (rating 6) cyberware version exists in the Augmentations
//   chapter (not yet catalogued - future chunk) and is explicitly NOT the
//   same catalog entry.
// - "Imaging Scope" and "Periscope" both also exist as weapon accessories in
//   gear.ts (top-mounted, weapon-specific). The entries here are the
//   standalone optics versions from this chapter - distinct real items,
//   given distinct ids to avoid collision, not a duplicate of the weapon
//   accessories.
// - "Certified credstick" and "Credit account" (book p. 272 prose) are
//   payment-method concepts, not separately priced catalog items - a
//   certified credstick is simply one of the credstick types already
//   catalogued below, and a credit account's cost is folded into Lifestyle
//   costs (not modeled in this app yet) rather than being its own purchase.

import type { GearCatalogEntry } from "./gear.js";

export const electronicsGear: GearCatalogEntry[] = [
  // --- Commlinks (book p. 267) ---
  {
    id: "commlink-meta-link",
    name: "Meta Link",
    category: "electronics",
    subcategory: "Commlinks",
    cost: 100,
    availability: "2",
    summary: "The entry-level commlink.",
    stats: { deviceRating: "1", attributesDF: "1/0", activeProgramSlots: "0" },
  },
  {
    id: "commlink-sony-emperor",
    name: "Sony Emperor",
    category: "electronics",
    subcategory: "Commlinks",
    cost: 700,
    availability: "2",
    summary: "A step up from entry-level.",
    stats: { deviceRating: "2", attributesDF: "1/1", activeProgramSlots: "1" },
  },
  {
    id: "commlink-renraku-sensei",
    name: "Renraku Sensei",
    category: "electronics",
    subcategory: "Commlinks",
    cost: 1000,
    availability: "2",
    summary: "A solid mid-tier commlink.",
    stats: { deviceRating: "3", attributesDF: "2/0", activeProgramSlots: "1" },
  },
  {
    id: "commlink-erika-elite",
    name: "Erika Elite",
    category: "electronics",
    subcategory: "Commlinks",
    cost: 2500,
    availability: "2",
    summary: "An upper-mid-tier commlink.",
    stats: { deviceRating: "4", attributesDF: "2/1", activeProgramSlots: "2" },
  },
  {
    id: "commlink-hermes-ikon",
    name: "Hermes Ikon",
    category: "electronics",
    subcategory: "Commlinks",
    cost: 5000,
    availability: "3",
    summary: "A high-end commlink.",
    stats: { deviceRating: "5", attributesDF: "3/0", activeProgramSlots: "2" },
  },
  {
    id: "commlink-transys-avalon",
    name: "Transys Avalon",
    category: "electronics",
    subcategory: "Commlinks",
    cost: 8000,
    availability: "3",
    summary: "The top-of-the-line commlink.",
    stats: { deviceRating: "6", attributesDF: "3/1", activeProgramSlots: "3" },
  },

  // --- Cyberdecks (book p. 268) ---
  {
    id: "cyberdeck-erika-mcd-6",
    name: "Erika MCD-6",
    category: "electronics",
    subcategory: "Cyberdecks",
    cost: 24750,
    availability: "3(I)",
    summary: "An entry-level cyberdeck, worn like a bracer on the wrist.",
    stats: { deviceRating: "1", attributesAS: "4/3", activeProgramSlots: "2" },
  },
  {
    id: "cyberdeck-spinrad-falcon",
    name: "Spinrad Falcon",
    category: "electronics",
    subcategory: "Cyberdecks",
    cost: 61500,
    availability: "3(I)",
    summary: "A step-up cyberdeck.",
    stats: { deviceRating: "2", attributesAS: "5/4", activeProgramSlots: "4" },
  },
  {
    id: "cyberdeck-mct-360",
    name: "MCT 360",
    category: "electronics",
    subcategory: "Cyberdecks",
    cost: 95000,
    availability: "3(I)",
    summary: "A solid mid-tier cyberdeck.",
    stats: { deviceRating: "3", attributesAS: "6/5", activeProgramSlots: "6" },
  },
  {
    id: "cyberdeck-renraku-kitsune",
    name: "Renraku Kitsune",
    category: "electronics",
    subcategory: "Cyberdecks",
    cost: 107000,
    availability: "4(I)",
    summary: "An upper-mid-tier cyberdeck.",
    stats: { deviceRating: "4", attributesAS: "7/6", activeProgramSlots: "8" },
  },
  {
    id: "cyberdeck-shiawase-cyber-6",
    name: "Shiawase Cyber-6",
    category: "electronics",
    subcategory: "Cyberdecks",
    cost: 172500,
    availability: "5(I)",
    summary: "A high-end cyberdeck.",
    stats: { deviceRating: "5", attributesAS: "8/7", activeProgramSlots: "10" },
  },
  {
    id: "cyberdeck-fairlight-excalibur",
    name: "Fairlight Excalibur",
    category: "electronics",
    subcategory: "Cyberdecks",
    cost: 410600,
    availability: "6(I)",
    summary: "The top-of-the-line cyberdeck.",
    stats: { deviceRating: "6", attributesAS: "9/8", activeProgramSlots: "12" },
  },

  // --- Cyberhacks (Hack & Slash p.34) - external black-market devices that provide a
  // decker's Data Processing/Firewall pair without cyberjack surgery, for pairing with
  // a custom cyberdeck's Attack/Sleaze (or as a standalone budget option). Illegal;
  // incompatible with legally manufactured cyberdecks per the book, though this app
  // doesn't enforce Availability restrictions anywhere so that's flavor text only. ---
  {
    id: "cyberhack-rating-1",
    name: "Cyberhack (Rating 1)",
    category: "electronics",
    subcategory: "Cyberhacks",
    cost: 20000,
    availability: "3(I)",
    summary: "Entry-level black-market Data Processing/Firewall device; requires a wired connection to an implanted datajack.",
    stats: { deviceRating: "1", attributesDF: "1/3" },
  },
  {
    id: "cyberhack-rating-2",
    name: "Cyberhack (Rating 2)",
    category: "electronics",
    subcategory: "Cyberhacks",
    cost: 40000,
    availability: "4(I)",
    summary: "A step-up cyberhack.",
    stats: { deviceRating: "2", attributesDF: "2/4" },
  },
  {
    id: "cyberhack-rating-3",
    name: "Cyberhack (Rating 3)",
    category: "electronics",
    subcategory: "Cyberhacks",
    cost: 60000,
    availability: "5(I)",
    summary: "A solid mid-tier cyberhack.",
    stats: { deviceRating: "3", attributesDF: "3/5" },
  },
  {
    id: "cyberhack-rating-4",
    name: "Cyberhack (Rating 4)",
    category: "electronics",
    subcategory: "Cyberhacks",
    cost: 80000,
    availability: "6(I)",
    summary: "The top-of-the-line cyberhack.",
    stats: { deviceRating: "4", attributesDF: "3/6" },
  },

  // --- Accessories (book pp. 268-269) ---
  {
    id: "accessory-ar-gloves",
    name: "AR Gloves",
    category: "electronics",
    subcategory: "Electronics Accessories",
    cost: 150,
    availability: "1",
    summary: "Lets you manually interact with AR, \"touching\" and \"holding\" AROs with tactile force-feedback.",
    stats: { deviceRating: "3" },
  },
  {
    id: "accessory-electronic-paper",
    name: "Electronic Paper",
    category: "electronics",
    subcategory: "Electronics Accessories",
    cost: 5,
    availability: "1",
    summary: "A thin, foldable electronic sheet acting as an ultrathin monitor/touchscreen; wireless read/write.",
    stats: { deviceRating: "1" },
  },
  {
    id: "accessory-printer",
    name: "Printer",
    category: "electronics",
    subcategory: "Electronics Accessories",
    cost: 25,
    availability: "1",
    summary: "A full-color printer with attached paper supply.",
    stats: { deviceRating: "3" },
  },
  {
    id: "accessory-satellite-link",
    name: "Satellite Link",
    category: "electronics",
    subcategory: "Electronics Accessories",
    cost: 500,
    availability: "3",
    summary: "Uplinks to low-Earth-orbit comm satellites for Matrix access with no local wireless network; includes a portable dish.",
    stats: { deviceRating: "4" },
  },
  {
    id: "accessory-sim-module",
    name: "Sim Module",
    category: "electronics",
    subcategory: "Electronics Accessories",
    cost: 100,
    availability: "1",
    summary: "Full simsense experience via DNI (trodes, datajack, or implanted commlink).",
  },
  {
    id: "accessory-sim-module-hot-sim",
    name: "Sim Module (Hot-Sim)",
    category: "electronics",
    subcategory: "Electronics Accessories",
    cost: 250,
    availability: "2(I)",
    summary: "The hot-sim upgrade to a sim module, opening the full range of VR experiences at the risk of frying your brain.",
  },
  {
    id: "accessory-simrig",
    name: "Simrig",
    category: "electronics",
    subcategory: "Electronics Accessories",
    cost: 1000,
    availability: "4",
    summary: "Records sensory/emotive experience data from the wearer; used to make most simsense chips sold on the market.",
    stats: { deviceRating: "3" },
  },
  {
    id: "accessory-subvocal-mic",
    name: "Subvocal Microphone",
    category: "electronics",
    subcategory: "Electronics Accessories",
    cost: 50,
    availability: "2",
    summary: "An adhesive throat patch letting you communicate via subvocalized speech; eavesdroppers can't gain or spend Edge to overhear it.",
    stats: { deviceRating: "3" },
  },
  {
    id: "accessory-trid-projector",
    name: "Trid Projector",
    category: "electronics",
    subcategory: "Electronics Accessories",
    cost: 200,
    availability: "1",
    summary: "Projects a 3-D hologram into a five-meter cube.",
    stats: { deviceRating: "3" },
  },
  {
    id: "accessory-trodes",
    name: "Trodes",
    category: "electronics",
    subcategory: "Electronics Accessories",
    cost: 70,
    availability: "1",
    summary: "An electrode-and-ultrasound net giving a DNI connection; any style of headband, hat, or headware.",
    stats: { deviceRating: "3" },
  },

  // --- RFID Tags (book p. 269) ---
  {
    id: "rfid-standard-tags",
    name: "Standard Tags (10)",
    category: "electronics",
    subcategory: "RFID Tags",
    cost: 1,
    availability: "1",
    summary: "Basic RFID tags for geo-tagging, tracking, and access control.",
    stats: { deviceRating: "1" },
  },
  {
    id: "rfid-datachip",
    name: "Datachip",
    category: "electronics",
    subcategory: "RFID Tags",
    cost: 5,
    availability: "1",
    summary: "Offline data storage; no wireless capability, needs a universal data connector to read/write.",
    stats: { deviceRating: "1" },
  },
  {
    id: "rfid-security-stealth-tags",
    name: "Security/Stealth Tags (10)",
    category: "electronics",
    subcategory: "RFID Tags",
    cost: 10,
    availability: "2",
    summary: "Usually implanted under the skin to track people; can't be erased with a tag eraser. The stealth variant runs silent, transmitting only in preset bursts.",
    stats: { deviceRating: "3" },
  },
  {
    id: "rfid-sensor-tags",
    name: "Sensor Tags (10)",
    category: "electronics",
    subcategory: "RFID Tags",
    cost: 40,
    availability: "2",
    summary: "Records 24 hours of data from a single rating-2-or-less sensor (sold separately).",
    stats: { deviceRating: "2" },
  },

  // --- Communications and Countermeasures (book p. 271) ---
  {
    id: "comms-bug-scanner",
    name: "Bug Scanner",
    category: "electronics",
    subcategory: "Communications & Countermeasures",
    cost: 200,
    availability: "3",
    summary: "Locates wireless devices within twenty meters by signal strength.",
  },
  {
    id: "comms-data-tap",
    name: "Data Tap",
    category: "electronics",
    subcategory: "Communications & Countermeasures",
    cost: 300,
    availability: "2",
    summary: "Connects to a data cable for a direct connection to devices on either end, immune to Noise.",
  },
  {
    id: "comms-headjammer",
    name: "Headjammer",
    category: "electronics",
    subcategory: "Communications & Countermeasures",
    cost: 150,
    availability: "5(I)",
    summary: "Neutralizes implanted commlinks/cyberdecks once attached to the target device's location.",
    levels: { min: 1, max: 6 },
  },
  {
    id: "comms-jammer-area",
    name: "Jammer, Area",
    category: "electronics",
    subcategory: "Communications & Countermeasures",
    cost: 200,
    availability: "4(L)",
    summary: "Floods a spherical area with jamming noise equal to its Device Rating; rating drops by 1 per 10 meters from center.",
    levels: { min: 1, max: 6 },
  },
  {
    id: "comms-jammer-directional",
    name: "Jammer, Directional",
    category: "electronics",
    subcategory: "Communications & Countermeasures",
    cost: 200,
    availability: "4(L)",
    summary: "Floods a thirty-degree conical area with jamming noise; rating drops by 1 per 30 meters from center.",
    levels: { min: 1, max: 6 },
  },
  {
    id: "comms-micro-transceiver",
    name: "Micro-Transceiver",
    category: "electronics",
    subcategory: "Communications & Countermeasures",
    cost: 100,
    availability: "1",
    summary: "A short-range voice communicator (earbud + subvocal mic) linking with other micro-transceivers/commlinks within a kilometer.",
    stats: { deviceRating: "2" },
  },
  {
    id: "comms-tag-eraser",
    name: "Tag Eraser",
    category: "electronics",
    subcategory: "Communications & Countermeasures",
    cost: 450,
    availability: "3",
    summary: "An EMP-pulse handheld device that burns out RFID tags within five millimeters; one charge, ten-second recharge plugged in.",
  },
  {
    id: "comms-white-noise-generator",
    name: "White Noise Generator",
    category: "electronics",
    subcategory: "Communications & Countermeasures",
    cost: 50,
    availability: "3",
    summary: "Creates a random-noise field inhibiting audio surveillance; only the highest-rated generator in use counts.",
    levels: { min: 1, max: 6 },
  },

  // --- Software (book p. 272) ---
  {
    id: "software-autosoft",
    name: "Autosoft",
    category: "electronics",
    subcategory: "Software",
    cost: 500,
    availability: "1",
    summary: "Programs used to operate drones.",
    levels: { min: 1, max: 9 },
  },
  {
    id: "software-cyberprogram-basic",
    name: "Cyberprogram, Basic",
    category: "electronics",
    subcategory: "Software",
    cost: 60,
    availability: "1",
    summary: "A basic Matrix program used by regular users and hackers alike.",
  },
  {
    id: "software-cyberprogram-hacking",
    name: "Cyberprogram, Hacking",
    category: "electronics",
    subcategory: "Software",
    cost: 250,
    availability: "4(I)",
    summary: "A hacking-focused Matrix program.",
  },
  {
    id: "software-datasoft",
    name: "Datasoft",
    category: "electronics",
    subcategory: "Software",
    cost: 120,
    availability: "2",
    summary: "A mini-library covering a specific Knowledge skill subject; used the same as that Knowledge skill.",
  },
  {
    id: "software-mapsoft",
    name: "Mapsoft",
    category: "electronics",
    subcategory: "Software",
    cost: 100,
    availability: "2",
    summary: "Detailed data on a ~5,000 sq km area (streets, listings, topography, census, GPS); +1 dice pool bonus finding directions.",
  },
  {
    id: "software-shopsoft",
    name: "Shopsoft",
    category: "electronics",
    subcategory: "Software",
    cost: 150,
    availability: "2",
    summary: "Pricing/review comparison-shopping program for a specific product type; +1 dice pool bonus on Matrix Search tests to buy/sell.",
  },
  {
    id: "software-activesofts",
    name: "Activesofts",
    category: "electronics",
    subcategory: "Software",
    cost: 5000,
    availability: "4",
    summary: "Replaces a physical active skill; requires a skillwire system to use.",
    levels: { min: 1, max: 6 },
  },
  {
    id: "software-knowsofts",
    name: "Knowsofts",
    category: "electronics",
    subcategory: "Software",
    cost: 2500,
    availability: "2",
    summary: "Replicates a Knowledge skill; requires a skilljack to use. Does not have ratings.",
  },
  {
    id: "software-linguasofts",
    name: "Linguasofts",
    category: "electronics",
    subcategory: "Software",
    cost: 1500,
    availability: "1",
    summary: "Replicates a language skill; requires a skilljack to use. Cannot exceed rating 4.",
    levels: { min: 1, max: 4 },
  },
  {
    id: "software-tutorsoft",
    name: "Tutorsoft",
    category: "electronics",
    subcategory: "Software",
    cost: 400,
    availability: "Rating/3",
    summary: "A virtual private tutor for a specific skill; makes Instruction tests at rating x2 dice. Cannot teach Magic/Resonance skills.",
    levels: { min: 1, max: 6 },
  },

  // --- ID and Credit (book p. 273) ---
  {
    id: "credstick-standard",
    name: "Credstick, Standard",
    category: "electronics",
    subcategory: "ID & Credit",
    cost: 5,
    availability: "1",
    summary: "Untraceable stored-value stick, max 5,000¥.",
  },
  {
    id: "credstick-silver",
    name: "Credstick, Silver",
    category: "electronics",
    subcategory: "ID & Credit",
    cost: 20,
    availability: "1",
    summary: "Untraceable stored-value stick, max 20,000¥.",
  },
  {
    id: "credstick-gold",
    name: "Credstick, Gold",
    category: "electronics",
    subcategory: "ID & Credit",
    cost: 100,
    availability: "2",
    summary: "Untraceable stored-value stick, max 100,000¥.",
  },
  {
    id: "credstick-platinum",
    name: "Credstick, Platinum",
    category: "electronics",
    subcategory: "ID & Credit",
    cost: 500,
    availability: "3",
    summary: "Untraceable stored-value stick, max 500,000¥.",
  },
  {
    id: "credstick-ebony",
    name: "Credstick, Ebony",
    category: "electronics",
    subcategory: "ID & Credit",
    cost: 1000,
    availability: "5",
    summary: "Untraceable stored-value stick, max 1,000,000¥.",
  },
  {
    id: "id-fake-sin",
    name: "Fake SIN",
    category: "electronics",
    subcategory: "ID & Credit",
    cost: 2500,
    availability: "4(I)",
    summary: "A forged System Identification Number; rating used against verification systems. Leaves a datatrail with use, making fake SINs disposable.",
    levels: { min: 1, max: 6 },
  },
  {
    id: "id-fake-license",
    name: "Fake License",
    category: "electronics",
    subcategory: "ID & Credit",
    cost: 200,
    availability: "4(I)",
    summary: "A forged license for a restricted item/activity, tied to a specific fake SIN; rating can't exceed that SIN's rating.",
    levels: { min: 1, max: 6 },
  },

  // --- Tools (book pp. 273-274) ---
  {
    id: "tools-kit",
    name: "Kit",
    category: "electronics",
    subcategory: "Tools",
    cost: 500,
    availability: "1",
    summary: "Portable basic-repair gear for a specific skill; without at least a kit in the field, a skill may not be usable actively.",
  },
  {
    id: "tools-shop",
    name: "Shop",
    category: "electronics",
    subcategory: "Tools",
    cost: 5000,
    availability: "4",
    summary: "Transportable (fits in a van) advanced tools; +1 dice pool modifier for appropriate on-site tests. Stocked with standard spare parts.",
  },
  {
    id: "tools-facility",
    name: "Facility",
    category: "electronics",
    subcategory: "Tools",
    cost: 50000,
    availability: "7",
    summary: "An immobile building-based workshop for advanced construction/modification; same bonus and parts as a Shop, plus a bonus Edge usable on Extended tests within it.",
  },

  // --- Optical and Imaging Devices (book pp. 274-275) ---
  {
    id: "optics-binoculars",
    name: "Binoculars",
    category: "electronics",
    subcategory: "Optical & Imaging Devices",
    cost: 50,
    availability: "1",
    summary: "Handheld with built-in vision magnification; electronic version, can take a variety of vision enhancements.",
    levels: { min: 1, max: 3 },
  },
  {
    id: "optics-binoculars-optical",
    name: "Binoculars, Optical",
    category: "electronics",
    subcategory: "Optical & Imaging Devices",
    cost: 50,
    availability: "1",
    summary: "Non-electronic binoculars; can only take the image link enhancement. Spellcasters can use these to cast at distant targets.",
  },
  {
    id: "optics-camera",
    name: "Camera",
    category: "electronics",
    subcategory: "Optical & Imaging Devices",
    cost: 100,
    availability: "1",
    summary: "Captures still photos, video, and trideo; can be upgraded with vision and audio enhancements.",
    levels: { min: 1, max: 6 },
  },
  {
    id: "optics-micro-camera",
    name: "Micro-Camera",
    category: "electronics",
    subcategory: "Optical & Imaging Devices",
    cost: 100,
    availability: "1",
    summary: "A Capacity-1 miniature camera.",
  },
  {
    id: "optics-contacts",
    name: "Contacts",
    category: "electronics",
    subcategory: "Optical & Imaging Devices",
    cost: 200,
    availability: "2",
    summary: "Worn directly on the eyes; nearly undetectable but with little enhancement Capacity. Must be wireless.",
    levels: { min: 1, max: 3 },
  },
  {
    id: "optics-endoscope",
    name: "Endoscope",
    category: "electronics",
    subcategory: "Optical & Imaging Devices",
    cost: 250,
    availability: "3",
    summary: "A meter-plus fiber-optic cable with a myomeric-rope tip and optical lens, for looking around corners or into narrow spaces.",
  },
  {
    id: "optics-glasses",
    name: "Glasses",
    category: "electronics",
    subcategory: "Optical & Imaging Devices",
    cost: 100,
    availability: "1",
    summary: "Lightweight frame-mounted lenses; hard to distinguish from ordinary prescription glasses.",
    levels: { min: 1, max: 4 },
  },
  {
    id: "optics-goggles",
    name: "Goggles",
    category: "electronics",
    subcategory: "Optical & Imaging Devices",
    cost: 50,
    availability: "1",
    summary: "Large, bulky, head-strapped; hard to dislodge, with room for a wide array of vision enhancements.",
    levels: { min: 1, max: 6 },
  },
  {
    id: "optics-imaging-scope",
    name: "Imaging Scope (Optics)",
    category: "electronics",
    subcategory: "Optical & Imaging Devices",
    cost: 300,
    availability: "1",
    summary: "A standalone vision-enhancer/display device (distinct from the weapon-mounted top accessory of the same name).",
    stats: { capacity: "3" },
  },
  {
    id: "optics-monocle",
    name: "Monocle",
    category: "electronics",
    subcategory: "Optical & Imaging Devices",
    cost: 120,
    availability: "1",
    summary: "Worn on a headband/helmet with a flip-down arm, or old-fashioned on a smart-adhesive chain.",
    levels: { min: 1, max: 4 },
  },
  {
    id: "optics-mage-sight-goggles",
    name: "Mage Sight Goggles",
    category: "electronics",
    subcategory: "Optical & Imaging Devices",
    cost: 3000,
    availability: "5",
    summary: "Heavy goggles connected via myomeric rope (10/20/30m) to an optical lens, letting spellcasters gain line of sight while staying out of sight.",
  },
  {
    id: "optics-periscope",
    name: "Periscope (Optics)",
    category: "electronics",
    subcategory: "Optical & Imaging Devices",
    cost: 50,
    availability: "2",
    summary: "An L-shaped two-mirror tube for looking, shooting, or casting around corners (distinct from the weapon-mounted top accessory of the same name).",
  },

  // --- Visual Enhancements (book p. 275) ---
  {
    id: "visual-enh-flare-compensation",
    name: "Flare Compensation",
    category: "electronics",
    subcategory: "Visual Enhancements",
    cost: 250,
    availability: "1",
    summary: "Protects against blinding flashes/glare; bonus Edge if the opposition lacks the same, reduces flash-pak-style penalties.",
    stats: { capacityCost: "1" },
  },
  {
    id: "visual-enh-image-link",
    name: "Image Link",
    category: "electronics",
    subcategory: "Visual Enhancements",
    cost: 25,
    availability: "1",
    summary: "Displays visual AR information in your field of vision; required to truly \"see\" AR.",
    stats: { capacityCost: "1" },
  },
  {
    id: "visual-enh-low-light-vision",
    name: "Low-Light Vision",
    category: "electronics",
    subcategory: "Visual Enhancements",
    cost: 500,
    availability: "2",
    summary: "See normally down to starlight levels (not total darkness); bonus Edge if opposition lacks the same.",
    stats: { capacityCost: "1" },
  },
  {
    id: "visual-enh-smartlink",
    name: "Smartlink (Optics)",
    category: "electronics",
    subcategory: "Visual Enhancements",
    cost: 2000,
    availability: "2",
    summary: "The vision-accessory side of a smartgun system; range, ammo, and a targeting dot when the linked gun is in view.",
    stats: { capacityCost: "2" },
  },
  {
    id: "visual-enh-thermographic-vision",
    name: "Thermographic Vision",
    category: "electronics",
    subcategory: "Visual Enhancements",
    cost: 500,
    availability: "2",
    summary: "Infrared vision to spot heat patterns, living beings in darkness, recently-run machinery, etc.",
    stats: { capacityCost: "1" },
  },
  {
    id: "visual-enh-ultrasound-link",
    name: "Ultrasound Link",
    category: "electronics",
    subcategory: "Visual Enhancements",
    cost: 300,
    availability: "1",
    summary: "The visual overlay for an ultrasound accessory.",
    stats: { capacityCost: "1" },
  },
  {
    id: "visual-enh-vision-enhancement",
    name: "Vision Enhancement",
    category: "electronics",
    subcategory: "Visual Enhancements",
    cost: 500,
    availability: "1",
    summary: "Sharpens vision at all ranges; +1 dice pool bonus to visual Perception tests.",
    stats: { capacityCost: "2" },
  },
  {
    id: "visual-enh-vision-magnification",
    name: "Vision Magnification",
    category: "electronics",
    subcategory: "Visual Enhancements",
    cost: 250,
    availability: "1",
    summary: "Digital zoom up to 50x; +2 Attack Rating at Medium/Far/Extreme range for attacks with a non-zero rating there.",
    stats: { capacityCost: "1" },
  },

  // --- Auditory Devices (book pp. 275-276) ---
  {
    id: "audio-directional-microphone",
    name: "Directional Microphone",
    category: "electronics",
    subcategory: "Auditory Devices",
    cost: 50,
    availability: "2",
    summary: "Listen in on conversations up to 100m away; must be pointed at the target, blocked by solid objects/loud sound.",
    levels: { min: 1, max: 6 },
  },
  {
    id: "audio-earbuds",
    name: "Earbuds",
    category: "electronics",
    subcategory: "Auditory Devices",
    cost: 50,
    availability: "1",
    summary: "Hard-to-spot ergonomic earplugs, hard to tell from standard music-player earbuds.",
    levels: { min: 1, max: 3 },
  },
  {
    id: "audio-headphones",
    name: "Headphones",
    category: "electronics",
    subcategory: "Auditory Devices",
    cost: 50,
    availability: "1",
    summary: "A full adjustable headset; bulk allows more Capacity.",
    levels: { min: 1, max: 6 },
  },
  {
    id: "audio-laser-mic",
    name: "Laser Microphone",
    category: "electronics",
    subcategory: "Auditory Devices",
    cost: 100,
    availability: "2",
    summary: "Reads vibrations off a solid surface via laser to reconstruct sound on the other side; max range 100m.",
    levels: { min: 1, max: 6 },
  },
  {
    id: "audio-omnidirectional-mic",
    name: "Omni-Directional Microphone",
    category: "electronics",
    subcategory: "Auditory Devices",
    cost: 50,
    availability: "1",
    summary: "A standard audio pickup, usually built into or linked with a commlink/recorder. Micro versions: Capacity 1 only, 5m range.",
    levels: { min: 1, max: 6 },
  },

  // --- Audio Enhancements (book p. 276) ---
  {
    id: "audio-enh-audio-enhancement",
    name: "Audio Enhancement",
    category: "electronics",
    subcategory: "Audio Enhancements",
    cost: 500,
    availability: "1",
    summary: "Hear a broader frequency spectrum with fine discrimination; +1 dice pool bonus to aural Perception tests.",
    stats: { capacityCost: "1" },
  },
  {
    id: "audio-enh-select-sound-filter",
    name: "Select Sound Filter",
    category: "electronics",
    subcategory: "Audio Enhancements",
    cost: 250,
    availability: "3",
    summary: "Blocks background noise and isolates chosen sound patterns (footsteps, a word, rotor blades); loads a number of patterns up to its Rating. Non-cyberware version, capped at Rating 3.",
    levels: { min: 1, max: 3 },
  },
  {
    id: "audio-enh-spatial-recognizer",
    name: "Spatial Recognizer",
    category: "electronics",
    subcategory: "Audio Enhancements",
    cost: 1000,
    availability: "2",
    summary: "Pinpoints the source of a sound; bonus Edge on Perception tests to find it (lost if not used immediately).",
    stats: { capacityCost: "2" },
  },

  // --- Sensors (book pp. 276-277) ---
  {
    id: "sensor-handheld-housing",
    name: "Handheld Sensor Housing",
    category: "electronics",
    subcategory: "Sensors",
    cost: 100,
    availability: "1",
    summary: "A portable case for mounting sensors.",
    levels: { min: 1, max: 3 },
  },
  {
    id: "sensor-wall-mounted-housing",
    name: "Wall-Mounted Sensor Housing",
    category: "electronics",
    subcategory: "Sensors",
    cost: 250,
    availability: "1",
    summary: "A fixed-installation case for mounting sensors.",
    levels: { min: 1, max: 6 },
  },
  {
    id: "sensor-array",
    name: "Sensor Array",
    category: "electronics",
    subcategory: "Sensors",
    cost: 1000,
    availability: "3",
    summary: "Includes up to its Rating in functions chosen from the Sensor Functions list. When used for Perception tests, its rating can substitute for the Perception skill.",
    levels: { min: 2, max: 8 },
  },
  {
    id: "sensor-single",
    name: "Single Sensor",
    category: "electronics",
    subcategory: "Sensors",
    cost: 100,
    availability: "2",
    summary: "A sensor performing only one function from the Sensor Functions list.",
    levels: { min: 1, max: 8 },
  },
];
