// Firing Squad (Combat Sourcebook) chunk of the NPC template catalog - see
// npcTemplates.ts's header for the full rationale (same NpcTemplateEntry
// shape). Kept in its own file the same way every other sourcebook chunk
// is split out.
//
// Transcribed from Firing_Squad__Combat_Sourcebook__noimg.pdf, "Fighting
// Forces" chapter, book pp. 135-150: Corporate Security Forces (Lone Star,
// Knight Errant, five smaller "Other Security Providers" corps, and the
// Humanis Policlub paramilitary) and Gangs (Ancients, Halloweeners,
// Cutters, First Nations, Smokers Club). 35 entries total - the complete
// Fighting Forces roster (the chapter's own stat-block content ends where
// the "Game Information / Weapon & Armor Stats" gear tables begin).
//
// Stat-block numbers are transcribed as printed; flavor text is
// paraphrased in our own words, same convention as every other catalog
// file in this project.
//
// Known gaps/notes, flagged rather than guessed at:
// - `armor` is derived as (printed Defense Rating) - (printed base Body),
//   the same convention already used elsewhere in this catalog. For a
//   handful of entries with augmentations that also boost Body itself
//   (e.g. Centurion's bone density augmentation), the book's own DR math
//   compounds in ways a compact stat block doesn't fully expose - the
//   derived armor number may be off by a point or two from "just the
//   printed gear's own (+N)" for those entries specifically.
// - The Humanis Paramilitary Rigger (p. 143) arrives with an armed Toyota
//   Gopher pickup truck and an escort of Horizon Flying Eye drones (plus
//   an on-call Ares Black Sky combat drone) - vehicle/drone stat blocks
//   are out of scope for this roster (same boundary as every other
//   sourcebook chunk here), so only the rigger's own personal stats are
//   transcribed; the vehicle/drone support is noted in `notes` instead.
// - The three Ancients archetypes (Racer, Gunner, Mage) print with elf
//   racial adjustments already baked into their attributes, per the
//   book's own callout - transcribed as printed, noted in each entry.

import type { NpcTemplateEntry } from "./npcTemplates.js";

const FIRING_SQUAD = "Firing Squad";

/** "X/Y" printed Initiative rank/Initiative Dice -> "X + Yd6". */
function initiative(rank: number, dice: number): string {
  return `${rank} + ${dice}d6`;
}

const CM_NOTE =
  "Condition Monitor is ONE combined Physical+Stun track per SR6's grunt rules (core rulebook p. 204) - treat the Physical and Stun trackers below as a single shared pool, not two separate ones.";

export const firingSquadTemplates: NpcTemplateEntry[] = [
  // --- Lone Star (book pp. 135-137) ---
  {
    id: "npc-fs-lonestar-street-veteran",
    name: "Lone Star Street Veteran",
    group: "Lone Star",
    summary: "A beat cop with a little cyber and a lot more experience, working the tough neighborhoods runners like to doss down in.",
    book: FIRING_SQUAD,
    data: {
      description: "Lone Star, Professional Rating 3. Reports in and uses cover/tactics rather than charging in.",
      physicalMonitor: 10,
      stunMonitor: 10,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 6,
      initiative: initiative(10, 1),
      combat: [
        "B4 A3(4) R4(6) S3(4) W4 L4 I4 C4 ESS3.9",
        "AC: A1, I2",
        "Skills: Athletics 3, Biotech 1, Close Combat 4, Electronics 1, Firearms 4, Influence 3, Outdoors 2, Perception 4, Stealth 2",
        "Augmentations: Cybereyes (rating 2, w/ camera, flare compensation, image link, smartlink), dermal plating 2, muscle replacement 1, reaction enhancers 2",
        "Gear: Armor jacket (+4), commlink (DR 4), flashlight, Jazz (2 doses)",
        "Weapons: Colt Manhunter [Heavy Pistol, DV 3P, SA, 10/8/6/—/—, w/ smartgun]; Defiance Super Shock [Taser, DV 6S(e), SS, 10/6*/—/—/—, w/ smartgun; *max range 20m]; Stun baton [Club, DV 5S(e), 6/—/—/—/—]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },
  {
    id: "npc-fs-lonestar-swat-doorkicker",
    name: "Lone Star SWAT Doorkicker",
    group: "Lone Star",
    summary: "Augmentation-built special operators, called in for hostage situations and high-risk targets, built around teamwork.",
    book: FIRING_SQUAD,
    data: {
      description: "Lone Star, Professional Rating 4. Coordinated assault team, not the lone-magic type.",
      physicalMonitor: 12,
      stunMonitor: 12,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 7,
      initiative: initiative(12, 2),
      combat: [
        "B7 A4(8) R5(6) S6(10) W5 L3 I6 C4 ESS1.2",
        "AC: A1, I3",
        "Skills: Athletics 4 (Throwing +2), Biotech 2, Close Combat 5 (Unarmed +2), Firearms 6, Influence 4 (Intimidation +3), Outdoors 3 (Tracking +2), Perception 6, Stealth 3",
        "Augmentations: Cybereyes (rating 2, w/ image link, camera, low-light, vision enhancement), cyberears (rating 2, w/ sound link, damper, audio enhancement, select sound filter 2), dermal plating 2, muscle replacement 4, wired reflexes 1",
        "Gear: Commlink (DR 6), Security armor w/ helmet (+7)",
        "Weapons: Colt M23 [Rifle, DV 5P, SA/BF/FA, Attack Ratings 7/10/10/10/6, w/ smartgun, explosive ammo]; Colt Manhunter [Heavy Pistol, DV 3P, SA, 10/8/6/—/—, w/ smartgun]; Mossberg CMDT [Shotgun, DV 5P, SA/BF, 5/12/7/—/—, w/ smartgun, explosive ammo]; Stun baton [Club, DV 5S(e), 6/—/—/—/—]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },
  {
    id: "npc-fs-lonestar-mage-corps",
    name: "Lone Star Mage Corps",
    group: "Lone Star",
    summary: "Wide-spread arcane support (astral overwatch, warding, spirit backup) rather than specialist combat mages.",
    book: FIRING_SQUAD,
    data: {
      description: "Lone Star, Professional Rating 5. Rarely without an air spirit escort.",
      physicalMonitor: 11,
      stunMonitor: 11,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 7,
      initiative: initiative(9, 1),
      combat: [
        "B3 A4 R4 S2 W5 L5 I5 C5 M5 ESS6",
        "AC: A1, I2",
        "Skills: Astral 6 (Emotional States +2), Athletics 2, Biotech 2, Close Combat 2, Conjuring 4 (Summoning +2), Electronics 1, Enchanting 2, Firearms 3 (Pistols +2), Influence 2 (Intimidation +2), Perception 5 (Urban +2), Piloting 1, Sorcery 5 (Spellcasting +2), Stealth 1 (Urban +2)",
        "Spells: Armor, Blast, Clairvoyance, Clout, Combat Sense, Confusion, Detect Enemies, Detect Magic, Heal, Increase Reflexes, Levitate, Light, Physical Barrier, Stunbolt",
        "Gear: Commlink (DR 5), full body armor w/ helmet (+7)",
        "Weapons: Colt Manhunter [Heavy Pistol, DV 3P, SA, 10/8/6/—/—, w/ laser sight]; Stun baton [Club, DV 5S(e), 6/—/—/—/—]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },
  {
    id: "npc-fs-lonestar-shadowrider",
    name: "Lone Star Shadowrider",
    group: "Lone Star",
    summary: "Off-the-books hunter-killer teams, deployed against homicidal runners with no warrant, no warning, and no mercy.",
    book: FIRING_SQUAD,
    data: {
      description: "Lone Star, Professional Rating 7. Blends in anywhere, shoots first.",
      physicalMonitor: 11,
      stunMonitor: 11,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 6,
      initiative: initiative(12, 3),
      combat: [
        "B6 A5(7) R5(7) S5(7) W4 L3 I5 C4 ESS1.6",
        "AC: A1, I4",
        "Skills: Athletics 7, Biotech 2 (First Aid +2), Close Combat 6 (Clubs +2), Electronics 2, Firearms 7 (Pistols +2), Influence 5 (Intimidation +3), Outdoors 2, Perception 6 (Hearing +2, Visual +3), Piloting 4 (Ground Craft +2), Stealth 5",
        "Augmentations: Cyberears (rating 2, w/ sound link, damper, audio enhancement, select sound filter 2), cybereyes (rating 2, w/ image link, camera, low-light, vision enhancement), dermal plating 2, muscle replacement 2, wired reflexes 2",
        "Gear: Armor jacket (+4), commlink (DR 4)",
        "Weapons: Colt Manhunter [Heavy Pistol, DV 3P, SA, 10/8/6/—/—, w/ laser sight]; Defiance Super Shock [Taser, DV 6S(e), SS, 10/6*/—/—/—, w/ smartgun; *max range 20m]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },

  // --- Knight Errant (book pp. 136-137) ---
  {
    id: "npc-fs-ke-firewatch",
    name: "Knight Errant Firewatch",
    group: "Knight Errant",
    summary: "Cross-trained special-problem solvers with mil-spec gear, best known for mopping up insect spirit incursions.",
    book: FIRING_SQUAD,
    data: {
      description: "Knight Errant, Professional Rating 5. Distrusts everyone near a bug-spirit incident, allies included.",
      physicalMonitor: 11,
      stunMonitor: 11,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 11,
      initiative: initiative(11, 3),
      combat: [
        "B5 A4(7) R4(6) S4(7) W5 L3 I5 C4 ESS0.2",
        "AC: A1, I4",
        "Skills: Athletics 6 (Throwing +2), Biotech 2 (First Aid +2), Close Combat 7, Engineering 4, Firearms 7 (Rifles +2), Influence 5 (Intimidation +3), Outdoors 5, Perception 6 (Visual +2), Piloting 3 (Ground Craft +2), Stealth 5 (Urban +3)",
        "Augmentations: Cyberears (rating 4, w/ sound link, balance augmenter, damper, audio enhancement, select sound filter 4, spatial recognizer), cybereyes (rating 4, w/ full suite), dermal plating 3, muscle replacement 3, wired reflexes 2",
        "Gear: Bug Stomper armor (+8), commlink (DR 5), Horizon Flying Eye",
        "Weapons: Ares Predator VI [Heavy Pistol, DV 4P, Attack Ratings 11/11/9/—/—, w/ smartgun, explosive ammo]; Fragmentation grenade [DV 16P, 12P, 8P; Blast 20m]; Ares Alpha [Rifle, DV 5P, SA/BF/FA, 4/10/9/7/2, w/ smartgun, explosive ammo, underbarrel grenade launcher]",
      ].join("\n"),
      notes: `${CM_NOTE} Arrives with a Horizon Flying Eye surveillance drone (drone stats not modeled here).`,
    },
  },
  {
    id: "npc-fs-ke-street-veteran",
    name: "Knight Errant Street Veteran",
    group: "Knight Errant",
    summary: "A KE beat-walker in the black-and-red straight coat, good source of information or the ones gunning for you.",
    book: FIRING_SQUAD,
    data: {
      description: "Knight Errant, Professional Rating 4. Bends the rules, knows the neighborhood.",
      physicalMonitor: 10,
      stunMonitor: 10,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 4,
      initiative: initiative(9, 1),
      combat: [
        "B4 A4 R4(5) S3 W4 L4 I4 C4 ESS5.1",
        "AC: A1, I2",
        "Skills: Athletics 3, Biotech 1, Close Combat 5, Con 1, Electronics 1, Firearms 4, Influence 4, Perception 4, Piloting 2",
        "Augmentations: Cyberears (rating 1, w/ sound link, damper), cybereyes (rating 2, w/ image link, camera, flare compensation, low-light), dermal plating 1, reaction enhancers 1",
        "Gear: Commlink (DR 4), jazz (6 doses), longcoat (+3), restraints (10 plastic, 2 metal)",
        "Weapons: Ares Predator VI [Heavy Pistol, DV 3P, 11/11/9/—/—]; Defiance Super Shock [Taser, DV 6S(e), SS, 10/6*/—/—/—; *max range 20m]; Stun baton [Club, DV 5S(e), 6/—/—/—/—]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },
  {
    id: "npc-fs-ke-detective-mage",
    name: "Knight Errant Detective Mage",
    group: "Knight Errant",
    summary: "Investigative-division mage who tracks perps (arcane and mundane) with ritual samples - dress code optional.",
    book: FIRING_SQUAD,
    data: {
      description: "Knight Errant, Professional Rating 5. Plays defensively; not offered runs the classic 'work for your freedom' deal.",
      physicalMonitor: 11,
      stunMonitor: 11,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 2,
      initiative: initiative(8, 1),
      combat: [
        "B2 A3 R4 S2 W5 L4 I4 C5 M7 ESS6",
        "AC: A1, I2",
        "Skills: Astral 3 (Emotional States +3), Athletics 2, Biotech 1 (First Aid +2), Close Combat 1 (Clubs +2), Conjuring 3 (Summoning +3), Electronics 1, Enchanting 2, Firearms 2 (Pistol +2), Influence 4 (Negotiation +2), Perception 4 (Aural +2, Visual +3), Piloting 1 (Ground Craft +2), Sorcery 5 (Ritual Spellcasting +2, Spellcasting +3), Stealth 1 (Urban +2)",
        "Spells and Rituals: Analyze Truth, Animate Plastic, Armor, Blast, Clairaudience, Clairvoyance, Clout, Confusion, Curse, Darkness, Detect Enemies, Detect Magic, Fling, Heal, Increase Reflexes, Light, Mindlink, Mind Probe, Physical Mask, Stabilize, Trid Phantasm, Ward",
        "Initiate Grade: 1. Metamagic: Shielding",
        "Gear: Armor clothing (+2), commlink (DR 4)",
        "Weapons: Ares Light Fire 70 [Light Pistol, DV 2P, SA, 10/7/6/—/—, w/ laser sight]; Stun baton [Club, DV 5S(e), 6/—/—/—/—]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },

  // --- Other Security Providers (book pp. 137-140) ---
  {
    id: "npc-fs-security-wolverine",
    name: "Wolverine Security",
    group: "Other Security Providers",
    summary: "An Ares subsidiary running a ruthless, no-mercy SOP at remote facilities - reputation built on cruelty backed by force.",
    book: FIRING_SQUAD,
    data: {
      description: "Other Security Providers, Professional Rating 3. Wolverine Security.",
      physicalMonitor: 12,
      stunMonitor: 12,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 11,
      initiative: initiative(12, 2),
      combat: [
        "B6 A4(7) R4(8) S6(9) W2 L2 I4 C4 ESS0.2",
        "AC: A1, I3",
        "Skills: Athletics 2 (Throwing +3), Close Combat 4 (Clubs +2, Unarmed +3), Firearms 4 (Pistol +2, Automatics +3), Influence 2 (Intimidation +3), Outdoors 3 (Local Terrain +2), Perception 4 (Visual +2, Aural +3), Piloting 1 (Ground Craft +3), Stealth 3 (Local Terrain +2)",
        "Augmentations: Cyberears (rating 3, w/ sound link, damper, select sound filter 3), cybereyes (rating 3, w/ image link, camera, flare compensation, low-light, smartlink), dermal plating 4, muscle replacement 3, reaction enhancers 3, wired reflexes 1",
        "Gear: Commlink (DR 5), security armor w/ helmet (+7)",
        "Weapons: Ares Predator VI [Heavy Pistol, DV 4P, Attack Ratings 11/11/9/—/—, w/ smartgun, explosive ammo]; Fragmentation grenade [DV 16P, 12P, 8P; Blast 20m]; Ares Alpha [Rifle, DV 5P, SA/BF/FA, 4/10/9/7/2, w/ smartgun, explosive ammo, underbarrel grenade launcher]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },
  {
    id: "npc-fs-security-hard-corps",
    name: "Hard Corps Security",
    group: "Other Security Providers",
    summary: "Bargain-basement Ares security for low-rent apartments and non-vital sites - Knight Errant wannabes and cast-offs.",
    book: FIRING_SQUAD,
    data: {
      description: "Other Security Providers, Professional Rating 3. Hard Corps Security.",
      physicalMonitor: 10,
      stunMonitor: 10,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 5,
      initiative: initiative(6, 1),
      combat: [
        "B4 A2(3) R3 S2(3) W2 L2 I3 C2 ESS4.9",
        "AC: A1, I2",
        "Skills: Athletics 1, Close Combat 4, Cracking 2, Electronics 3, Engineering 4, Firearms 3, Influence 2 (Intimidation +2), Outdoors 2, Perception 3, Piloting 2, Stealth 2",
        "Augmentations: Cybereyes (rating 1, w/ image link, camera, flare compensation, low-light vision), dermal plating 1, muscle replacement 1",
        "Gear: Armor jacket (+4), commlink (DR 4), jazz (2 doses)",
        "Weapons: Ares Predator VI [Heavy Pistol, DV 3S, 11/11/9/—/—, w/ smartgun, gel ammo]; Defiance Super Shock [Taser, DV 6S(e), SS, 10/6*/—/—/—; *max range 20m]; Stun baton [Club, DV 5S(e), 6/—/—/—/—]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },
  {
    id: "npc-fs-security-minuteman",
    name: "Minuteman Security",
    group: "Other Security Providers",
    summary: "Horizon's rebranded corpsec: observe, ascertain threat, then engage - often sends a swarm of deckers in first.",
    book: FIRING_SQUAD,
    data: {
      description: "Other Security Providers, Professional Rating 4. Minuteman Security.",
      physicalMonitor: 10,
      stunMonitor: 10,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 4,
      initiative: initiative(8, 1),
      combat: [
        "B4 A4 R3(5) S3 W3 L3 I3 C4 ESS5.4",
        "AC: A1, I2",
        "Skills: Athletics 2 (Throwing Weapons +2), Biotech 1 (First Aid +2), Close Combat 4, Firearms 4, Influence 3 (Intimidation +2), Outdoors 1 (Urban +2), Perception 2 (Urban +2), Piloting 1 (Ground Craft +2), Stealth 2 (Urban +3)",
        "Augmentations: Reaction enhancers 2",
        "Gear: Armor jacket (+4), commlink (DR 5), goggles (rating 4, w/ flare compensation, image link, low-light vision, smartlink), jammer (area, rating 4), medkit, micro-transceiver, jazz (1 dose), smoke grenades (2)",
        "Weapons: Bates-Brown combat boots [Unarmed, DV 3S, (STRx2)/—/—/—/—]; Browning Ultra Power [Heavy Pistol, DV 3P, SA, 10/9/6/—/—, w/ laser sight, smartgun]; Shock gloves [Unique, DV 4S(e), 5/—/—/—/—]; Stun baton [Club, DV 5S(e), 6/—/—/—/—]; Stun grenade [DV 10S, 8S, 6S; Blast 15m]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },
  {
    id: "npc-fs-security-centurion",
    name: "Centurion",
    group: "Other Security Providers",
    summary: "Saeder-Krupp's calm, cold, methodical subsidiary - spec ops, counter-intel, and famously, gang-eradication task forces.",
    book: FIRING_SQUAD,
    data: {
      description: "Other Security Providers, Professional Rating 5. Centurion.",
      physicalMonitor: 11,
      stunMonitor: 11,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 6,
      initiative: initiative(9, 2),
      combat: [
        "B5(+3) A4(5) R4(5) S4(5) W5 L3 I4 C2 ESS2.8",
        "AC: A1, I3",
        "Skills: Athletics 3, Biotech 1 (First Aid +2), Close Combat 4 (Blades +2), Firearms 5, Influence 3 (Intimidation +3), Outdoors 4, Perception 4, Piloting 3, Stealth 4",
        "Augmentations: Bone density augmentation 3, damage compensator 6, muscle augmentation 1, muscle toner 1, orthoskin 2, platelet factories, sleep regulator, synaptic booster 1",
        "Gear: Armor jacket (+4), commlink (DR 4)",
        "Weapons: Colt Government 2076 [Heavy Pistol, DV 4P, SA, 11/9/6/—/—, w/ laser sight, explosive ammo]; Colt M23 [Rifle, DV 5P, SA/BF/FA, 6/9/9/9/5, w/ flashlight, laser sight, silencer, explosive ammo]; Xiphos Tactical Gladius [Sword, DV 3P, 10/—/—/—/—]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },
  {
    id: "npc-fs-security-eagle",
    name: "Eagle Security",
    group: "Other Security Providers",
    summary: "NAN-founded security corp with a stoic, disciplined approach and a bug-hunting special ops unit (the Pisko).",
    book: FIRING_SQUAD,
    data: {
      description: "Other Security Providers, Professional Rating 5. Eagle Security.",
      physicalMonitor: 11,
      stunMonitor: 11,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 4,
      initiative: initiative(13, 3),
      combat: [
        "B5 A3(5) R4(9) S4(6) W4 L3 I4 C3 ESS1.7",
        "AC: A1, I4",
        "Skills: Athletics 5, Biotech 1 (First Aid +2), Close Combat 4 (Clubs +2), Electronics 2, Firearms 4, Influence 3 (Intimidation +2, Leadership +3), Outdoors 5, Perception 5, Piloting 2 (Ground Craft +2), Stealth 4",
        "Augmentations: Muscle replacement 2, reaction enhancers 3, wired reflexes 2",
        "Gear: Armor jacket (+4), commlink (DR 5)",
        "Weapons: Ares Predator VI [Heavy Pistol, DV 4P, 11/11/9/—/—, w/ smartgun, explosive ammo]; Fragmentation grenade [DV 16P, 12P, 8P; Blast 20m]; High explosive grenade [DV 16P, 10P, 4P; Blast 15m]; Ares Alpha [Rifle, DV 5P, SA/BF/FA, 4/10/9/7/2, w/ smartgun, explosive ammo, underbarrel grenade launcher]; Urban Tribe Tomahawk Mk II [Blades, DV 2P, Attack Ratings 10/9*/—/—/—; *max range 20m]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },
  {
    id: "npc-fs-security-petrovski",
    name: "Petrovski Security",
    group: "Other Security Providers",
    summary: "An MCT subsidiary (hiding behind its own name) with a zero-zone policy - professional, cold, little moral compass.",
    book: FIRING_SQUAD,
    data: {
      description: "Other Security Providers, Professional Rating 4. Petrovski Security.",
      physicalMonitor: 10,
      stunMonitor: 10,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 4,
      initiative: initiative(8, 1),
      combat: [
        "B4 A5 R4 S4 W4 L3 I4 C3 ESS6",
        "AC: A1, I2",
        "Skills: Athletics 2, Biotech 2 (First Aid +2), Close Combat 4, Electronics 2, Firearms 3 (Automatics +2), Influence 1 (Intimidation +2), Perception 3, Piloting 3",
        "Gear: Armor jacket (+4), earbuds (rating 1, w/ audio enhancement), commlink (DR 4), flashlight, goggles (capacity 2, w/ image link, low-light vision), jazz (2 doses), micro-transceiver",
        "Weapons: Bates-Brown combat boots [Unarmed, DV 3S, (STRx2)/—/—/—/—]; Ares Light Fire 70 [Light Pistol, DV 2P, SA, 10/7/6/—/—, w/ laser sight]; SCK Model 100 [Submachine Gun, DV 3P, SA/BF, 11/11/8/—/—, w/ laser sight, folding stock]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },

  // --- Paramilitary Forces: Humanis Policlub (book pp. 140-144) ---
  {
    id: "npc-fs-humanis-grunt",
    name: "Humanis Grunt",
    group: "Humanis Paramilitary",
    summary: "Weekend-warrior bulk of Humanis's violent arm - impulsive, mean-spirited, and well-trained, but cowards at heart.",
    book: FIRING_SQUAD,
    data: {
      description: "Humanis Paramilitary, Professional Rating 2. Focuses fire on magicians and the biggest metahumans; breaks and runs if their sergeant falls.",
      physicalMonitor: 10,
      stunMonitor: 10,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 4,
      initiative: initiative(6, 2),
      combat: [
        "B3(+1) A3 R3(4) S3 W2 L1 I2 C2 ESS4.2",
        "AC: A1, I3",
        "Skills: Athletics 2, Close Combat 2, Firearms 4, Influence 2 (Intimidation +2), Perception 2, Stealth 1",
        "Augmentations: Bone lacing (plastic), cybereyes (rating 2, w/ image link, low-light vision, smartlink), wired reflexes 1 (used)",
        "Gear: Armor vest (+3), commlink (DR 2), flash-pak, glasses (rating 1, w/ flare compensation), fake SIN and licenses (rating 2), micro-transceiver, smoke grenade",
        "Weapons: Colt America L36 [Light Pistol, DV 3P, SA, 10/10/8/—/—, w/ internal smartlink]; Colt M23 [Rifle, DV 5P, SA/BF/FA, 6/9/9/9/5, w/ internal smartlink, imaging scope, shock pad]; Unarmed attack [DV 3P, 8/—/—/—/—]; Survival knife [Blade, DV 4P, 8/2*/—/—/—; *max range 20m if thrown]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },
  {
    id: "npc-fs-humanis-sergeant",
    name: "Humanis Paramilitary Sergeant",
    group: "Humanis Paramilitary",
    summary: "Proven Humanis zealots given better gear and command of a squad - measured retreat, not panic, if things go poorly.",
    book: FIRING_SQUAD,
    data: {
      description: "Humanis Paramilitary, Professional Rating 3. Grunts under their command are likely to panic if the sergeant falls.",
      physicalMonitor: 11,
      stunMonitor: 11,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 4,
      initiative: initiative(7, 2),
      combat: [
        "B4(+1) A3(4) R3(4) S3(4) W3 L2 I3 C2 ESS3.5",
        "AC: A1, I3",
        "Skills: Athletics 3, Close Combat 3 (Unarmed +2), Firearms 5, Influence 3 (Intimidation +2), Perception 3, Stealth 2",
        "Augmentations: Bone lacing (plastic), cyberarm (synthetic, attribute increase: Agility +1, Strength +1, cyber implant light pistol: Ares Light Fire 7S), wired reflexes 1",
        "Gear: Armor vest (+3), commlink (DR 4), micro-transceiver, smoke grenade, flash-pak, glasses (rating 4, w/ flare compensation, smartlink, thermographic vision), fake SIN and licenses (rating 3)",
        "Weapons: Implanted Ares Light Fire 75 [Light Pistol, DV 3P, SA, 8/5/4/—/—]; Colt M23 [Rifle, DV 5P, SA/BF/FA, 6/9/9/9/5, w/ internal smartgun system, imaging scope, shock pad]; Unarmed attack [DV 3P, 8/—/—/—/—]; Survival knife [Blade, DV 4P, 8/2*/—/—/—; *max range 20m if thrown]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },
  {
    id: "npc-fs-humanis-cyber-soldier",
    name: "Humanis Cyber Soldier",
    group: "Humanis Paramilitary",
    summary: "Heavily augmented zealot who breaks from the pack to snipe designated targets - brutal, effective, feels alive when killing.",
    book: FIRING_SQUAD,
    data: {
      description: "Humanis Paramilitary, Professional Rating 4. Lone-wolf type - don't combine into Grunt Group attacks.",
      physicalMonitor: 11,
      stunMonitor: 11,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 7,
      initiative: initiative(9, 3),
      combat: [
        "B4(+2) A4 R4(6) S3(5) W3 L2 I3 C2 ESS1",
        "AC: A1, I4",
        "Skills: Athletics 4, Close Combat 4 (Unarmed +2), Firearms 5 (Rifles +2), Influence 3 (Intimidation +2), Perception 3, Stealth 3",
        "Augmentations: Bone lacing (aluminum), cyberarm (obvious, attribute increase: Agility +2, Strength +2, Armor +2, gyromount, hardening), cybereyes (rating 3, low-light vision, thermographic vision, flare compensation, smartlink), damage compensator 7, wired reflexes 2",
        "Gear: Armor jacket (+4), commlink (DR 4), micro-transceiver, smoke grenade, flash-pak, fake SIN and licenses (rating 4)",
        "Weapons: Ares Predator VI [Heavy Pistol, DV 5P, SA/BF, 10/10/8/—/—, w/ smartgun system]; Cavalier Arms Crockett EBR [Rifle, DV 7P, SA/BF, 5/10/13/10/10, w/ smartgun system, imaging scope, shock pad]; Unarmed attack [DV 4P, 11/—/—/—/—]; Survival knife [Blade, DV 4P, 8/2*/—/—/—; *max range 20m if thrown]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },
  {
    id: "npc-fs-humanis-decker",
    name: "Humanis Paramilitary Decker",
    group: "Humanis Paramilitary",
    summary: "Cold-sim Matrix recon support, staying safely out of sight while scanning for icons and data to use against enemies.",
    book: FIRING_SQUAD,
    data: {
      description: "Humanis Paramilitary, Professional Rating 4. Dual-natured NPC: a metahuman decker with both a physical body and a Matrix persona.",
      physicalMonitor: 10,
      stunMonitor: 10,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 3,
      initiative: initiative(6, 2),
      combat: [
        "B2 A2 R2 S2 W3 L4(6) I4 C2 ESS3",
        "AC: A1, I3",
        "Matrix persona: A5 S4 D5(6) F6, AR 9, DR 12, Initiative 10 + 2d6, AC A1/I3, CM 9",
        "Skills: Athletics 2, Close Combat 2, Cracking 5, Electronics 5, Firearms 2, Influence 2, Perception 5, Stealth 3",
        "Augmentations: Cerebral booster 2, cybereyes (rating 2, w/ flare compensation, low-light vision), cyberjack (rating 3, used), mnemonic enhancer 2",
        "Gear: Armor vest (+3), commlink (DR 6), glasses (capacity 3, w/ smartlink, thermographic vision), fake SIN and licenses (rating 4), micro-transceiver, smoke grenade, flash-pak, Spinrad Falcon cyberdeck (DR 2, 5/4)",
        "Programs (4 slots): Baby Monitor, Biofeedback, Browse, Toolbox",
        "Weapons: Ruger Super Warhawk [Heavy Pistol, DV 5P, SA, 8/11/8/—/—, w/ laser sight]; Unarmed attack [DV 1S, 4/—/—/—/—]; Survival knife [Blade, DV 4P, 8/2*/—/—/—; *max range 20m if thrown]",
      ].join("\n"),
      notes: `${CM_NOTE} Physical stats above are its meat body; the separate Matrix persona stats are listed in the combat text.`,
    },
  },
  {
    id: "npc-fs-humanis-rigger",
    name: "Humanis Paramilitary Rigger",
    group: "Humanis Paramilitary",
    summary: "Drives the regiment's mobile command HQ, using drones for surveillance while the general rides shotgun.",
    book: FIRING_SQUAD,
    data: {
      description: "Humanis Paramilitary, Professional Rating 3. Prefers splitting dice pools across two targets over focusing one.",
      physicalMonitor: 11,
      stunMonitor: 11,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 4,
      initiative: initiative(9, 1),
      combat: [
        "B3(+1) A3 R4 S3 W4 L5 I5 C2 ESS3.0",
        "AC: A1, I2",
        "Matrix persona (rigger command console): D7 F6, DR 13, Initiative 12 + 3d6, AC A1/I4, CM 11",
        "Skills: Athletics 2, Close Combat 2, Engineering 5, Firearms 2, Influence 2, Perception 4, Piloting 5, Stealth 2",
        "Augmentations: Bone lacing (plastic), control rig (rating 2, used), cybereyes (rating 3, w/ flare compensation, smartlink, thermographic vision)",
        "Programs (6 slots): Armor, Encryption, Overclock, Signal Scrubber, Stealth, Toolbox",
        "Gear: Armor vest (+3), commlink (DR 6), helmet (+1), fake SIN and licenses (rating 5), flash-pak, micro-transceiver, smoke grenade, Vulcan Liegelord rigger command console",
        "Weapons: none listed - relies on the squad's vehicle-mounted Stoner-Ares M202 machine gun (vehicle stats not modeled here)",
      ].join("\n"),
      notes: `${CM_NOTE} Arrives with an armed Toyota Gopher pickup (heavy machine gun mount) and an escort of Horizon Flying Eye drones, plus an on-call Ares Black Sky air-to-ground combat drone - vehicle/drone stat blocks are out of scope for this roster.`,
    },
  },
  {
    id: "npc-fs-humanis-general",
    name: "Humanis Paramilitary General",
    group: "Humanis Paramilitary",
    summary: "Commands an entire local regiment - the military equivalent of a face, gathering resources and coordinating with sympathizers.",
    book: FIRING_SQUAD,
    data: {
      description: "Humanis Paramilitary, Professional Rating 5. Observes and commands from a distance; breaks away from direct combat if possible.",
      physicalMonitor: 11,
      stunMonitor: 11,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 4,
      initiative: initiative(11, 4),
      combat: [
        "B5(+2) A4 R4(6) S5 W5 L3 I5 C4 ESS2",
        "AC: A1, I4",
        "Skills: Athletics 4, Close Combat 4 (Unarmed +2), Con 6, Firearms 4 (Pistols +2), Influence 5 (Intimidation +2), Perception 4, Stealth 4",
        "Augmentations: Bone lacing (aluminum), cyberears (rating 3, audio enhancement, damper, select sound filter rating 4, spatial recognizer), cybereyes (rating 4, full suite), commlink (headware, DR 6), datajack, wired reflexes 2",
        "Gear: Armor vest (+3), fake SIN and licenses (rating 6), flash-pak, laser microphone (rating 1, audio enhancement), micro-flare launcher and flares, smoke grenades, micro-transceiver",
        "Weapons: Ares Light Fire 75 [Light Pistol, DV 3P, SA, 10/7/6/—/—, w/ internal smartgun system, silencer]; Unarmed attack [DV 4P, 13/—/—/—/—]; Survival knife [Blade, DV 4P, 8/2*/—/—/—; *max range 20m if thrown]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },

  // --- Gangs: Ancients (book pp. 144-145) ---
  {
    id: "npc-fs-ancients-racer",
    name: "Ancients Racer",
    group: "Ancients",
    summary: "Hyperbike masters who'll issue a street race challenge at the slightest provocation - elf, with racial adjustments applied.",
    book: FIRING_SQUAD,
    data: {
      description: "Ancients, Professional Rating 3 (Elf). Often carries a rider into gang scuffles.",
      physicalMonitor: 14,
      stunMonitor: 14,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 4,
      initiative: initiative(9, 1),
      combat: [
        "B2 A3 R5(9) S2 W3 L2 I5 C3 ESS2.8 (Elf)",
        "AC: A1, I2",
        "Skills: Athletics 1, Close Combat 2, Cracking 4, Electronics 3, Engineering 4, Firearms 3, Influence 1, Outdoors 2, Perception 3, Piloting 4 (Ground Craft +3), Stealth 2",
        "Augmentations: Control rig 2, reaction enhancers 4",
        "Gear: CycleWear Armor (+3), helmet (+1, w/ camera, thermographic), commlink (DR 3), Suzuki Mirage",
        "Weapons: Ingram Smartgun XI [Submachine Gun, DV 4P, SA/BF, 13/11/8/—/—, w/ smartgun, explosive ammo]; Sword [Blade, DV 3P, 9/—/—/—/—]",
      ].join("\n"),
      notes: `${CM_NOTE} Arrives on a Suzuki Mirage (vehicle stats not modeled here).`,
    },
  },
  {
    id: "npc-fs-ancients-gunner",
    name: "Ancients Gunner",
    group: "Ancients",
    summary: "SMG/machine-pistol shooters who also carry a sword for a more personal message - elf, with racial adjustments applied.",
    book: FIRING_SQUAD,
    data: {
      description: "Ancients, Professional Rating 3 (Elf).",
      physicalMonitor: 10,
      stunMonitor: 10,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 4,
      initiative: initiative(10, 1),
      combat: [
        "B2 A4(5) R5(6) S3(5) W3 L2 I4 C2 ESS4.3 (Elf)",
        "AC: A1, I2",
        "Skills: Athletics 1, Close Combat 3 (Blades +2), Cracking 4, Electronics 3, Engineering 3, Firearms 4, Influence 1, Outdoors 2, Perception 3, Piloting 2, Stealth 2",
        "Augmentations: Muscle replacement 2, reaction enhancers 1",
        "Gear: CycleWear Armor (+3), helmet (+1, w/ smartlink), commlink (DR 4), jazz (4 doses)",
        "Weapons: Ingram Smartgun XI [Submachine Gun, DV 4P, SA/BF, 13/11/8/—/—, w/ smartgun, explosive ammo]; Nodachi [Blades, DV 5P, 10/—/—/—/—]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },
  {
    id: "npc-fs-ancients-mage",
    name: "Ancients Mage",
    group: "Ancients",
    summary: "Rides on the back of the bike casting anything except protection for it - electricity, ice, and fire are top picks for flair.",
    book: FIRING_SQUAD,
    data: {
      description: "Ancients, Professional Rating 4 (Elf).",
      physicalMonitor: 10,
      stunMonitor: 10,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 7,
      initiative: initiative(9, 1),
      combat: [
        "B1 A3 R5 S1 W4 L4 I4 C7 M5 ESS6 (Elf)",
        "AC: A1, I2",
        "Skills: Astral 4, Athletics 2, Biotech 2, Close Combat 2, Conjuring 4, Electronics 1, Enchanting 2, Firearms 3, Influence 2 (Intimidation +2), Perception 4, Piloting 1, Sorcery 5, Stealth 3",
        "Spells: Armor, Blast, Clairvoyance, Clout, Combat Sense, Confusion, Detect Enemies, Detect Magic, Heal, Increase Reflexes, Levitate, Light, Physical Barrier, Resist Pain, Stabilize, Stunbolt",
        "Gear: Commlink (DR 4), full body armor w/ helmet (+7, w/ smartlink, thermographic), reagents (20), spirit of air (Force 4, 3 services), spirit of kin (Force 4, 2 services)",
        "Weapons: HK P50 [Light Pistol, DV 3P, SA, 10/8/5/—/—, w/ laser sight, smartgun, explosive ammo]; Stun baton [Club, DV 5S(e), 6/—/—/—/—]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },

  // --- Gangs: Halloweeners (book pp. 145-146) ---
  {
    id: "npc-fs-halloweeners-neophyte",
    name: "Halloweeners Neophyte",
    group: "Halloweeners",
    summary: "The newest, most dangerous (least skilled) Halloweeners - desperate to burn the world to fit the gang's image.",
    book: FIRING_SQUAD,
    data: {
      description: "Halloweeners, Professional Rating 2.",
      physicalMonitor: 9,
      stunMonitor: 9,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 3,
      initiative: initiative(6, 1),
      combat: [
        "B2 A4 R3 S2 W1 L1 I3 C2 ESS6",
        "AC: A1, I2",
        "Skills: Athletics 1 (Throwing +2), Close Combat 1 (Clubs +2), Exotic Weapons (Flamethrower) 4, Influence 2 (Intimidation +2), Perception 3",
        "Gear: Synthleather (+2, w/ fire resistance 2), commlink (DR 2), ballistic mask (+1)",
        "Weapons: Homemade Flamer [Exotic, DV 3P*, SS, 10(c), 5/8/—/—/—, applies Burning 3 status]; Flaming baseball bat [Club, DV 3S, 8/—/—/—/—, applies Burning 2 status]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },
  {
    id: "npc-fs-halloweeners-molotov",
    name: "Halloweeners Molotov",
    group: "Halloweeners",
    summary: "Survivors who've learned to harness fire safely - see fire as something to be respected, not abused.",
    book: FIRING_SQUAD,
    data: {
      description: "Halloweeners, Professional Rating 3.",
      physicalMonitor: 10,
      stunMonitor: 10,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 5,
      initiative: initiative(7, 1),
      combat: [
        "B3 A4 R4 S2 W3 L2 I3 C3 ESS6",
        "AC: A1, I2",
        "Skills: Athletics 2 (Throwing +3), Close Combat 2 (Clubs +2), Exotic Weapons (Flamethrower) 5, Influence 2 (Intimidation +3), Perception 3",
        "Gear: Armor jacket (+4, w/ fire resistance 3), commlink (DR 4), ballistic mask (+1), jazz (2 doses)",
        "Weapons: Shiawase Blazer [Exotic, DV 6P, SS, 5(m), 14/12/10/—/—, applies Burning 4 status]; Flaming baseball bat [Club, DV 3S, 8/—/—/—/—, applies Burning 2 status]; 2x Molotov Cocktail [DV 4P, 3P, 2P; Blast 15m, Burning DV]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },
  {
    id: "npc-fs-halloweeners-master-of-flame",
    name: "Halloweeners Master of the Flame",
    group: "Halloweeners",
    summary: "One rung below the gang's leaders - burns with the precision of a surgeon, not indiscriminately, but still bat-drek crazy.",
    book: FIRING_SQUAD,
    data: {
      description: "Halloweeners, Professional Rating 4.",
      physicalMonitor: 10,
      stunMonitor: 10,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 6,
      initiative: initiative(10, 2),
      combat: [
        "B5 A5(7) R5(6) S3 W5 L3 I4 C6 ESS4",
        "AC: A1, I3",
        "Skills: Athletics 4 (Throwing +3), Close Combat 4 (Clubs +3), Exotic Weapons (Flamethrower) 8, Influence 4 (Intimidation +3), Perception 5",
        "Augmentations: Dermal plating 2, muscle toner 2, wired reflexes 1",
        "Gear: Full body armor w/ helmet (+7, w/ fire resistance 6), commlink (DR 4), jazz (2 doses)",
        "Weapons: rEVOlution Hell Turtle [Exotic, DV 3-5P*, SS, 15(c), 6/10/—/—/—, w/ wild die; *uses 1 ammo per DV, applies Burning 3 status]; Flaming staff [Club, DV 4S, 8/—/—/—/—, applies Burning 3 status]; 4x Incendiary Grenade [DV 6P, 4P, 2P; Blast 15m, applies Burning 4 status]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },

  // --- Gangs: Cutters (book pp. 146-147) ---
  {
    id: "npc-fs-cutters-corner-dealer",
    name: "Cutters Corner Dealer",
    group: "Cutters",
    summary: "The lowest rung of a businesslike gang - chic dress, slick moves, and a habit of overstepping the wrong people.",
    book: FIRING_SQUAD,
    data: {
      description: "Cutters, Professional Rating 2.",
      physicalMonitor: 9,
      stunMonitor: 9,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 2,
      initiative: initiative(6, 1),
      combat: [
        "B1 A3 R2 S1 W2 L2 I4 C3 ESS6.0",
        "AC: A1, I2",
        "Skills: Athletics 1, Close Combat 1 (Blades +2), Electronics 2, Firearms 2 (Pistols +2), Influence 1 (Negotiation +2), Perception 2 (Urban +2), Piloting 1 (Ground Craft +2), Stealth 2 (Sneaking +2)",
        "Gear: Actioneer business clothing (+2), commlink (DR 3), Horizon Flying Eye",
        "Weapons: Beretta 101T [Light Pistol, DV 2P, SA, 9/8/6/—/—, 21(c)]; Combat knife [Blade, DV 4P, 8/2*/—/—/—; *max range 15m]",
      ].join("\n"),
      notes: `${CM_NOTE} Has a Horizon Flying Eye drone on call (drone stats not modeled here).`,
    },
  },
  {
    id: "npc-fs-cutters-negotiator",
    name: "Cutters Negotiator",
    group: "Cutters",
    summary: "Calm under pressure and good at reading a mark - travels with an entourage of up-and-comers and thugs.",
    book: FIRING_SQUAD,
    data: {
      description: "Cutters, Professional Rating 3.",
      physicalMonitor: 11,
      stunMonitor: 11,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 5,
      initiative: initiative(8, 2),
      combat: [
        "B3 A4(5) R3(4) S1 W4 L3 I4 C5(+1) ESS4.4",
        "AC: A1, I3",
        "Skills: Athletics 3, Close Combat 2 (Unarmed +2, Blades +3), Con 4 (Impersonation +3), Electronics 2, Firearms 4 (Pistols +2), Influence 5 (Negotiation +3), Perception 4 (Urban +2), Piloting 2 (Ground Craft +2), Stealth 3 (Sneaking +2)",
        "Augmentations: Cybereyes (rating 2, w/ camera, image link, low-light vision, smartlink), muscle toner 1, tailored pheromones 1, wired reflexes 1",
        "Gear: Ace of Coins armor (+3), commlink (DR 5), SecureTech Invisi-shield armor (+2)",
        "Weapons: Nemesis Arms Praetorian II [Heavy Pistol, DV 3P, SA, 9/8/8/—/—, 12(c), w/ smartgun]; Combat knife [Blade, DV 4P, 8/2*/—/—/—; *max range 15m]; Shock gloves [Close Combat, DV 4S(e), 5/—/—/—/—]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },
  {
    id: "npc-fs-cutters-legbreaker",
    name: "Cutters Legbreaker",
    group: "Cutters",
    summary: "Every gang needs thugs - treats causing injury as a business transaction, breaking only what matches the debt owed.",
    book: FIRING_SQUAD,
    data: {
      description: "Cutters, Professional Rating 3.",
      physicalMonitor: 11,
      stunMonitor: 11,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 9,
      initiative: initiative(12, 2),
      combat: [
        "B6 A4(7) R5(8) S6(9) W2 L2 I4 C2 ESS1.2",
        "AC: A1, I3",
        "Skills: Athletics 5, Close Combat 6 (Blades +2, Unarmed +3), Electronics 2, Firearms 4 (Pistols +3), Influence 4 (Negotiation +2, Intimidation +3), Perception 4 (Urban +2), Piloting 1 (Ground Craft +2), Stealth 2 (Sneaking +2)",
        "Augmentations: Cybereyes (rating 2, w/ camera, image link, low-light vision, smartlink), dermal plating 3, muscle replacement 3, reaction enhancers 2, wired reflexes 1",
        "Gear: Ace of Cups armor (+4), commlink (DR 4), SecureTech Invisi-shield armor (+2)",
        "Weapons: Ares Predator VI [Heavy Pistol, DV 3P, SA/BF, 10/10/8/—/—, 15(c), w/ smartgun, gel and explosive ammo]; Combat knife [Blade, DV 4P, 8/2*/—/—/—; *max range 15m]; Stun baton [Club, DV 5S(e), Attack Ratings 6/—/—/—/—]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },

  // --- Gangs: First Nations (book pp. 147-149) ---
  {
    id: "npc-fs-firstnations-warrior",
    name: "First Nations Warrior",
    group: "First Nations",
    summary: "Traditional style meets modern tech - chem sniffers in the feathers, MADscanners in the bone armor.",
    book: FIRING_SQUAD,
    data: {
      description: "First Nations, Professional Rating 3.",
      physicalMonitor: 11,
      stunMonitor: 11,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 6,
      initiative: initiative(10, 2),
      combat: [
        "B5 A4(5) R5(6) S4(5) W3 L2 I4 C3 ESS3.8",
        "AC: A1, I3",
        "Skills: Athletics 3, Close Combat 2 (Unarmed +2), Firearms 3, Influence 1 (Intimidation +2), Outdoors 2 (Survival +2), Perception 3, Piloting 2 (Ground Craft +2), Stealth 4 (Sneaking +2)",
        "Augmentations: Cybereyes (rating 2, w/ camera, image link, low-light vision, smartlink), dermal plating 1, muscle replacement 1, wired reflexes 1",
        "Gear: Armor jacket (+4), commlink (DR 3), ballistic mask (+1)",
        "Weapons: Browning Ultra Power [Heavy Pistol, DV 3P, SA, 10/9/6/—/—, w/ laser sight, smartgun]; Ranger Arms AA-16 [Shotgun, DV 6P, SA/BF/FA, 6/12/7/—/—, 12(c), w/ laser sight]; Urban Tribe Tomahawk Mk II [Blades, DV 2P, 10/9*/—/—/—; *max range 20m]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },
  {
    id: "npc-fs-firstnations-shaman",
    name: "First Nations Shaman",
    group: "First Nations",
    summary: "Disenfranchised NAN youth with the Talent, drawn to the gang like moths to a flame - some turn toxic from lack of discipline.",
    book: FIRING_SQUAD,
    data: {
      description: "First Nations, Professional Rating 4.",
      physicalMonitor: 11,
      stunMonitor: 11,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 4,
      initiative: initiative(9, 1),
      combat: [
        "B1 A3 R4 S1 W5 L4 I5 C5 M5 ESS6",
        "AC: A1, I2",
        "Skills: Astral 3 (Astral Signatures +2, Emotional States +3), Athletics 2, Biotech 2 (First Aid +2), Close Combat 3 (Blades +2, Clubs +3), Conjuring 4 (Summoning +3), Electronics 1 (Computer +2), Enchanting 2 (Alchemy +2, Artificing +3), Firearms 2 (Shotguns +2, Pistols +3), Influence 3 (Intimidation +2, Negotiation +3), Outdoors 3 (Woods +2, Survival +3), Perception 4 (Visual +2), Piloting 1 (Ground Craft +2), Sorcery 5 (Ritual Spellcasting +2, Spellcasting +3), Stealth 2 (Sneaking +2)",
        "Spells and Rituals: Animate Metal, Animate Plastic, Animate Stone, Animate Wood, Antidote, Armor, Blast, Clout, Confusion, Detect Magic, Heal, Light, Mana Barrier, Physical Barrier, Renascence, Shape Metal, Shape Plastic, Shape Stone, Shape Wood, Stunbolt, Ward",
        "Gear: Armor vest (+3), commlink (DR 3), helmet (+1, w/ low-light vision, image link)",
        "Weapons: Colt America L36 [Light Pistol, DV 2P, SA, 9/9/6/—/—, w/ laser sight]; Mossberg CMDT [Shotgun, DV 4P, SA/BF, 5/12/7/—/—, w/ laser sight]; Combat knife [Blade, DV 3P, 8/2*/—/—/—; *max range 15m]; Staff [Clubs, DV 4S, 8/—/—/—/—]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },
  {
    id: "npc-fs-firstnations-traditionalist",
    name: "First Nations Traditionalist",
    group: "First Nations",
    summary: "Avoids modern tools, relying on skill and training a hacker can't strip away - honored, distrusted leadership.",
    book: FIRING_SQUAD,
    data: {
      description: "First Nations, Professional Rating 5.",
      physicalMonitor: 11,
      stunMonitor: 11,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 4,
      initiative: initiative(11, 1),
      combat: [
        "B5 A5 R5 S5 W5 L4 I5 C4 ESS6",
        "AC: A1, I2",
        "Skills: Athletics 3 (Throwing +2, Archery +3), Close Combat 4 (Unarmed +2, Blades +3), Influence 3 (Intimidation +3), Outdoors 5 (Tracking +2, Survival +3), Perception 5 (Visual +2, Aural +3), Piloting 2 (Ground Craft +3), Stealth 5 (Sneaking +3)",
        "Gear: Armor vest (+3), commlink (DR 2), helmet (+1, w/ low-light vision, image link)",
        "Weapons: rEVOlution Iron Hawk bow (rating 6) [Bow, DV 4P, SS, 5/9/2/1/—, w/ wild die]; Urban Tribe Tomahawk Mk II [Blades, DV 2P, 10/9*/—/—/—; *max range 20m]; 2x throwing knives [Thrown, DV 3P, 10/9/3/—/—]; Knucks [Unarmed, DV 3P, 6/—/—/—/—]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },

  // --- Gangs: Smokers Club (book pp. 149-150) ---
  {
    id: "npc-fs-smokers-young-buck",
    name: "Smokers Club Young Buck",
    group: "Smokers Club",
    summary: "Skilled talent waiting for the big break, making up for inexperience with ingenuity and tenacity.",
    book: FIRING_SQUAD,
    data: {
      description: "Smokers Club, Professional Rating 3. Assassins-for-hire, individual in style and method.",
      physicalMonitor: 10,
      stunMonitor: 10,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 4,
      initiative: initiative(10, 3),
      combat: [
        "B3 A4(6) R4(6) S3(6) W4 L3 I4 C4 ESS1.4",
        "AC: A1, I4",
        "Skills: Athletics 3, Close Combat 4, Con 3, Electronics 2 (Computer +2), Engineering 1 (Demolitions +2), Firearms 4 (Pistols +2, Rifles +3), Influence 3, Outdoors 3, Perception 4, Piloting 2 (Ground Craft +3), Stealth 3 (Sneaking +2)",
        "Augmentations: Cybereyes (rating 3, w/ camera, flare compensation, image link, low-light, smartlink, vision enhancement), cyberears (rating 3, w/ audio enhancement, damper, select sound filter 2, sound link, spatial recognizer), muscle replacement 2, reaction enhancers 2, wired reflexes 2",
        "Gear: Armor jacket (+4), commlink (DR 5)",
        "Weapons: Browning Ultra Power [Heavy Pistol, DV 3P, SA, 10/9/6/—/—, w/ laser sight, smartgun]; Shiawase Arms Model 73 [Assault Rifle, DV 4P, SA/BF/FA, 4/11/10/8/3, w/ smartgun, silencer]; Shiawase Arms Tactical Model 69 [Sniper Rifle, DV 6P, SA, 2/9/13/17/13, 10(m), w/ silencer, smartgun, handload ammo]; Iron Fang combat knife [Blade, DV 3P, 9/1*/—/—/—; *max range 15m, wild die, smart materials]; Stun baton [Club, DV 5S(e), 6/—/—/—/—]; Garrote [Unarmed, DV 3P, 8/—/—/—/—; wild die]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },
  {
    id: "npc-fs-smokers-social-adept-assassin",
    name: "Smokers Club Social Adept Assassin",
    group: "Smokers Club",
    summary: "Blends and portrays whoever they need to be - the delivery gal, the old lady, the up-and-coming exec you don't see coming.",
    book: FIRING_SQUAD,
    data: {
      description: "Smokers Club, Professional Rating 4.",
      physicalMonitor: 11,
      stunMonitor: 11,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 10,
      initiative: initiative(12, 3),
      combat: [
        "B3 A3 R4(6) S3 W5 L4 I6 C7 M10 ESS6",
        "AC: A1, I4",
        "Skills: Astral 4, Athletics 4, Biotech 2 (First Aid +2), Close Combat 4 (Blades +2), Con 6(9) (Acting +2, Impersonation +3), Electronics 3 (Computer +2), Firearms 3 (Pistols +2), Influence 8(11) (Etiquette +2, Negotiation +3), Perception 4 (Visual +2), Piloting 2 (Ground Craft +2), Stealth 2",
        "Adept Powers: Astral Perception, Combat Sense 1, Danger Sense, Enhanced Perception, Improved Ability (Con) 3, Improved Ability (Influence) 3, Improved Reflexes 2, Improved Sense (Hearing), Kinesics, Mystic Armor 6, Rapid Healing 3, Spell Resistance 1, Vocal Control",
        "Initiate Grade: 4. Metamagics: Flexible signature, masking, power point (2)",
        "Gear: Armor jacket (+4), commlink (DR 6)",
        "Weapons: rEVOlution Arms Ocelot [Machine Pistol, DV 2P, SA/BF/FA, 9/10/5/—/—, w/ barrel-mounted silencer, laser sight, wild die]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },
  {
    id: "npc-fs-smokers-adept-infiltrator",
    name: "Smokers Club Adept Infiltrator",
    group: "Smokers Club",
    summary: "Air ducts, elevator shafts, and warehouse rafters - stealth and cunning bring death from unexpected angles.",
    book: FIRING_SQUAD,
    data: {
      description: "Smokers Club, Professional Rating 7.",
      physicalMonitor: 10,
      stunMonitor: 10,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 4,
      initiative: initiative(15, 5),
      combat: [
        "B4 A6(8) R6(10) S4 W4 L4 I5 C5 M9 ESS6",
        "AC: A1, I6",
        "Skills: Athletics 8 (Gymnastics +2, Climbing +3), Biotech 3 (First Aid +2), Close Combat 8 (Unarmed +3), Con 3 (Disguise +2), Electronics 3 (Computer +2), Firearms 6 (SMG +2, Pistol +3), Influence 3 (Negotiation +2), Outdoors 6 (Tracking +2), Perception 7(10) (Visual +2, Aural +3), Piloting 1 (Ground Craft +2), Stealth 6(9) (Palming +2, Sneaking +3)",
        "Adept Powers: Combat Sense 1, Enhanced Perception, Improved Ability (Perception) 3, Improved Ability (Stealth) 3, Improved Agility 2, Improved Reflexes 4, Improved Sense (Hearing, Sight), Spell Resistance 1, Traceless Walk, Wall Running",
        "Initiate Grade: 4. Metamagics: Masking, Power Point (3)",
        "Gear: Armor jacket (+4), commlink (DR 6)",
        "Weapons: Ares Light Fire 75 [Light Pistol, DV 3P, SA, Attack Ratings 10/7/6/—/—, w/ barrel-mounted silencer, laser sight, explosive ammo]; FN P93 Praetor [Submachine Gun, DV 4P, SA/BF, 8/11/6/—/—, w/ flashlight, laser sight, rigid stock, silencer]; Shock gloves [Close Combat, DV 4S(e), 5/—/—/—/—]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },
  {
    id: "npc-fs-smokers-long-gun",
    name: "Smokers Club Long Gun",
    group: "Smokers Club",
    summary: "The classic sniper, perched far enough off that neither target nor witnesses connect them to the shot.",
    book: FIRING_SQUAD,
    data: {
      description: "Smokers Club, Professional Rating 5.",
      physicalMonitor: 11,
      stunMonitor: 11,
      physicalDamage: 0,
      stunDamage: 0,
      armor: 3,
      initiative: initiative(13, 3),
      combat: [
        "B2 A6(10) R3(7) S2 W5 L5 I6 C3 ESS2.04",
        "AC: A1, I4",
        "Skills: Athletics 3, Close Combat 3, Con 5 (Disguise +2), Electronics 3, Engineering 2, Firearms 7 (Rifles +3), Influence 1, Outdoors 3, Perception 4, Piloting 3, Stealth 5",
        "Augmentations: Cybereyes (alphaware, rating 4, w/ full suite), cyberears (alphaware, rating 3, w/ full suite), muscle toner 4, reaction enhancers 2, wired reflexes 2",
        "Gear: Armor vest (+3), commlink (DR 5)",
        "Weapons: Ares Viper Slivergun [Heavy Pistol, DV 4P(f), SA/BF, 12/8/6/—/—, w/ built-in silencer, smartgun]; PSG Enforcer II [Sniper Rifle, DV 5P, SS, 2/9/13/13/7, 12x2(c), w/ silencer, smartgun, handload ammo]; Shock gloves [Close Combat, DV 4S(e), 5/—/—/—/—]",
      ].join("\n"),
      notes: CM_NOTE,
    },
  },
];
