// Gear catalog. Chunked to align with the Sixth World Companion's PACKs
// taxonomy (Weapons PACKs, Armor PACKs, Sensor/Identity/Surveillance PACKs,
// Augmentation PACKs, Vehicle/Drone/Console/Autosoft/Upgrade PACKs, Complete
// Character PACKs) rather than one big "all gear" pass - see README.
//
// This file covers the first chunk: Weapons. Transcribed from the SR6 core
// rulebook's Weapons chapter, book pp. 247-264 (PDF pp. 248-265 in
// SR6_Core_RuleBook_noimg.pdf - the book's own table of contents only lists
// "Hold-outs" onward starting at p. 251, but Melee, Thrown/Projectile, and
// Taser weapons are unlisted-but-present chapter content on pp. 247-251
// immediately before it, so they're included here too - a "Weapons" chunk
// without melee weapons would be an odd gap). Stat-block numbers (Damage
// Value, Attack Ratings, Availability, Cost, etc.) are transcribed as
// printed since they're game rules, not protected expression; flavor text
// is paraphrased in our own words, same convention as qualities.ts.
//
// Known gaps in this pass, flagged rather than guessed at:
// - Ammo "type" modifiers (APDS, Explosive, Flechette, Gel, Stick-n-Shock,
//   Caseless; book p. 262) price as a multiplier against a weapon class's
//   base per-10-rounds cost, not a flat nuyen amount - that doesn't fit this
//   catalog's flat-cost-per-entry model. Only the base "Regular" ammo cost
//   per weapon class is catalogued below; the multiplier table needs a
//   follow-up (a `costMultiplier` entry type) before it can be purchasable.
// - The "Missile Variant" upgrade (book p. 264, converts a rocket to a
//   guided missile for +Sensor Rating x 500¥) is similarly a modifier on
//   another item's cost, not a standalone purchase - noted in its own entry
//   below as informational only, not wired into automatic cost calculation.
// - Weapon accessories, ammo, and explosives are catalogued here (they're
//   printed in the same chapter/tables as the weapons themselves), but
//   armor accessories, general gear, and everything from p. 265 on is out
//   of scope for this chunk - see README's Armor/General Gear chunks.

export interface GearCatalogEntry {
  id: string;
  name: string;
  /** Broad grouping key, e.g. "weapon" - opaque string, not a fixed union, since new categories arrive with each future chunk. */
  category: string;
  /** Narrower grouping for the picker UI, e.g. "Light Pistols". */
  subcategory?: string;
  /** Nuyen cost; per-level if `levels` is set. */
  cost: number;
  /** Availability code, e.g. "4", "8R", "12F". */
  availability: string;
  summary: string;
  /** For rated items (e.g. Explosive Packages); cost is PER LEVEL, same convention as QualityCatalogEntry.levels. */
  levels?: { min: number; max: number };
  /** Free-form display-only stat fields (Damage, Modes, Attack Ratings, Ammo, Mount, Blast...); not strongly typed since each weapon subtype uses a different subset. */
  stats?: Record<string, string>;
}

export const weaponGear: GearCatalogEntry[] = [
  // --- Melee: Blades (book p. 249) ---
  {
    id: "combat-axe",
    name: "Combat Axe",
    category: "weapon",
    subcategory: "Blades",
    cost: 500,
    availability: "4",
    summary: "A single- or double-bladed axe with a spring-loaded thrusting point.",
    stats: { damage: "5P", attackRatings: "9/—/—/—/—" },
  },
  {
    id: "combat-survival-knife",
    name: "Combat/Survival Knife",
    category: "weapon",
    subcategory: "Blades",
    cost: 220,
    availability: "2",
    summary: "A chisel-pointed fighting knife; the survival variant adds a GPS monitor, multitool, and light in the handle for the same combat stats.",
    stats: { damage: "3P", attackRatings: "8/2*/—/—/—" },
  },
  {
    id: "forearm-snap-blades",
    name: "Forearm Snap Blades",
    category: "weapon",
    subcategory: "Blades",
    cost: 185,
    availability: "3",
    summary: "Three razor blades that extend and retract from the forearm on command or wireless signal.",
    stats: { damage: "3P", attackRatings: "6/—/—/—/—" },
  },
  {
    id: "knife",
    name: "Knife",
    category: "weapon",
    subcategory: "Blades",
    cost: 20,
    availability: "1",
    summary: "A catchall for any small fighting blade; stats cover all styles.",
    stats: { damage: "2P", attackRatings: "6/1*/—/—/—" },
  },
  {
    id: "katana",
    name: "Katana",
    category: "weapon",
    subcategory: "Blades",
    cost: 350,
    availability: "3",
    summary: "The iconic two-handed sword of the samurai.",
    stats: { damage: "4P", attackRatings: "10/—/—/—/—" },
  },
  {
    id: "polearm",
    name: "Polearm",
    category: "weapon",
    subcategory: "Blades",
    cost: 210,
    availability: "2",
    summary: "A long-hafted blade good for keeping distance; nearly impossible to conceal.",
    stats: { damage: "4P", attackRatings: "8/—/—/—/—" },
  },
  {
    id: "sword",
    name: "Sword",
    category: "weapon",
    subcategory: "Blades",
    cost: 320,
    availability: "3",
    summary: "A heavy one-handed blade in a variety of styles.",
    stats: { damage: "3P", attackRatings: "9/—/—/—/—" },
  },

  // --- Melee: Clubs (book p. 249) ---
  {
    id: "club",
    name: "Club",
    category: "weapon",
    subcategory: "Clubs",
    cost: 65,
    availability: "1",
    summary: "Covers any blunt improvised or purpose-made bludgeon (bat, crowbar, tire iron...).",
    stats: { damage: "3S", attackRatings: "6/—/—/—/—" },
  },
  {
    id: "extendable-baton",
    name: "Extendable Baton",
    category: "weapon",
    subcategory: "Clubs",
    cost: 52,
    availability: "2",
    summary: "A telescoping club, easier to conceal retracted.",
    stats: { damage: "2S", attackRatings: "5/—/—/—/—" },
  },
  {
    id: "sap",
    name: "Sap",
    category: "weapon",
    subcategory: "Clubs",
    cost: 75,
    availability: "1",
    summary: "A short, flexible, easily concealed blackjack.",
    stats: { damage: "2S", attackRatings: "6/—/—/—/—" },
  },
  {
    id: "staff",
    name: "Staff",
    category: "weapon",
    subcategory: "Clubs",
    cost: 150,
    availability: "1",
    summary: "A long fighting staff in composite, hardwood, or steel.",
    stats: { damage: "4S", attackRatings: "8/—/—/—/—" },
  },
  {
    id: "stun-baton",
    name: "Stun Baton",
    category: "weapon",
    subcategory: "Clubs",
    cost: 600,
    availability: "2",
    summary: "An electrical riot-control prod with ten charges.",
    stats: { damage: "5S(e)", attackRatings: "6/—/—/—/—" },
  },
  {
    id: "telescoping-staff",
    name: "Telescoping Staff",
    category: "weapon",
    subcategory: "Clubs",
    cost: 250,
    availability: "2",
    summary: "A staff that telescopes down to the size of a stun baton or sword.",
    stats: { damage: "4S", attackRatings: "8/—/—/—/—" },
  },

  // --- Melee: Other (Unarmed/Exotic) (book p. 250) ---
  {
    id: "bike-chain",
    name: "Bike Chain",
    category: "weapon",
    subcategory: "Melee (Other)",
    cost: 15,
    availability: "1",
    summary: "A heavy metal chain favored by go-gangs. Uses the Unarmed skill.",
    stats: { damage: "2S", attackRatings: "5/—/—/—/—" },
  },
  {
    id: "bullwhip",
    name: "Bullwhip",
    category: "weapon",
    subcategory: "Melee (Other)",
    cost: 255,
    availability: "4",
    summary: "A leather cord weapon; brutal on bare flesh, mainly a tripping hazard against armor. Uses Reaction instead of Strength for the Attack Rating. Uses the Exotic Melee skill.",
    stats: { damage: "1P", attackRatings: "6/—/—/—/—" },
  },
  {
    id: "knucks",
    name: "Knucks",
    category: "weapon",
    subcategory: "Melee (Other)",
    cost: 100,
    availability: "1",
    summary: "Brass knuckles or similar hand-augmenting weapons. Uses the Unarmed skill.",
    stats: { damage: "3P", attackRatings: "6/—/—/—/—" },
  },
  {
    id: "shock-gloves",
    name: "Shock Gloves",
    category: "weapon",
    subcategory: "Melee (Other)",
    cost: 790,
    availability: "4",
    summary: "Insulated gloves that discharge current on contact, inflicting the Zapped status. Good for ten charges. Uses the Unarmed skill.",
    stats: { damage: "4S(e)", attackRatings: "5/—/—/—/—" },
  },
  {
    id: "monofilament-whip",
    name: "Monofilament Whip",
    category: "weapon",
    subcategory: "Melee (Other)",
    cost: 1300,
    availability: "6(I)",
    summary: "Two meters of monofilament line that cuts through armor, flesh, and bone; a bad twist can injure the wielder. Uses the Exotic Melee skill.",
    stats: { damage: "6P", attackRatings: "14/—/—/—/—" },
  },

  // --- Thrown/Projectile (book pp. 250-251) ---
  {
    id: "bow",
    name: "Bow",
    category: "weapon",
    subcategory: "Bows & Crossbows",
    cost: 110,
    availability: "1(L)",
    summary:
      "A longbow or compound bow; hacker-proof but rare on the streets. Rating (1-14, minimum Strength to use) sets Damage, Attack Ratings, and cost: DV = ceil(Rating/2)P, Attack Ratings Close/Near/Medium = Rating/2, Rating, Rating/4, Cost = 100 + Rating x 10¥. Uses the Archery skill.",
    stats: { note: "Cost/DV/AR scale with chosen Rating - see summary; the value here is the Rating 1 baseline." },
  },
  {
    id: "arrow",
    name: "Arrow",
    category: "weapon",
    subcategory: "Ammunition",
    cost: 2,
    availability: "1",
    summary: "Must equal or exceed the bow's Rating. Cost = Rating x 2¥, Availability = Rating/3.",
  },
  {
    id: "injection-arrow",
    name: "Injection Arrow",
    category: "weapon",
    subcategory: "Ammunition",
    cost: 160,
    availability: "4",
    summary: "Delivers a drug/toxin payload on a hit. Base Rating 8. Cost = Rating x 20¥.",
  },
  {
    id: "crossbow-light",
    name: "Crossbow, Light",
    category: "weapon",
    subcategory: "Bows & Crossbows",
    cost: 150,
    availability: "3",
    summary: "A single-handed autoloading crossbow.",
    stats: { damage: "2P", attackRatings: "6/8/2/—/—" },
  },
  {
    id: "crossbow-standard",
    name: "Crossbow, Standard",
    category: "weapon",
    subcategory: "Bows & Crossbows",
    cost: 290,
    availability: "3(L)",
    summary: "A two-handed autoloading crossbow.",
    stats: { damage: "3P", attackRatings: "2/10/4/2/—" },
  },
  {
    id: "crossbow-heavy",
    name: "Crossbow, Heavy",
    category: "weapon",
    subcategory: "Bows & Crossbows",
    cost: 425,
    availability: "4(L)",
    summary: "A two-handed heavy autoloading crossbow.",
    stats: { damage: "4P", attackRatings: "2/8/6/4/—" },
  },
  {
    id: "bolt",
    name: "Bolt",
    category: "weapon",
    subcategory: "Ammunition",
    cost: 5,
    availability: "2",
    summary: "Standard crossbow ammunition.",
  },
  {
    id: "injection-bolt",
    name: "Injection Bolt",
    category: "weapon",
    subcategory: "Ammunition",
    cost: 50,
    availability: "4",
    summary: "Delivers a drug/toxin payload on a hit.",
  },
  {
    id: "throwing-knives",
    name: "Throwing Knives",
    category: "weapon",
    subcategory: "Thrown",
    cost: 155,
    availability: "2",
    summary: "Balanced knives for throwing; up to Agility/2 can be readied at once. Uses the Athletics skill.",
    stats: { damage: "2P", attackRatings: "10/9/3/—/—" },
  },
  {
    id: "throwing-stars",
    name: "Throwing Stars",
    category: "weapon",
    subcategory: "Thrown",
    cost: 160,
    availability: "2",
    summary: "Shuriken-style throwing weapons. Uses the Athletics skill.",
    stats: { damage: "2P", attackRatings: "9/11/5/—/—" },
  },

  // --- Tasers (book p. 251) ---
  {
    id: "defiance-super-shock",
    name: "Defiance Super Shock",
    category: "weapon",
    subcategory: "Tasers",
    cost: 340,
    availability: "1",
    summary: "A heavy-duty wired taser firing up to four darts on twenty-meter wires.",
    stats: { damage: "6S(e)", modes: "SS", attackRatings: "10/6*/—/—/—", ammo: "4(m)" },
  },
  {
    id: "yamaha-pulsar-i",
    name: "Yamaha Pulsar I",
    category: "weapon",
    subcategory: "Tasers",
    cost: 325,
    availability: "1",
    summary: "A wireless-capacitor taser with increased range but less punch than wired models; no melee contacts.",
    stats: { damage: "4S(e)", modes: "SS", attackRatings: "9/9†/—/—/—", ammo: "4(m)" },
  },
  {
    id: "yamaha-pulsar-ii",
    name: "Yamaha Pulsar II",
    category: "weapon",
    subcategory: "Tasers",
    cost: 350,
    availability: "1",
    summary: "As the Pulsar I, but adds melee contacts on the grip usable as a Close Combat Club attack.",
    stats: { damage: "4S(e)", modes: "SS", attackRatings: "9/9†/—/—/—", ammo: "4(m)" },
  },

  // --- Hold-outs (book p. 252) ---
  {
    id: "fichetti-tiffani-needler",
    name: "Fichetti Tiffani Needler",
    category: "weapon",
    subcategory: "Hold-outs",
    cost: 435,
    availability: "2",
    summary: "A stylish, wirelessly recolorable designer handgun chambered for caseless flechette rounds only. Cannot take accessories.",
    stats: { damage: "3P", modes: "SS", attackRatings: "10/6/2/—/—", ammo: "4(c)" },
  },
  {
    id: "streetline-special",
    name: "Streetline Special",
    category: "weapon",
    subcategory: "Hold-outs",
    cost: 200,
    availability: "2",
    summary: "A cheap 3D-nanoprinted pistol, harder to detect with MAD scanners. Cannot take accessories.",
    stats: { damage: "2P", modes: "SS", attackRatings: "8/8/—/—/—", ammo: "6(c)" },
  },
  {
    id: "walther-palm-pistol",
    name: "Walther Palm Pistol",
    category: "weapon",
    subcategory: "Hold-outs",
    cost: 345,
    availability: "2",
    summary: "A double-barreled over-under derringer capable of Burst Fire by firing both barrels at once. Cannot take accessories.",
    stats: { damage: "2P", modes: "SS/BF", attackRatings: "12/7/—/—/—", ammo: "6(b)" },
  },

  // --- Light Pistols (book p. 253) ---
  {
    id: "ares-light-fire-70",
    name: "Ares Light Fire 70",
    category: "weapon",
    subcategory: "Light Pistols",
    cost: 350,
    availability: "3(L)",
    summary: "A special-ops sidearm with an integrated barrel-mounted silencer and laser sight.",
    stats: { damage: "2P", modes: "SA", attackRatings: "10/7/6/—/—", ammo: "16(c)" },
  },
  {
    id: "ares-light-fire-75",
    name: "Ares Light Fire 75",
    category: "weapon",
    subcategory: "Light Pistols",
    cost: 400,
    availability: "3(L)",
    summary: "As the Light Fire 70, but not commonly available through legal channels; adds preloaded smartlink hardware and software.",
    stats: { damage: "2P", modes: "SA", attackRatings: "10/7/6/—/—", ammo: "16(c)" },
  },
  {
    id: "beretta-101t",
    name: "Beretta 101T",
    category: "weapon",
    subcategory: "Light Pistols",
    cost: 260,
    availability: "2(L)",
    summary: "A common light-pistol sidearm for security forces worldwide.",
    stats: { damage: "2P", modes: "SA", attackRatings: "9/8/6/—/—", ammo: "21(c)" },
  },
  {
    id: "beretta-201t",
    name: "Beretta 201T",
    category: "weapon",
    subcategory: "Light Pistols",
    cost: 460,
    availability: "3(L)",
    summary: "Shares the 101T's frame but adds automatic fire capability and a detachable shoulder stock.",
    stats: { damage: "2P", modes: "SA/FA", attackRatings: "9/8/6/—/—", ammo: "21(c)" },
  },
  {
    id: "colt-america-l36",
    name: "Colt America L36",
    category: "weapon",
    subcategory: "Light Pistols",
    cost: 230,
    availability: "2(L)",
    summary: "Cheap, easily concealed, and abundant on the streets; features an ownership-swap feature abused by cops and crooks alike.",
    stats: { damage: "2P", modes: "SA", attackRatings: "8/8/6/—/—", ammo: "11(c)" },
  },
  {
    id: "fichetti-security-600",
    name: "Fichetti Security 600",
    category: "weapon",
    subcategory: "Light Pistols",
    cost: 390,
    availability: "3(L)",
    summary: "A security-forces sidearm with a thirty-round magazine, detachable folding stock, and laser sight.",
    stats: { damage: "2P", modes: "SA", attackRatings: "10/9/6/—/—", ammo: "30(c)" },
  },
  {
    id: "ruger-redhawk",
    name: "Ruger Redhawk",
    category: "weapon",
    subcategory: "Light Pistols",
    cost: 250,
    availability: "2(L)",
    summary: "A revolver with a single/double firing selector: Semi-Auto on double action, Burst Fire on single.",
    stats: { damage: "3P", modes: "SA/BF", attackRatings: "7/10/7/—/—", ammo: "8(cy)" },
  },

  // --- Machine Pistols (book pp. 253-254) ---
  {
    id: "ares-crusader-ii",
    name: "Ares Crusader II",
    category: "weapon",
    subcategory: "Machine Pistols",
    cost: 520,
    availability: "4(L)",
    summary: "A high-capacity machine pistol with gas-vent recoil compensation and preloaded smartgun system.",
    stats: { damage: "2P", modes: "SA/BF", attackRatings: "9/9/7/—/—", ammo: "40(c)" },
  },
  {
    id: "ceska-black-scorpion",
    name: "Ceska Black Scorpion",
    category: "weapon",
    subcategory: "Machine Pistols",
    cost: 510,
    availability: "3(L)",
    summary: "A small, lethal machine pistol with an integral folding stock.",
    stats: { damage: "2P", modes: "SA/BF", attackRatings: "10/9/8/—/—", ammo: "35(c)" },
  },
  {
    id: "steyr-tmp",
    name: "Steyr TMP",
    category: "weapon",
    subcategory: "Machine Pistols",
    cost: 690,
    availability: "3(L)",
    summary: "A lightweight polymer-frame full-auto machine pistol with a standard top-mounted laser sight.",
    stats: { damage: "2P", modes: "SA/FA", attackRatings: "8/8/6/—/—", ammo: "30(c)" },
  },

  // --- Heavy Pistols (book pp. 254-255) ---
  {
    id: "ares-predator-vi",
    name: "Ares Predator VI",
    category: "weapon",
    subcategory: "Heavy Pistols",
    cost: 750,
    availability: "2(L)",
    summary: "A standard smartgun-equipped heavy pistol with Burst Fire and a variable-ammunition magazine system.",
    stats: { damage: "3P", modes: "SA/BF", attackRatings: "10/10/8/—/—", ammo: "15(c)" },
  },
  {
    id: "ares-viper-slivergun",
    name: "Ares Viper Slivergun",
    category: "weapon",
    subcategory: "Heavy Pistols",
    cost: 610,
    availability: "4(L)",
    summary: "Fires metal slivers (bought/treated as flechette ammo, not interchangeable with other flechette weapons); has an integrated silencer.",
    stats: { damage: "4P(fl)", modes: "SA/BF", attackRatings: "12/8/6/—/—", ammo: "30(c)" },
  },
  {
    id: "browning-ultra-power",
    name: "Browning Ultra Power",
    category: "weapon",
    subcategory: "Heavy Pistols",
    cost: 315,
    availability: "2(L)",
    summary: "Cheaper than the Predator VI, with a built-in top-mounted laser sight.",
    stats: { damage: "3P", modes: "SA", attackRatings: "10/9/6/—/—", ammo: "10(c)" },
  },
  {
    id: "colt-government-2076-manhunter",
    name: "Colt Government 2076/Manhunter",
    category: "weapon",
    subcategory: "Heavy Pistols",
    cost: 275,
    availability: "3(L)",
    summary: "Standard-issue military sidearm with an integral laser sight. The Manhunter variant (integrated smartgun system) costs 500¥.",
    stats: { damage: "3P", modes: "SA", attackRatings: "10/8/6/—/—", ammo: "14(c)" },
  },
  {
    id: "ruger-super-warhawk",
    name: "Ruger Super Warhawk",
    category: "weapon",
    subcategory: "Heavy Pistols",
    cost: 400,
    availability: "3(L)",
    summary: "A big, chromed revolver that makes large holes.",
    stats: { damage: "4P", modes: "SA", attackRatings: "8/11/8/—/—", ammo: "6(cy)" },
  },

  // --- Submachine Guns (book pp. 255-256) ---
  {
    id: "colt-cobra-tz-100",
    name: "Colt Cobra TZ-100",
    category: "weapon",
    subcategory: "Submachine Guns",
    cost: 730,
    availability: "2(L)",
    summary: "The base model of the Cobra TZ line, with an integral folding stock.",
    stats: { damage: "3P", modes: "SA/BF", attackRatings: "9/9/6/—/—", ammo: "32(c)" },
  },
  {
    id: "colt-cobra-tz-110",
    name: "Colt Cobra TZ-110",
    category: "weapon",
    subcategory: "Submachine Guns",
    cost: 785,
    availability: "2(L)",
    summary: "Adds a top-mounted laser sight to the TZ-100.",
    stats: { damage: "3P", modes: "SA/BF", attackRatings: "10/10/7/—/—", ammo: "32(c)" },
  },
  {
    id: "colt-cobra-tz-120",
    name: "Colt Cobra TZ-120",
    category: "weapon",
    subcategory: "Submachine Guns",
    cost: 840,
    availability: "3(L)",
    summary: "Adds a barrel-mounted gas-vent system to the TZ-110.",
    stats: { damage: "3P", modes: "SA/BF", attackRatings: "10/11/8/—/—", ammo: "32(c)" },
  },
  {
    id: "fn-p93-praetor",
    name: "FN P93 Praetor",
    category: "weapon",
    subcategory: "Submachine Guns",
    cost: 925,
    availability: "4(L)",
    summary: "A bullpup-design SMG with an integrated rigid stock, laser sight, and multi-mode flashlight.",
    stats: { damage: "4P", modes: "SA/BF/FA", attackRatings: "9/12/7/—/—", ammo: "50(c)" },
  },
  {
    id: "hk-227",
    name: "HK-227",
    category: "weapon",
    subcategory: "Submachine Guns",
    cost: 825,
    availability: "3(L)",
    summary: "Built on the venerable MP5 frame; a top choice for corporate/military security, with a retractable stock and integral silencer.",
    stats: { damage: "3P", modes: "SA/BF", attackRatings: "10/11/8/—/—", ammo: "28(c)" },
  },
  {
    id: "ingram-smartgun-xi",
    name: "Ingram Smartgun XI",
    category: "weapon",
    subcategory: "Submachine Guns",
    cost: 750,
    availability: "3(L)",
    summary: "A legendary street samurai SMG with a gas-vent system, smartgun system, and integral silencer.",
    stats: { damage: "3P", modes: "SA/BF", attackRatings: "11/9/6/—/—", ammo: "32(c)" },
  },
  {
    id: "sck-model-100",
    name: "SCK Model 100",
    category: "weapon",
    subcategory: "Submachine Guns",
    cost: 725,
    availability: "3(L)",
    summary: "Standard issue across Japanacorp security forces, with an internal smartgun system and folding stock.",
    stats: { damage: "3P", modes: "SA/BF", attackRatings: "10/10/7/—/—", ammo: "30(c)" },
  },
  {
    id: "uzi-v",
    name: "Uzi V",
    category: "weapon",
    subcategory: "Submachine Guns",
    cost: 455,
    availability: "2(L)",
    summary: "Spinrad Global's latest Uzi, with an integral folding stock and top-mounted laser sight.",
    stats: { damage: "3P", modes: "SA/BF/FA", attackRatings: "8/8/7/—/—", ammo: "24(c)" },
  },

  // --- Shotguns (book pp. 256-257) ---
  {
    id: "defiance-t-250",
    name: "Defiance T-250",
    category: "weapon",
    subcategory: "Shotguns",
    cost: 330,
    availability: "2(L)",
    summary: "A gas-operated semi-auto shotgun with a secondary pump action. Short-barreled version: Concealability 3, DV 3P, Attack Ratings 8/8/4/—/—.",
    stats: { damage: "4P", modes: "SS/SA", attackRatings: "7/10/6/—/—", ammo: "5(m)" },
  },
  {
    id: "mossberg-cmdt",
    name: "Mossberg CMDT",
    category: "weapon",
    subcategory: "Shotguns",
    cost: 700,
    availability: "4(L)",
    summary: "An assault shotgun taking ten-round clips or a twenty-four-round drum, with Burst Fire and a top-mounted laser sight.",
    stats: { damage: "4P", modes: "SA/BF", attackRatings: "4/11/7/—/—", ammo: "10(c)" },
  },
  {
    id: "pjss-model-55",
    name: "PJSS Model 55",
    category: "weapon",
    subcategory: "Shotguns",
    cost: 325,
    availability: "5(L)",
    summary: "A rich-hunter's double-barreled shotgun; both barrels can fire at once as a short burst.",
    stats: { damage: "4P", modes: "SA/BF(short)", attackRatings: "3/12/8/—/—", ammo: "2(b)" },
  },
  {
    id: "remington-roomsweeper",
    name: "Remington Roomsweeper",
    category: "weapon",
    subcategory: "Shotguns",
    cost: 325,
    availability: "2(L)",
    summary: "A double-barreled, pistol-gripped pocket shotgun.",
    stats: { damage: "5P", modes: "SA", attackRatings: "9/8/4/—/—", ammo: "8(m)" },
  },

  // --- Rifles (book pp. 257-258) ---
  {
    id: "ak-97",
    name: "AK-97",
    category: "weapon",
    subcategory: "Rifles",
    cost: 2100,
    availability: "2(L)",
    summary: "A rifle that never goes out of style, built for reliability and endurance.",
    stats: { damage: "5P", modes: "SA/BF/FA", attackRatings: "4/11/9/7/1", ammo: "38(c)" },
  },
  {
    id: "ares-alpha",
    name: "Ares Alpha",
    category: "weapon",
    subcategory: "Rifles",
    cost: 3400,
    availability: "5(L)",
    summary: "A worldwide-success assault rifle with an integrated underbarrel grenade launcher (As grenade, SS, AR —/6/8/6/5 hidden inline w/ rifle table but listed separately per rifle - see stats) and smartgun system.",
    stats: { damage: "4P", modes: "SA/BF/FA", attackRatings: "4/10/9/7/2", ammo: "42(c)", grenadeLauncher: "SS, AR 4/10/6/2/—, ammo 6(c)" },
  },
  {
    id: "colt-m23",
    name: "Colt M23",
    category: "weapon",
    subcategory: "Rifles",
    cost: 2100,
    availability: "2(L)",
    summary: "Cheap, mass-produced, and infinitely adaptable; can mount up to three underbarrel accessories.",
    stats: { damage: "4P", modes: "SA/BF/FA", attackRatings: "5/8/8/8/1", ammo: "40(c)" },
  },
  {
    id: "fn-har",
    name: "FN-HAR",
    category: "weapon",
    subcategory: "Rifles",
    cost: 2100,
    availability: "3(L)",
    summary: "A private-security and corporate high-threat-response rifle with a laser sight and gas-vent system.",
    stats: { damage: "5P", modes: "SA/BF/FA", attackRatings: "3/11/10/6/1", ammo: "35(c)" },
  },
  {
    id: "yamaha-raiden",
    name: "Yamaha Raiden",
    category: "weapon",
    subcategory: "Rifles",
    cost: 3200,
    availability: "5(L)",
    summary: "Yamaha's answer to the Alpha; electronic firing, an integral silencer and smartgun system, plus an underbarrel shotgun/grenade launcher.",
    stats: {
      damage: "4P",
      modes: "SA/BF/FA",
      attackRatings: "4/11/10/7/2",
      ammo: "60(c)",
      grenadeLauncher: "SS, AR 4/11/7/1/—, ammo 4(c)",
      shotgunMode: "SS/SA, DV 4P, AR 7/9/8/—/—, ammo 2(b)",
    },
  },
  {
    id: "ares-desert-strike",
    name: "Ares Desert Strike",
    category: "weapon",
    subcategory: "Rifles",
    cost: 11000,
    availability: "4(I)",
    summary: "Built for the Desert Wars, with a rigid shock-pad stock and detachable imaging scope.",
    stats: { damage: "5P", modes: "SA", attackRatings: "3/10/10/10/10", ammo: "14(c)" },
  },
  {
    id: "cavalier-arms-crockett-ebr",
    name: "Cavalier Arms Crockett EBR",
    category: "weapon",
    subcategory: "Rifles",
    cost: 9050,
    availability: "5(I)",
    summary: "A sniper rifle capable of Burst Fire, with a rigid shock-pad stock and detachable imaging scope.",
    stats: { damage: "5P", modes: "SA/BF", attackRatings: "3/8/11/8/8", ammo: "20(c)" },
  },
  {
    id: "ranger-arms-sm-5",
    name: "Ranger Arms SM-5",
    category: "weapon",
    subcategory: "Rifles",
    cost: 13200,
    availability: "5(I)",
    summary: "A silenced sniper rifle with an imaging scope and smartgun system; folds to fit a briefcase (Firearms + Logic (6) Extended test to assemble/disassemble).",
    stats: { damage: "5P", modes: "SA", attackRatings: "3/6/9/11/12", ammo: "15(c)" },
  },
  {
    id: "remington-900",
    name: "Remington 900",
    category: "weapon",
    subcategory: "Rifles",
    cost: 12000,
    availability: "3(L)",
    summary: "A high-powered bolt-action hunting rifle with a classic wooden body and top-mounted imaging scope; cannot mount underbarrel accessories.",
    stats: { damage: "5P", modes: "SS", attackRatings: "2/7/10/12/11", ammo: "5(m)" },
  },
  {
    id: "ruger-101",
    name: "Ruger 101",
    category: "weapon",
    subcategory: "Rifles",
    cost: 11100,
    availability: "2(L)",
    summary: "A gas-operated hunting rifle with a built-in imaging scope and shock-pad stock.",
    stats: { damage: "5P", modes: "SA", attackRatings: "2/6/10/12/11", ammo: "8(m)" },
  },
  {
    id: "barret-model-122",
    name: "Barret Model 122",
    category: "weapon",
    subcategory: "Rifles",
    cost: 15200,
    availability: "6(I)",
    summary: "An anti-materiel rifle for tearing through vehicles and machines, with a silencer, smartgun system, and folding bipod.",
    stats: { damage: "6P", modes: "SA", attackRatings: "1/8/11/16/14", ammo: "10(c)" },
  },

  // --- Machine Guns/Assault Cannons (book p. 258) ---
  {
    id: "ingram-valiant",
    name: "Ingram Valiant",
    category: "weapon",
    subcategory: "Machine Guns",
    cost: 4175,
    availability: "4(L)",
    summary: "A light machine gun favored by mercenary units, with a shock-pad stock, laser sight, and gas-vent system.",
    stats: { damage: "4P", modes: "SA/BF/FA", attackRatings: "2/11/12/7/3", ammo: "50(c) or 100(belt)" },
  },
  {
    id: "stoner-ares-m202",
    name: "Stoner-Ares M202",
    category: "weapon",
    subcategory: "Machine Guns",
    cost: 6900,
    availability: "4(L)",
    summary: "A medium machine gun with tremendous punch; requires Strength 3+.",
    stats: { damage: "5P", modes: "SA/BF/FA", attackRatings: "1/10/11/7/6", ammo: "50(c) or 100(belt)" },
  },
  {
    id: "rpk-hmg",
    name: "RPK HMG",
    category: "weapon",
    subcategory: "Machine Guns",
    cost: 8000,
    availability: "5(L)",
    summary: "A heavy machine gun used by militaries across Eastern Europe and Asia; requires Strength 5+, comes standard with a detachable tripod.",
    stats: { damage: "6P", modes: "SA/BF/FA", attackRatings: "1/10/12/8/7", ammo: "50(c) or 100(belt)" },
  },
  {
    id: "panther-xxl",
    name: "Panther XXL",
    category: "weapon",
    subcategory: "Machine Guns",
    cost: 10000,
    availability: "6(I)",
    summary: "An assault cannon; bulky, ugly, deadly, with a built-in smartgun system.",
    stats: { damage: "7P", modes: "SA", attackRatings: "1/9/12/8/6", ammo: "15(c)" },
  },

  // --- Special Weapons (Exotic) (book pp. 258-259) ---
  {
    id: "ares-super-squirt",
    name: "Ares S-III Super Squirt",
    category: "weapon",
    subcategory: "Special Weapons",
    cost: 560,
    availability: "3(L)",
    summary: "A glorified paintball marker firing nonlethal DMSO gel packs that deliver a Contact-vector toxin payload on a hit. Uses the Exotic Ranged Weapon skill.",
    stats: { damage: "Special", modes: "SS", attackRatings: "8/12/9/—/—", ammo: "20(c)" },
  },
  {
    id: "parashield-dart-pistol",
    name: "Parashield DART Pistol",
    category: "weapon",
    subcategory: "Special Weapons",
    cost: 510,
    availability: "2",
    summary: "The industry-standard dart pistol for delivering drug/toxin payloads. Uses the Exotic Ranged Weapon skill.",
    stats: { damage: "1P + special", modes: "SS", attackRatings: "9/10/8/—/—", ammo: "5(c)" },
  },
  {
    id: "parashield-dart-rifle",
    name: "Parashield DART Rifle",
    category: "weapon",
    subcategory: "Special Weapons",
    cost: 710,
    availability: "3",
    summary: "The rifle-length DART series with a top-mounted imaging scope. Uses the Exotic Ranged Weapon skill.",
    stats: { damage: "1P + special", modes: "SS", attackRatings: "5/8/11/3/—", ammo: "6(m)" },
  },

  // --- Launchers (book p. 259) ---
  {
    id: "ares-antioch-ii",
    name: "Ares Antioch II",
    category: "weapon",
    subcategory: "Launchers",
    cost: 5900,
    availability: "3(I)",
    summary: "A grenade launcher with an integral smartgun system and wireless-activation trigger setting. Uses the Exotic Weapons skill.",
    stats: { ammoType: "Grenade", modes: "SS", attackRatings: "—/6/8/6/5", ammo: "8(m)" },
  },
  {
    id: "armtech-mgl-6",
    name: "ArmTech MGL-6",
    category: "weapon",
    subcategory: "Launchers",
    cost: 1800,
    availability: "4(I)",
    summary: "A bullpup-pistol-style semi-auto grenade launcher. Uses the Exotic Weapons skill.",
    stats: { ammoType: "Grenade", modes: "SA", attackRatings: "—/8/8/3/—", ammo: "6(c)" },
  },
  {
    id: "armtech-mgl-12",
    name: "ArmTech MGL-12",
    category: "weapon",
    subcategory: "Launchers",
    cost: 5000,
    availability: "4(I)",
    summary: "A rifle-style semi-auto grenade launcher. Uses the Exotic Weapons skill.",
    stats: { ammoType: "Grenade", modes: "SA", attackRatings: "—/8/9/6/2", ammo: "12(c)" },
  },
  {
    id: "aztechnology-striker",
    name: "Aztechnology Striker",
    category: "weapon",
    subcategory: "Launchers",
    cost: 7000,
    availability: "5(I)",
    summary: "A disposable-warhead, reusable-tube missile launcher. Uses the Exotic Weapons skill.",
    stats: { ammoType: "Missile", modes: "SS", attackRatings: "—/4/10/9/6", ammo: "1(ml)" },
  },
  {
    id: "onotari-interceptor",
    name: "Onotari Interceptor",
    category: "weapon",
    subcategory: "Launchers",
    cost: 9000,
    availability: "5(I)",
    summary: "A military dual-barrel missile launcher that can load two missiles of different types at once. Uses the Exotic Weapons skill.",
    stats: { ammoType: "Missile", modes: "SS", attackRatings: "—/5/9/10/8", ammo: "2(ml)" },
  },

  // --- Weapon Accessories (book pp. 259-261) ---
  {
    id: "accessory-airburst-link",
    name: "Airburst Link",
    category: "weapon",
    subcategory: "Weapon Accessories",
    cost: 600,
    availability: "3",
    summary: "A smartgun accessory for grenade/rocket launchers that reduces scatter distance via rangefinder.",
    stats: { mount: "—" },
  },
  {
    id: "accessory-bipod",
    name: "Bipod",
    category: "weapon",
    subcategory: "Weapon Accessories",
    cost: 200,
    availability: "1",
    summary: "A two-legged brace for firing prone or sitting; +2 Attack Rating when deployed.",
    stats: { mount: "Underbarrel" },
  },
  {
    id: "accessory-concealable-holster",
    name: "Concealable Holster",
    category: "weapon",
    subcategory: "Weapon Accessories",
    cost: 150,
    availability: "1",
    summary: "A holster worn anywhere on the body; increases Concealability threshold by 1. Fits pistols and tasers only.",
    stats: { mount: "—" },
  },
  {
    id: "accessory-gas-vent-system",
    name: "Gas-Vent System",
    category: "weapon",
    subcategory: "Weapon Accessories",
    cost: 500,
    availability: "3",
    summary: "Removes the Attack Rating penalty for Semi-Auto fire and reduces it to 2 for Burst Fire. Cannot be removed once installed.",
    stats: { mount: "Barrel" },
  },
  {
    id: "accessory-gyro-mount",
    name: "Gyro Mount",
    category: "weapon",
    subcategory: "Weapon Accessories",
    cost: 1400,
    availability: "3",
    summary: "A worn, gyro-stabilized harness for a rifle or machine gun; negates Semi-Auto/Burst Fire penalties, +3 Attack Rating for Full-Auto.",
    stats: { mount: "Underbarrel" },
  },
  {
    id: "accessory-hidden-arm-slide",
    name: "Hidden Arm Slide",
    category: "weapon",
    subcategory: "Weapon Accessories",
    cost: 350,
    availability: "2",
    summary: "A forearm slide for a Hold-out, Light Pistol, or Taser; grants a bonus Edge on first use and increases Concealability by 1.",
    stats: { mount: "—" },
  },
  {
    id: "accessory-imaging-scope",
    name: "Imaging Scope",
    category: "weapon",
    subcategory: "Weapon Accessories",
    cost: 350,
    availability: "1",
    summary: "A top-mounted scope with micro camera and magnification; target can't gain Edge from higher Defense Rating while used.",
    stats: { mount: "Top" },
  },
  {
    id: "accessory-laser-sight",
    name: "Laser Sight",
    category: "weapon",
    subcategory: "Weapon Accessories",
    cost: 125,
    availability: "1",
    summary: "Projects a targeting dot; +1 Attack Rating, not cumulative with smartlink.",
    stats: { mount: "Top or Underbarrel" },
  },
  {
    id: "accessory-periscope",
    name: "Periscope",
    category: "weapon",
    subcategory: "Weapon Accessories",
    cost: 70,
    availability: "2",
    summary: "Lets the user target around corners, reducing the Cover IV penalty when taking cover.",
    stats: { mount: "Top" },
  },
  {
    id: "accessory-quick-draw-holster",
    name: "Quick-Draw Holster",
    category: "weapon",
    subcategory: "Weapon Accessories",
    cost: 175,
    availability: "2",
    summary: "Grants a bonus Minor Action when the Quick-Draw Action is taken.",
    stats: { mount: "—" },
  },
  {
    id: "accessory-shock-pad",
    name: "Shock Pad",
    category: "weapon",
    subcategory: "Weapon Accessories",
    cost: 50,
    availability: "2",
    summary: "A shock-absorbing stock pad for a rifle, shotgun, or heavy weapon; decreases Semi-Auto/Burst Fire penalties by 1.",
    stats: { mount: "—" },
  },
  {
    id: "accessory-silencer",
    name: "Silencer/Suppressor",
    category: "weapon",
    subcategory: "Weapon Accessories",
    cost: 500,
    availability: "4",
    summary: "Reduces sound/flash of firing; not compatible with revolvers or shotguns.",
    stats: { mount: "Barrel" },
  },
  {
    id: "accessory-smart-firing-platform",
    name: "Smart Firing Platform",
    category: "weapon",
    subcategory: "Weapon Accessories",
    cost: 2500,
    availability: "5",
    summary: "A robotic tripod that mounts and fires one smartgun-equipped weapon via its own onboard pilot.",
    stats: { mount: "Underbarrel" },
  },
  {
    id: "accessory-smartgun-internal",
    name: "Smartgun System, Internal",
    category: "weapon",
    subcategory: "Weapon Accessories",
    cost: 500,
    availability: "1(L)",
    summary: "Built into the weapon at manufacture; +2 Attack Rating with a smartlink across all ranges.",
    stats: { mount: "—" },
  },
  {
    id: "accessory-smartgun-external",
    name: "Smartgun System, External",
    category: "weapon",
    subcategory: "Weapon Accessories",
    cost: 200,
    availability: "2(L)",
    summary: "Attached after the fact via an Engineering + Logic (4, 1 hour) Extended Test; +2 Attack Rating with a smartlink across all ranges.",
    stats: { mount: "Top or Underbarrel" },
  },
  {
    id: "accessory-spare-clip",
    name: "Spare Clip",
    category: "weapon",
    subcategory: "Weapon Accessories",
    cost: 5,
    availability: "2",
    summary: "An unloaded standard magazine for a specific weapon.",
    stats: { mount: "—" },
  },
  {
    id: "accessory-speed-loader",
    name: "Speed Loader",
    category: "weapon",
    subcategory: "Weapon Accessories",
    cost: 25,
    availability: "1",
    summary: "A weapon-specific reload ring for a revolver's cylinder.",
    stats: { mount: "—" },
  },
  {
    id: "accessory-tripod",
    name: "Tripod",
    category: "weapon",
    subcategory: "Weapon Accessories",
    cost: 500,
    availability: "2",
    summary: "A stable firing base; negates Semi-Auto/Burst Fire penalties, +3 Attack Rating for Full-Auto when deployed.",
    stats: { mount: "Underbarrel" },
  },

  // --- Ammo: base cost per weapon class, Regular rounds (book p. 262) ---
  {
    id: "ammo-holdout-light-machine-pistol",
    name: "Ammo: Hold-out/Light Pistol/Machine Pistol (10 rounds)",
    category: "weapon",
    subcategory: "Ammunition",
    cost: 5,
    availability: "1",
    summary: "Regular ammunition, ten rounds. Special ammo types (APDS, Explosive, Flechette, Gel, Stick-n-Shock, Caseless) price as a multiplier on this base cost - not yet catalogued, see file header.",
  },
  {
    id: "ammo-heavy-pistol-smg",
    name: "Ammo: Heavy Pistol/SMG (10 rounds)",
    category: "weapon",
    subcategory: "Ammunition",
    cost: 10,
    availability: "1",
    summary: "Regular ammunition, ten rounds.",
  },
  {
    id: "ammo-rifle",
    name: "Ammo: Rifle (10 rounds)",
    category: "weapon",
    subcategory: "Ammunition",
    cost: 20,
    availability: "2(L)",
    summary: "Regular ammunition, ten rounds.",
  },
  {
    id: "ammo-taser",
    name: "Ammo: Taser Dart (10)",
    category: "weapon",
    subcategory: "Ammunition",
    cost: 10,
    availability: "1",
    summary: "Replacement darts, ten count.",
  },
  {
    id: "ammo-injection-dart",
    name: "Ammo: Injection Dart (10)",
    category: "weapon",
    subcategory: "Ammunition",
    cost: 5,
    availability: "2",
    summary: "Ten dart bodies; cost is 5¥ plus the toxin/drug payload's own cost (not included here).",
  },
  {
    id: "ammo-assault-cannon",
    name: "Ammo: Assault Cannon (10 rounds)",
    category: "weapon",
    subcategory: "Ammunition",
    cost: 50,
    availability: "4(I)",
    summary: "Regular ammunition, ten rounds; assault cannons can't be loaded with other ammo types.",
  },
  {
    id: "ammo-machine-gun",
    name: "Ammo: Machine Gun (10 rounds)",
    category: "weapon",
    subcategory: "Ammunition",
    cost: 15,
    availability: "2(L)",
    summary: "Regular ammunition, ten rounds.",
  },
  {
    id: "ammo-shotgun",
    name: "Ammo: Shotgun (10 rounds)",
    category: "weapon",
    subcategory: "Ammunition",
    cost: 15,
    availability: "2(L)",
    summary: "Regular slug rounds, ten rounds.",
  },
  {
    id: "ammo-dmso",
    name: "Ammo: DMSO Gel Packs (10)",
    category: "weapon",
    subcategory: "Ammunition",
    cost: 10,
    availability: "1",
    summary: "Nonlethal gel-pack ammunition for the Ares Super Squirt.",
  },

  // --- Explosives: Grenades (book p. 263) ---
  {
    id: "grenade-stun",
    name: "Stun Grenade",
    category: "weapon",
    subcategory: "Explosives",
    cost: 100,
    availability: "4(L)",
    summary: "A flash-bang; inflicts Blinded I, Deafened I, and Dazed on top of Stun damage in its blast.",
    stats: { damageGroundZero: "10S", damageClose: "8S", damageNear: "6S", blast: "15m" },
  },
  {
    id: "grenade-fragmentation",
    name: "Fragmentation Grenade",
    category: "weapon",
    subcategory: "Explosives",
    cost: 150,
    availability: "4(I)",
    summary: "The classic shrapnel grenade.",
    stats: { damageGroundZero: "16P", damageClose: "12P", damageNear: "8P", blast: "20m" },
  },
  {
    id: "grenade-high-explosive",
    name: "High Explosive Grenade",
    category: "weapon",
    subcategory: "Explosives",
    cost: 150,
    availability: "4(I)",
    summary: "Delivers a powerful blast over a smaller area than fragmentation.",
    stats: { damageGroundZero: "16P", damageClose: "10P", damageNear: "4P", blast: "15m" },
  },
  {
    id: "grenade-gas",
    name: "Gas Grenade",
    category: "weapon",
    subcategory: "Explosives",
    cost: 50,
    availability: "4(I)",
    summary: "Delivers any chosen chemical/toxin payload as a gas cloud lasting ~10 combat rounds. Cost is 50¥ plus 20 doses of the chosen chemical.",
  },
  {
    id: "grenade-smoke",
    name: "Smoke/Thermal Smoke Grenade",
    category: "weapon",
    subcategory: "Explosives",
    cost: 50,
    availability: "4(I)",
    summary: "Releases an obscuring smoke cloud (Blinded I outside it, Blinded II within) lasting ~10 combat rounds.",
  },
  {
    id: "grenade-flash-pak",
    name: "Flash-Pak",
    category: "weapon",
    subcategory: "Explosives",
    cost: 125,
    availability: "4(L)",
    summary: "A strobing device inflicting the Blinded status via vision; ten charges, one per combat round.",
    stats: { damageGroundZero: "Blinded III", damageClose: "Blinded II", damageNear: "Blinded I", blast: "10m" },
  },

  // --- Explosives: Rockets and Missiles (book p. 264) ---
  {
    id: "rocket-anti-vehicle",
    name: "Anti-Vehicle Rocket",
    category: "weapon",
    subcategory: "Explosives",
    cost: 2800,
    availability: "5(I)",
    summary: "A shaped-charge warhead for burning/punching through vehicles or barriers; +2 Attack Rating against vehicles.",
    stats: { damageGroundZero: "12P", damageClose: "8P", damageNear: "4P", blast: "10m" },
  },
  {
    id: "rocket-fragmentation",
    name: "Fragmentation Rocket",
    category: "weapon",
    subcategory: "Explosives",
    cost: 2000,
    availability: "5(I)",
    summary: "Very effective against unprotected people; weak against barriers, structures, and vehicles.",
    stats: { damageGroundZero: "16P", damageClose: "12P", damageNear: "8P", blast: "30m" },
  },
  {
    id: "rocket-high-explosive",
    name: "High Explosive Rocket",
    category: "weapon",
    subcategory: "Explosives",
    cost: 2100,
    availability: "5(I)",
    summary: "Heavy damage over a small area; a scaled-up version of an HE grenade's blast pattern.",
    stats: { damageGroundZero: "16P", damageClose: "10P", damageNear: "4P", blast: "20m" },
  },
  {
    id: "rocket-gas",
    name: "Gas Rocket",
    category: "weapon",
    subcategory: "Explosives",
    cost: 750,
    availability: "4(I)",
    summary: "Delivers a gas payload over a wide area. Cost is 750¥ plus 100 doses of the chosen chemical.",
  },
  {
    id: "rocket-smoke",
    name: "Smoke/Thermal Smoke Rocket",
    category: "weapon",
    subcategory: "Explosives",
    cost: 1200,
    availability: "4(I)",
    summary: "As the smoke grenade, but delivered by rocket for wider coverage.",
  },
  {
    id: "missile-variant-guidance",
    name: "Missile Variant (Guidance Upgrade)",
    category: "weapon",
    subcategory: "Explosives",
    cost: 500,
    availability: "1",
    summary:
      "Converts any rocket above into a guided missile: as the base rocket, +2 Attack Rating, cost is the base rocket's cost plus Sensor Rating x 500¥, Availability is the base rocket's +1(I). Informational only - the listed cost/availability here are the per-Sensor-Rating-point surcharge, not a standalone item; not automatically added to a base rocket's price.",
  },

  // --- Explosives: Conventional Explosives (book p. 264) ---
  {
    id: "explosive-package-1-3",
    name: "Explosive Package (Rating 1-3)",
    category: "weapon",
    subcategory: "Explosives",
    cost: 10,
    availability: "1(I)",
    summary: "Plastic or foam explosive compound, priced per point of Rating.",
    levels: { min: 1, max: 3 },
  },
  {
    id: "explosive-package-4-6",
    name: "Explosive Package (Rating 4-6)",
    category: "weapon",
    subcategory: "Explosives",
    cost: 50,
    availability: "2(I)",
    summary: "Plastic or foam explosive compound, priced per point of Rating.",
    levels: { min: 4, max: 6 },
  },
  {
    id: "explosive-package-7-9",
    name: "Explosive Package (Rating 7-9)",
    category: "weapon",
    subcategory: "Explosives",
    cost: 100,
    availability: "3(I)",
    summary: "Plastic or foam explosive compound, priced per point of Rating.",
    levels: { min: 7, max: 9 },
  },
  {
    id: "explosive-package-10-12",
    name: "Explosive Package (Rating 10-12)",
    category: "weapon",
    subcategory: "Explosives",
    cost: 250,
    availability: "4(I)",
    summary: "Plastic or foam explosive compound, priced per point of Rating.",
    levels: { min: 10, max: 12 },
  },
  {
    id: "explosive-package-13-15",
    name: "Explosive Package (Rating 13-15)",
    category: "weapon",
    subcategory: "Explosives",
    cost: 500,
    availability: "5(I)",
    summary: "Plastic or foam explosive compound, priced per point of Rating.",
    levels: { min: 13, max: 15 },
  },
  {
    id: "explosive-package-16-18",
    name: "Explosive Package (Rating 16-18)",
    category: "weapon",
    subcategory: "Explosives",
    cost: 1000,
    availability: "6(I)",
    summary: "Plastic or foam explosive compound, priced per point of Rating.",
    levels: { min: 16, max: 18 },
  },
  {
    id: "explosive-package-19-20",
    name: "Explosive Package (Rating 19-20)",
    category: "weapon",
    subcategory: "Explosives",
    cost: 5000,
    availability: "7(I)",
    summary: "Plastic or foam explosive compound, priced per point of Rating.",
    levels: { min: 19, max: 20 },
  },
  {
    id: "detonator-cap",
    name: "Detonator Cap",
    category: "weapon",
    subcategory: "Explosives",
    cost: 75,
    availability: "4(I)",
    summary: "Set off by programmable timer or radio signal; inserted into a mass of explosives.",
  },
];
