// Gear catalog, General/survival/security gear chunk - third in the
// Companion PACKs-aligned sequence (see gear.ts's header for the full
// rationale and chunk ordering).
//
// Transcribed from SR6_Core_RuleBook_noimg.pdf, book pp. 278-282 (PDF pp.
// 279-283): Security and Restraints, Breaking and Entering Gear, Industrial
// Chemicals, Survival Gear, Grapple Gun & Rope, and Biotech (including Slap
// Patches and DocWagon Contracts). Corrected end page from the README's
// original "278-281" estimate - Biotech's Slap Patches table actually runs
// to book p. 282, right before Augmentations starts (same kind of
// direct-read correction the Weapons and Armor chunks each needed).
//
// Stat-block numbers are transcribed as printed; flavor text is paraphrased
// in our own words, same convention as qualities.ts/gear.ts/armor.ts.
//
// Known gaps in this pass:
// - The "sensor functions" reference table (book p. 278: Atmosphere sensor,
//   Camera, Cyberware scanner, Directional/Laser/Omni-directional
//   microphone, Geiger counter, MAD scanner, Motion sensor, Olfactory
//   sensor, Ultrasound) lists function/max-range only, no cost or
//   Availability - it's describing sensor *capabilities* for use elsewhere
//   (e.g. a hazmat suit's sensor slot), not a priced catalog. The actual
//   priced Sensors table it cross-references ("Sensors, p. 276") sits
//   outside this chunk's page range and isn't transcribed here - flagged
//   rather than guessed at, same as the ammo-type-multiplier gap in gear.ts.
// - Tranq Patch (book p. 282) prices as (Rating x Rating) x 10¥ - quadratic
//   in Rating, not linear - which doesn't fit this catalog's flat
//   cost-per-level model (`levels` assumes cost x rating, which only
//   matches the printed formula at a single rating). Catalogued at its
//   Rating 1 baseline (10¥) only, with the real formula noted in the
//   summary for manual pricing at higher ratings, rather than mistranscribed
//   into a wrong per-level cost.
// - DocWagon Contracts (book p. 282) price as a recurring subscription
//   (monthly or annual), not a one-time purchase - catalogued at their
//   annual figure with the monthly alternative noted in the summary, same
//   treatment as the Weapons chunk's Colt Government/Manhunter variant
//   pricing.

import type { GearCatalogEntry } from "./gear.js";

export const generalGear: GearCatalogEntry[] = [
  // --- Security and Restraints (book p. 278) ---
  {
    id: "containment-manacles",
    name: "Containment Manacles",
    category: "gear",
    subcategory: "Security and Restraints",
    cost: 250,
    availability: "3",
    summary: "Metal manacles (Structure 10) attached to a prisoner's wrists and ankles, limiting them to a shuffle or three-meter sprint.",
  },
  {
    id: "lock",
    name: "Lock",
    category: "gear",
    subcategory: "Security and Restraints",
    cost: 10,
    availability: "2",
    summary: "A mechanical key lock; bypassed with an Engineering + Agility (Rating) test.",
    levels: { min: 1, max: 6 },
  },
  {
    id: "maglock",
    name: "Maglock",
    category: "gear",
    subcategory: "Security and Restraints",
    cost: 100,
    availability: "3",
    summary: "An electronic lock sealed with electromagnets, with biometric/keycard/passcard/RFID access options.",
    levels: { min: 1, max: 9 },
  },
  {
    id: "keypad",
    name: "Keypad",
    category: "gear",
    subcategory: "Security and Restraints",
    cost: 50,
    availability: "1",
    summary: "A maglock access-control keypad.",
  },
  {
    id: "card-reader",
    name: "Card Reader",
    category: "gear",
    subcategory: "Security and Restraints",
    cost: 50,
    availability: "1",
    summary: "A maglock keycard/passcard reader.",
  },
  {
    id: "biometric-reader-security",
    name: "Biometric Reader",
    category: "gear",
    subcategory: "Security and Restraints",
    cost: 200,
    availability: "2",
    summary: "A fingerprint/retina/voice/tongue-print scanner used to lock down a maglock or electronics.",
  },
  {
    id: "metal-restraints",
    name: "Metal Restraints",
    category: "gear",
    subcategory: "Security and Restraints",
    cost: 20,
    availability: "1",
    summary: "Standard metal restraints (Structure 10) with a mechanical or wireless-controlled lock.",
  },
  {
    id: "plasteel-restraints",
    name: "Plasteel Restraints",
    category: "gear",
    subcategory: "Security and Restraints",
    cost: 50,
    availability: "2",
    summary: "Flash-fused plasteel restraints (Structure 12) that remain in place until the subject is cut free.",
  },
  {
    id: "plastic-straps",
    name: "Plastic Straps (10)",
    category: "gear",
    subcategory: "Security and Restraints",
    cost: 5,
    availability: "1",
    summary: "Disposable plastic restraint straps (Structure 6), lightweight and carried in bundles.",
  },

  // --- Breaking and Entering Gear (book p. 279) ---
  {
    id: "autopicker",
    name: "Autopicker",
    category: "gear",
    subcategory: "Breaking and Entering Gear",
    cost: 500,
    availability: "4(L)",
    summary: "A lockpick gun for quick mechanical lock bypass; +1 dice pool modifier when picking a mechanical lock.",
  },
  {
    id: "cellular-glove-molder",
    name: "Cellular Glove Molder",
    category: "gear",
    subcategory: "Breaking and Entering Gear",
    cost: 500,
    availability: "6(I)",
    summary: "Takes a finger or palm print and molds a wearable \"sleeve\" to fool some biometric locks.",
    levels: { min: 1, max: 4 },
  },
  {
    id: "chisel-wrecking-bar",
    name: "Chisel/Wrecking Bar",
    category: "gear",
    subcategory: "Breaking and Entering Gear",
    cost: 20,
    availability: "1",
    summary: "A sturdy metal slab that doubles your effective Strength when forcing a door, lock, or container.",
  },
  {
    id: "keycard-copier",
    name: "Keycard Copier",
    category: "gear",
    subcategory: "Breaking and Entering Gear",
    cost: 600,
    availability: "4(I)",
    summary: "Copies a keycard in seconds; the duplicate can then be manufactured with an Electronics Kit.",
  },
  {
    id: "lockpick-set",
    name: "Lockpick Set",
    category: "gear",
    subcategory: "Breaking and Entering Gear",
    cost: 250,
    availability: "2",
    summary: "Mechanical burglary tools for picking locks by hand, unless using an autopicker.",
  },
  {
    id: "maglock-passkey",
    name: "Maglock Passkey",
    category: "gear",
    subcategory: "Breaking and Entering Gear",
    cost: 2000,
    availability: "3(I)",
    summary: "A maglock \"skeleton key\" inserted into a cardreader to fool it into believing a legitimate passkey was swiped.",
    levels: { min: 1, max: 4 },
  },
  {
    id: "miniwelder",
    name: "Miniwelder",
    category: "gear",
    subcategory: "Breaking and Entering Gear",
    cost: 250,
    availability: "1",
    summary: "A portable electric-arc device for cutting or welding metal; DV 6 when cutting through barriers. Thirty minutes of operation per fuel canister.",
  },
  {
    id: "miniwelder-fuel-canister",
    name: "Miniwelder Fuel Canister",
    category: "gear",
    subcategory: "Breaking and Entering Gear",
    cost: 80,
    availability: "1",
    summary: "Replacement fuel for a miniwelder.",
  },
  {
    id: "monofilament-chainsaw",
    name: "Monofilament Chainsaw",
    category: "gear",
    subcategory: "Breaking and Entering Gear",
    cost: 500,
    availability: "3",
    summary: "A portable motorized saw with monofilament-wire teeth; DV 8 against barriers. Not usable as a melee weapon.",
  },
  {
    id: "sequencer",
    name: "Sequencer",
    category: "gear",
    subcategory: "Breaking and Entering Gear",
    cost: 250,
    availability: "4(I)",
    summary: "An electronic device required to defeat keypad-maglocks.",
    levels: { min: 1, max: 6 },
  },

  // --- Industrial Chemicals (book p. 279) ---
  {
    id: "glue-solvent",
    name: "Glue Solvent",
    category: "gear",
    subcategory: "Industrial Chemicals",
    cost: 90,
    availability: "1",
    summary: "Dissolves about a square meter of fast-drying aerosol superglue.",
  },
  {
    id: "glue-sprayer",
    name: "Glue Sprayer",
    category: "gear",
    subcategory: "Industrial Chemicals",
    cost: 150,
    availability: "1",
    summary: "Fast-drying aerosol superglue, enough for about a square meter - e.g. gluing a door or window shut. Hardens in 1 combat round.",
  },
  {
    id: "thermite-burning-bar",
    name: "Thermite Burning Bar",
    category: "gear",
    subcategory: "Industrial Chemicals",
    cost: 500,
    availability: "5(L)",
    summary: "A rod of thermite and oxygen for melting holes in iron, steel, or plasteel; inflicts 10P Fire damage. Not usable as a weapon.",
  },

  // --- Survival Gear (book pp. 279-280) ---
  {
    id: "chemsuit",
    name: "Chemsuit",
    category: "gear",
    subcategory: "Survival Gear",
    cost: 150,
    availability: "4",
    summary: "An impermeable coverall worn over clothes or armor providing Chemical Protection; not vacuum-sealed like a full hazmat suit.",
    levels: { min: 1, max: 6 },
  },
  {
    id: "climbing-gear",
    name: "Climbing Gear",
    category: "gear",
    subcategory: "Survival Gear",
    cost: 200,
    availability: "1",
    summary: "A backpack with 100m of rope, harness, gloves, carabiners, crampons, and pitons for assisted climbing.",
  },
  {
    id: "diving-gear",
    name: "Diving Gear",
    category: "gear",
    subcategory: "Survival Gear",
    cost: 2000,
    availability: "3",
    summary: "Wetsuit, facemask/snorkel, regulator, two-hour air tank, and buoyancy vest; protects against Inhalation toxins and provides Rating 2 Cold Resistance.",
  },
  {
    id: "flashlight",
    name: "Flashlight",
    category: "gear",
    subcategory: "Survival Gear",
    cost: 25,
    availability: "1",
    summary: "Long-lasting, super-bright; also available in low-light and infrared versions.",
  },
  {
    id: "gas-mask",
    name: "Gas Mask",
    category: "gear",
    subcategory: "Survival Gear",
    cost: 200,
    availability: "1",
    summary: "An air-supplied re-breather giving immunity to Inhalation-vector toxins; one-hour clean-air supply.",
  },
  {
    id: "gecko-tape-gloves",
    name: "Gecko Tape Gloves",
    category: "gear",
    subcategory: "Survival Gear",
    cost: 250,
    availability: "3",
    summary: "A set of gloves, kneepads, and slip-on soles with dry-adhesive micro-hairs; grants assisted climbing. Useless when wet.",
  },
  {
    id: "hazmat-suit",
    name: "Hazmat Suit",
    category: "gear",
    subcategory: "Survival Gear",
    cost: 3000,
    availability: "3",
    summary: "Full-body suit with a four-hour internal air tank, chemical seal, and a sensor slot; protects against Contact- and Inhalation-vector toxins.",
  },
  {
    id: "light-stick",
    name: "Light Stick",
    category: "gear",
    subcategory: "Survival Gear",
    cost: 25,
    availability: "1",
    summary: "Bend, snap, and shake for three hours of soft chemical illumination over a ten-meter radius.",
  },
  {
    id: "magnesium-torch-flare",
    name: "Magnesium Torch/Flare",
    category: "gear",
    subcategory: "Survival Gear",
    cost: 5,
    availability: "1",
    summary: "Strike for five minutes of bright torchlight out to 20 meters; hitting someone with the end deals 3P Fire damage.",
  },
  {
    id: "microflare-launcher",
    name: "Microflare Launcher",
    category: "gear",
    subcategory: "Survival Gear",
    cost: 175,
    availability: "1",
    summary: "Shoots colored flares 200 meters up, illuminating a city block for a couple minutes. Fired at a person, deals 3P Fire damage (untrained skill check).",
  },
  {
    id: "microflares",
    name: "Microflares",
    category: "gear",
    subcategory: "Survival Gear",
    cost: 25,
    availability: "1",
    summary: "Ammunition for a microflare launcher.",
  },
  {
    id: "rappelling-gloves",
    name: "Rappelling Gloves",
    category: "gear",
    subcategory: "Survival Gear",
    cost: 50,
    availability: "1",
    summary: "Special-fabric gloves giving a bonus Edge to hold your grip on a line; required to use microwire or stealth rope without slicing your hands.",
  },
  {
    id: "respirator",
    name: "Respirator",
    category: "gear",
    subcategory: "Survival Gear",
    cost: 50,
    availability: "1",
    summary: "A filter mask protecting against Inhalation-vector toxins; adds its Rating as a dice pool bonus resisting Inhalation chemicals.",
    levels: { min: 1, max: 6 },
  },
  {
    id: "survival-kit",
    name: "Survival Kit",
    category: "gear",
    subcategory: "Survival Gear",
    cost: 200,
    availability: "2",
    summary: "Knife, lighter, matches, compass, string saw, thermal blanket, seven days of ration bars, water purifier, and fishing line.",
  },

  // --- Grapple Gun & Rope (book p. 281) ---
  {
    id: "grapple-gun",
    name: "Grapple Gun",
    category: "gear",
    subcategory: "Grapple Gun & Rope",
    cost: 500,
    availability: "3",
    summary: "Shoots a grappling hook up to 60-100m depending on line type, with an internal winch. Usable untrained as a weapon (AR 1, DV 1S).",
  },
  {
    id: "microwire",
    name: "Microwire (100m)",
    category: "gear",
    subcategory: "Grapple Gun & Rope",
    cost: 50,
    availability: "2",
    summary: "Nearly-monofilament rope, hard to see (Perception threshold 6); supports up to 100kg. Requires rappelling gloves - slices hands otherwise (5P).",
  },
  {
    id: "myomeric-rope",
    name: "Myomeric Rope (10m)",
    category: "gear",
    subcategory: "Grapple Gun & Rope",
    cost: 200,
    availability: "4",
    summary: "Remote-controllable rope (up to 30m) that can wind around obstacles or tie itself off; moves 2m per combat round.",
  },
  {
    id: "standard-rope",
    name: "Standard Rope (100m)",
    category: "gear",
    subcategory: "Grapple Gun & Rope",
    cost: 50,
    availability: "1",
    summary: "Ordinary climbing/utility rope; supports up to 400kg over 60m.",
  },
  {
    id: "stealth-rope",
    name: "Stealth Rope (100m)",
    category: "gear",
    subcategory: "Grapple Gun & Rope",
    cost: 85,
    availability: "3(I)",
    summary: "Crumbles to dust within seconds when touched with a catalyst stick, leaving almost no trace. Supports up to 400kg over 60m.",
  },
  {
    id: "catalyst-stick",
    name: "Catalyst Stick",
    category: "gear",
    subcategory: "Grapple Gun & Rope",
    cost: 120,
    availability: "3(I)",
    summary: "Reusable device that triggers the chemical reaction to dissolve stealth rope.",
  },

  // --- Biotech (book pp. 281-282) ---
  {
    id: "biomonitor",
    name: "Biomonitor",
    category: "gear",
    subcategory: "Biotech",
    cost: 300,
    availability: "2",
    summary: "Measures heart rate, blood pressure, and body temperature; can analyze blood, sweat, and skin samples. Worn as an armband/wristband or integrated into clothing.",
  },
  {
    id: "docwagon-basic",
    name: "DocWagon Contract: Basic",
    category: "gear",
    subcategory: "Biotech",
    cost: 5000,
    availability: "1",
    summary: "Emergency medical response within 10 minutes, 24/7. Priced at the annual rate; 500¥/month is the alternative billing option.",
  },
  {
    id: "docwagon-gold",
    name: "DocWagon Contract: Gold",
    category: "gear",
    subcategory: "Biotech",
    cost: 25000,
    availability: "1",
    summary: "Adds one free resuscitation/year, 50% off HTR service, 10% off extended care. Priced at the annual rate; 2,500¥/month is the alternative billing option.",
  },
  {
    id: "docwagon-platinum",
    name: "DocWagon Contract: Platinum",
    category: "gear",
    subcategory: "Biotech",
    cost: 50000,
    availability: "1",
    summary: "Four free resuscitations/year, 50% off extended care, free HTR service (death compensation still applies). Priced at the annual rate; 5,000¥/month is the alternative billing option.",
  },
  {
    id: "docwagon-super-platinum",
    name: "DocWagon Contract: Super-Platinum",
    category: "gear",
    subcategory: "Biotech",
    cost: 100000,
    availability: "1",
    summary: "Five free resuscitations/year, no HTR charge, no death compensation charge. Priced at the annual rate; 10,000¥/month is the alternative billing option.",
  },
  {
    id: "disposable-syringe",
    name: "Disposable Syringe",
    category: "gear",
    subcategory: "Biotech",
    cost: 10,
    availability: "2",
    summary: "Single-use syringe for applying Injection-vector toxins.",
  },
  {
    id: "medkit",
    name: "Medkit",
    category: "gear",
    subcategory: "Biotech",
    cost: 250,
    availability: "3",
    summary: "Drug supplies, bandages, tools, and a doctor expert system; counts as a Kit for Biotech tests.",
    levels: { min: 1, max: 6 },
  },
  {
    id: "medkit-supplies",
    name: "Medkit Supplies",
    category: "gear",
    subcategory: "Biotech",
    cost: 100,
    availability: "1",
    summary: "Replacement supplies for a medkit after use; up to five sets can be stored in the medkit's case.",
  },
  {
    id: "antidote-patch",
    name: "Antidote Patch",
    category: "gear",
    subcategory: "Biotech",
    cost: 150,
    availability: "3",
    summary: "Cancels or negates the Poisoned status for a broad range of toxins.",
  },
  {
    id: "chem-patch",
    name: "Chem Patch",
    category: "gear",
    subcategory: "Biotech",
    cost: 200,
    availability: "3",
    summary: "A blank patch that can be loaded with one dose of a chemical or toxin for later application.",
  },
  {
    id: "stim-patch",
    name: "Stim Patch",
    category: "gear",
    subcategory: "Biotech",
    cost: 25,
    availability: "3",
    summary: "Removes Stun damage equal to its Rating and cancels Dazed; after (Rating x 10) minutes the patient takes (Rating + 1) unresisted Stun damage. Prevents resting while active.",
    levels: { min: 1, max: 6 },
  },
  {
    id: "tranq-patch",
    name: "Tranq Patch",
    category: "gear",
    subcategory: "Biotech",
    cost: 10,
    availability: "3",
    summary: "Inflicts Stun damage equal to its Rating (resisted with Body only). Prices as (Rating x Rating) x 10¥ - quadratic, not linear - so only the Rating 1 cost (10¥) is catalogued here; compute higher ratings by hand.",
  },
  {
    id: "trauma-patch",
    name: "Trauma Patch",
    category: "gear",
    subcategory: "Biotech",
    cost: 500,
    availability: "3",
    summary: "Immediately heals 1d6 + 1 Overflow Damage when applied. Always wireless, connects to the Matrix on application.",
  },
];
