// Metavariants, transcribed from the SR6 Companion, "Creating a Metavariant
// or Metasapient Player Character" section (book pp. 91-93) - the
// "Metavariants General Info & Character Development Table" (Customization
// Karma + per-Priority Adjustment Points) and the "[Metatype] Variant
// Attribute Ranges" tables. Racial Traits are listed as free-text names
// only (mechanics not modeled), same precedent as `MetatypeAttributes.
// racialQualities` in priority-tables.ts.
//
// Metasapients (Centaur, Merrow, Naga, Pixie, Sasquatch) are out of scope -
// they're explicitly GM-discretion per the book and bring in mechanics
// (innate Magic rating, natural weapons, movement rates, Dual Natured) that
// don't fit the existing attribute/priority model, same precedent as the
// deferred Complete Character/Vehicle Upgrade PACKs.
//
// Nartaki's Customization Karma is printed as "5/10" - 5 Karma if Shiva
// Arms is taken at level 1, 10 if taken at level 2 - not a flat cost like
// every other entry; captured in `karmaNote` since Shiva Arms' level isn't
// itself a modeled choice (racial traits are display-only).
import type { AttributeRange, Metatype, PriorityLetter } from "./priority-tables.js";

export interface MetavariantCatalogEntry {
  id: string;
  name: string;
  parentMetatype: Metatype;
  /** Customization Karma cost, deducted from the 50-point customization Karma pool. */
  karma: number;
  /** Only set for entries whose printed Karma cost varies by an unmodeled sub-choice (e.g. Nartaki's Shiva Arms level). */
  karmaNote?: string;
  body: AttributeRange;
  agility: AttributeRange;
  reaction: AttributeRange;
  strength: AttributeRange;
  willpower: AttributeRange;
  logic: AttributeRange;
  intuition: AttributeRange;
  charisma: AttributeRange;
  edge: AttributeRange;
  /** Adjustment Points at each Priority letter; a missing letter means the metavariant isn't available at that priority. */
  adjustmentPoints: Partial<Record<PriorityLetter, number>>;
  racialTraits: string[];
}

export const metavariants: MetavariantCatalogEntry[] = [
  // ---- Dwarf variants ----
  {
    id: "duende",
    name: "Duende",
    parentMetatype: "Dwarf",
    karma: 10,
    body: { min: 1, max: 7 },
    agility: { min: 1, max: 6 },
    reaction: { min: 1, max: 8 },
    strength: { min: 1, max: 6 },
    willpower: { min: 1, max: 7 },
    logic: { min: 1, max: 6 },
    intuition: { min: 1, max: 7 },
    charisma: { min: 1, max: 6 },
    edge: { min: 1, max: 6 },
    adjustmentPoints: { A: 13, B: 11, C: 9, D: 4, E: 1 },
    racialTraits: [
      "Allergy (Sunlight, Extreme)",
      "Low-light Vision",
      "Thermographic Vision",
      "Toxin Resistance",
      "Unusual Hair",
    ],
  },
  {
    id: "gnome",
    name: "Gnome",
    parentMetatype: "Dwarf",
    karma: 5,
    body: { min: 1, max: 4 },
    agility: { min: 1, max: 6 },
    reaction: { min: 1, max: 6 },
    strength: { min: 1, max: 4 },
    willpower: { min: 1, max: 7 },
    logic: { min: 1, max: 7 },
    intuition: { min: 1, max: 6 },
    charisma: { min: 1, max: 6 },
    edge: { min: 1, max: 6 },
    adjustmentPoints: { A: 13, B: 11, C: 9, D: 4, E: 1 },
    racialTraits: ["Magic Resistance", "Neoteny", "Thermographic Vision", "Toxin Resistance"],
  },
  {
    id: "hanuman",
    name: "Hanuman",
    parentMetatype: "Dwarf",
    karma: 5,
    body: { min: 1, max: 6 },
    agility: { min: 1, max: 7 },
    reaction: { min: 1, max: 6 },
    strength: { min: 1, max: 7 },
    willpower: { min: 1, max: 6 },
    logic: { min: 1, max: 6 },
    intuition: { min: 1, max: 7 },
    charisma: { min: 1, max: 6 },
    edge: { min: 1, max: 6 },
    adjustmentPoints: { A: 12, B: 10, C: 9, D: 4, E: 1 },
    racialTraits: [
      "Low-light Vision",
      "Monkey Paws",
      "Prehensile Tail",
      "Toxin Resistance",
      "Unusual Hair (Body)",
    ],
  },
  {
    id: "koborokuru",
    name: "Koborokuru",
    parentMetatype: "Dwarf",
    karma: 5,
    body: { min: 1, max: 7 },
    agility: { min: 1, max: 6 },
    reaction: { min: 1, max: 6 },
    strength: { min: 1, max: 7 },
    willpower: { min: 1, max: 7 },
    logic: { min: 1, max: 6 },
    intuition: { min: 1, max: 6 },
    charisma: { min: 1, max: 6 },
    edge: { min: 1, max: 6 },
    adjustmentPoints: { A: 13, B: 11, C: 9, D: 4, E: 1 },
    racialTraits: ["Celerity", "Thermographic Vision", "Toxin Resistance", "Unusual Hair"],
  },
  {
    id: "menehune",
    name: "Menehune",
    parentMetatype: "Dwarf",
    karma: 5,
    body: { min: 1, max: 7 },
    agility: { min: 1, max: 7 },
    reaction: { min: 1, max: 5 },
    strength: { min: 1, max: 7 },
    willpower: { min: 1, max: 6 },
    logic: { min: 1, max: 6 },
    intuition: { min: 1, max: 6 },
    charisma: { min: 1, max: 6 },
    edge: { min: 1, max: 6 },
    adjustmentPoints: { A: 12, B: 10, C: 9, D: 4 },
    racialTraits: ["Thermographic Vision", "Toxin Resistance", "Underwater Vision", "Webbed Digits"],
  },

  // ---- Elf variants ----
  {
    id: "dalakitnon",
    name: "Dalakitnon",
    parentMetatype: "Elf",
    karma: 5,
    body: { min: 1, max: 6 },
    agility: { min: 1, max: 7 },
    reaction: { min: 1, max: 6 },
    strength: { min: 1, max: 6 },
    willpower: { min: 1, max: 6 },
    logic: { min: 1, max: 8 },
    intuition: { min: 1, max: 7 },
    charisma: { min: 1, max: 8 },
    edge: { min: 1, max: 6 },
    adjustmentPoints: { B: 11, C: 9, D: 4, E: 1 },
    racialTraits: ["Allergy (Spices, Moderate)", "Gender Transmorphism", "Low-light Vision"],
  },
  {
    id: "dryad",
    name: "Dryad",
    parentMetatype: "Elf",
    karma: 5,
    body: { min: 1, max: 6 },
    agility: { min: 1, max: 7 },
    reaction: { min: 1, max: 6 },
    strength: { min: 1, max: 5 },
    willpower: { min: 1, max: 6 },
    logic: { min: 1, max: 6 },
    intuition: { min: 1, max: 6 },
    charisma: { min: 1, max: 8 },
    edge: { min: 1, max: 6 },
    adjustmentPoints: { B: 11, C: 9, D: 4, E: 1 },
    racialTraits: ["Glamour", "Low-light Vision", "Symbiosis"],
  },
  {
    id: "nocturna",
    name: "Nocturna",
    parentMetatype: "Elf",
    karma: 5,
    body: { min: 1, max: 5 },
    agility: { min: 1, max: 8 },
    reaction: { min: 1, max: 6 },
    strength: { min: 1, max: 6 },
    willpower: { min: 1, max: 6 },
    logic: { min: 1, max: 6 },
    intuition: { min: 1, max: 6 },
    charisma: { min: 1, max: 7 },
    edge: { min: 1, max: 6 },
    adjustmentPoints: { B: 10, C: 8, D: 4, E: 1 },
    racialTraits: [
      "Allergy (Sunlight, Mild)",
      "Low-light Vision",
      "Keen-eared",
      "Nocturnal",
      "Unusual Hair (Colored Fur)",
    ],
  },
  {
    id: "wakyambi",
    name: "Wakyambi",
    parentMetatype: "Elf",
    karma: 10,
    body: { min: 1, max: 6 },
    agility: { min: 1, max: 7 },
    reaction: { min: 1, max: 6 },
    strength: { min: 1, max: 6 },
    willpower: { min: 1, max: 6 },
    logic: { min: 1, max: 6 },
    intuition: { min: 1, max: 6 },
    charisma: { min: 1, max: 7 },
    edge: { min: 1, max: 7 },
    adjustmentPoints: { B: 12, C: 9, D: 4 },
    racialTraits: ["Celerity", "Elongated Limbs", "Low-light Vision"],
  },
  {
    id: "xapiri-thepe",
    name: "Xapiri Thëpë",
    parentMetatype: "Elf",
    karma: 5,
    body: { min: 1, max: 6 },
    agility: { min: 1, max: 7 },
    reaction: { min: 1, max: 6 },
    strength: { min: 1, max: 6 },
    willpower: { min: 1, max: 6 },
    logic: { min: 1, max: 6 },
    intuition: { min: 1, max: 6 },
    charisma: { min: 1, max: 7 },
    edge: { min: 1, max: 6 },
    adjustmentPoints: { B: 10, C: 8, D: 4, E: 1 },
    racialTraits: [
      "Allergy (Pollutants, Mild)",
      "Bioluminescence (UV Spectrum)",
      "Low-light Vision",
      "Photometabolism",
    ],
  },

  // ---- Human variants ----
  {
    id: "nartaki",
    name: "Nartaki",
    parentMetatype: "Human",
    karma: 5,
    karmaNote: "10 Karma instead if Shiva Arms is taken at level 2 rather than level 1.",
    body: { min: 1, max: 8 },
    agility: { min: 1, max: 8 },
    reaction: { min: 1, max: 6 },
    strength: { min: 1, max: 8 },
    willpower: { min: 1, max: 6 },
    logic: { min: 1, max: 6 },
    intuition: { min: 1, max: 6 },
    charisma: { min: 1, max: 6 },
    edge: { min: 1, max: 6 },
    adjustmentPoints: { C: 10, D: 4 },
    racialTraits: ["Shiva Arms (1 or 2)", "Striking Skin Pigmentation"],
  },
  {
    id: "valkyrie",
    name: "Valkyrie",
    parentMetatype: "Human",
    karma: 15,
    body: { min: 1, max: 7 },
    agility: { min: 1, max: 6 },
    reaction: { min: 1, max: 6 },
    strength: { min: 1, max: 7 },
    willpower: { min: 1, max: 6 },
    logic: { min: 1, max: 6 },
    intuition: { min: 1, max: 6 },
    charisma: { min: 1, max: 6 },
    edge: { min: 1, max: 6 },
    adjustmentPoints: { B: 11, C: 10, D: 4 },
    racialTraits: ["Functional Wings (Type 2)"],
  },

  // ---- Ork variants ----
  {
    id: "hobgoblin",
    name: "Hobgoblin",
    parentMetatype: "Ork",
    karma: 5,
    body: { min: 1, max: 6 },
    agility: { min: 1, max: 6 },
    reaction: { min: 1, max: 6 },
    strength: { min: 1, max: 7 },
    willpower: { min: 1, max: 6 },
    logic: { min: 1, max: 6 },
    intuition: { min: 1, max: 6 },
    charisma: { min: 1, max: 7 },
    edge: { min: 1, max: 6 },
    adjustmentPoints: { A: 13, B: 11, C: 9, D: 4, E: 1 },
    racialTraits: ["Fangs", "Low-light Vision", "Extravagant Eyes", "Poor Self Control (Vindictive)"],
  },
  {
    id: "ogre",
    name: "Ogre",
    parentMetatype: "Ork",
    karma: 5,
    body: { min: 1, max: 9 },
    agility: { min: 1, max: 6 },
    reaction: { min: 1, max: 5 },
    strength: { min: 1, max: 8 },
    willpower: { min: 1, max: 7 },
    logic: { min: 1, max: 6 },
    intuition: { min: 1, max: 6 },
    charisma: { min: 1, max: 6 },
    edge: { min: 1, max: 6 },
    adjustmentPoints: { A: 13, B: 11, C: 9, D: 4, E: 1 },
    racialTraits: ["Low-light Vision", "Ogre Stomach"],
  },
  {
    id: "oni",
    name: "Oni",
    parentMetatype: "Ork",
    karma: 5,
    body: { min: 1, max: 8 },
    agility: { min: 1, max: 7 },
    reaction: { min: 1, max: 6 },
    strength: { min: 1, max: 7 },
    willpower: { min: 1, max: 6 },
    logic: { min: 1, max: 6 },
    intuition: { min: 1, max: 6 },
    charisma: { min: 1, max: 7 },
    edge: { min: 1, max: 6 },
    adjustmentPoints: { A: 13, B: 11, C: 9, D: 4, E: 1 },
    racialTraits: ["Low-light Vision", "Striking Skin Pigmentation"],
  },
  {
    id: "satyr",
    name: "Satyr",
    parentMetatype: "Ork",
    karma: 10,
    body: { min: 1, max: 7 },
    agility: { min: 1, max: 6 },
    reaction: { min: 1, max: 7 },
    strength: { min: 1, max: 7 },
    willpower: { min: 1, max: 6 },
    logic: { min: 1, max: 6 },
    intuition: { min: 1, max: 6 },
    charisma: { min: 1, max: 6 },
    edge: { min: 1, max: 6 },
    adjustmentPoints: { A: 13, B: 11, C: 9, D: 4 },
    racialTraits: ["Low-light Vision", "Satyr Legs"],
  },

  // ---- Troll variants ----
  {
    id: "cyclops",
    name: "Cyclops",
    parentMetatype: "Troll",
    karma: 5,
    body: { min: 1, max: 9 },
    agility: { min: 1, max: 5 },
    reaction: { min: 1, max: 6 },
    strength: { min: 1, max: 10 },
    willpower: { min: 1, max: 6 },
    logic: { min: 1, max: 6 },
    intuition: { min: 1, max: 6 },
    charisma: { min: 1, max: 5 },
    edge: { min: 1, max: 6 },
    adjustmentPoints: { A: 13, B: 11, C: 9, D: 4, E: 1 },
    racialTraits: ["Built Tough 2", "Cyclopean Eye", "Thermographic Vision"],
  },
  {
    id: "fomorian",
    name: "Fomorian",
    parentMetatype: "Troll",
    karma: 10,
    body: { min: 1, max: 9 },
    agility: { min: 1, max: 6 },
    reaction: { min: 1, max: 6 },
    strength: { min: 1, max: 8 },
    willpower: { min: 1, max: 6 },
    logic: { min: 1, max: 6 },
    intuition: { min: 1, max: 6 },
    charisma: { min: 1, max: 7 },
    edge: { min: 1, max: 6 },
    adjustmentPoints: { A: 14, B: 11, C: 9, D: 4 },
    racialTraits: ["Built Tough 2", "Magic Resistance 1", "Thermographic Vision"],
  },
  {
    id: "giant",
    name: "Giant",
    parentMetatype: "Troll",
    karma: 5,
    body: { min: 1, max: 9 },
    agility: { min: 1, max: 5 },
    reaction: { min: 1, max: 6 },
    strength: { min: 1, max: 10 },
    willpower: { min: 1, max: 6 },
    logic: { min: 1, max: 6 },
    intuition: { min: 1, max: 6 },
    charisma: { min: 1, max: 5 },
    edge: { min: 1, max: 6 },
    adjustmentPoints: { A: 14, B: 11, C: 9, D: 4, E: 1 },
    racialTraits: ["Built Tough 2", "Dermal Alteration (Bark)", "Thermographic Vision"],
  },
  {
    id: "minotaur",
    name: "Minotaur",
    parentMetatype: "Troll",
    karma: 5,
    body: { min: 1, max: 10 },
    agility: { min: 1, max: 5 },
    reaction: { min: 1, max: 6 },
    strength: { min: 1, max: 9 },
    willpower: { min: 1, max: 6 },
    logic: { min: 1, max: 6 },
    intuition: { min: 1, max: 6 },
    charisma: { min: 1, max: 5 },
    edge: { min: 1, max: 6 },
    adjustmentPoints: { A: 13, B: 11, C: 9, D: 4, E: 1 },
    racialTraits: ["Built Tough 2", "Goring Horns", "Thermographic Vision"],
  },
];
