// Spells catalog. Unlike the gear catalogs, this one deliberately spans
// multiple sourcebooks (Core Rulebook here, Street Wyrd in
// spellsStreetWyrd.ts) since spells accumulate across a magician's whole
// library rather than being scoped to one PACKs-aligned gear chunk. Every
// entry carries a `book` field for that reason.
//
// This file covers the Core Rulebook: Combat, Detection, Health, Illusion,
// and Manipulation spells, book pp. 132-142 (SR6_Core_RuleBook_noimg.pdf).
// Stat-block numbers (Range, Type, Duration, Drain Value, Damage) are
// transcribed as printed; flavor text is paraphrased in our own words, same
// convention as every other catalog file in this project.
//
// Known gaps in this pass, flagged rather than guessed at:
// - Rituals (Ritual Spellcasting, book p. 143+ - Prodigal Spell, etc.) are a
//   structurally different system (a multi-participant, multi-step casting
//   process with its own catalog of named rituals) and are not covered here.
// - The Sixth World Companion has no Spells chapter and contributes nothing
//   to this catalog - checked directly against its extracted text (no
//   "RANGE/TYPE/DURATION/DV" stat blocks appear anywhere in the book), not
//   assumed absent.
// - "Learning Spells" (p. 130) confirms the free-spell-allotment rule
//   ("Sorcerers select a number of free spells or rituals equal to their
//   Magic x2 - the rating used is the Magic in the Priority table") is
//   stated only for Priority-built characters; see deriveSpells.ts for how
//   that's applied. Every spell beyond that allotment costs 5 Karma
//   ("New Spells", p. 69-70), flat regardless of category.

export interface SpellCatalogEntry {
  id: string;
  name: string;
  category: "Combat" | "Detection" | "Health" | "Illusion" | "Manipulation";
  /** Free-form descriptors from the book, e.g. "Direct Combat", "Area", "Single-Sense". */
  tags?: string[];
  /** Touch, LOS, or LOS(A) for an area effect. */
  range: string;
  /** M (mana) or P (physical). */
  type: "M" | "P";
  /** I (Instantaneous), S (Sustained), L (Limited), or P (Permanent). */
  duration: string;
  /** Drain Value; "Special" for the rare spell whose Drain is defined narratively instead of a flat number. */
  drainValue: number | string;
  /** Combat spells only: S (Stun), P (Physical), or "P, Special" for spells with a non-standard damage model explained in the summary. */
  damage?: string;
  summary: string;
  /** Sourcebook this entry is transcribed from. */
  book: string;
}

const CORE = "Core Rulebook";

export const coreSpells: SpellCatalogEntry[] = [
  // --- Combat Spells (book p. 132-134) ---
  {
    id: "spell-acid-stream",
    name: "Acid Stream",
    category: "Combat",
    tags: ["Indirect Combat"],
    range: "LOS",
    type: "P",
    duration: "I",
    drainValue: 5,
    damage: "P, Special",
    summary: "Sprays a target with corrosive acid, dealing Chemical damage and inflicting the Corroded status equal to net hits.",
    book: CORE,
  },
  {
    id: "spell-toxic-wave",
    name: "Toxic Wave",
    category: "Combat",
    tags: ["Indirect Combat", "Area"],
    range: "LOS (A)",
    type: "P",
    duration: "I",
    drainValue: 6,
    damage: "P, Special",
    summary: "Area-effect version of Acid Stream, showering everyone in the blast with corrosive acid.",
    book: CORE,
  },
  {
    id: "spell-clout",
    name: "Clout",
    category: "Combat",
    tags: ["Indirect Combat"],
    range: "LOS",
    type: "P",
    duration: "I",
    drainValue: 3,
    damage: "S",
    summary: "Slams a target with a blast of magically-shaped force, dealing Stun damage.",
    book: CORE,
  },
  {
    id: "spell-blast",
    name: "Blast",
    category: "Combat",
    tags: ["Indirect Combat", "Area"],
    range: "LOS (A)",
    type: "P",
    duration: "I",
    drainValue: 4,
    damage: "S",
    summary: "Area-effect version of Clout, battering everyone caught in the blast with force.",
    book: CORE,
  },
  {
    id: "spell-flamestrike",
    name: "Flamestrike",
    category: "Combat",
    tags: ["Indirect Combat"],
    range: "LOS",
    type: "P",
    duration: "I",
    drainValue: 5,
    damage: "P, Special",
    summary: "Blasts a single target with Fire elemental damage, imposing the Burning status equal to net hits.",
    book: CORE,
  },
  {
    id: "spell-fireball",
    name: "Fireball",
    category: "Combat",
    tags: ["Indirect Combat", "Area"],
    range: "LOS (A)",
    type: "P",
    duration: "I",
    drainValue: 6,
    damage: "P, Special",
    summary: "The classic area-effect fireball: Fire elemental damage and Burning status to everyone in the blast.",
    book: CORE,
  },
  {
    id: "spell-ice-spear",
    name: "Ice Spear",
    category: "Combat",
    tags: ["Indirect Combat"],
    range: "LOS",
    type: "P",
    duration: "I",
    drainValue: 5,
    damage: "P, Special",
    summary: "Impales a single target with a spear of ice, dealing Cold elemental damage and imposing Chilled.",
    book: CORE,
  },
  {
    id: "spell-ice-storm",
    name: "Ice Storm",
    category: "Combat",
    tags: ["Indirect Combat", "Area"],
    range: "LOS (A)",
    type: "P",
    duration: "I",
    drainValue: 6,
    damage: "P, Special",
    summary: "Area-effect version of Ice Spear, blasting everyone in range with Cold elemental damage and Chilled.",
    book: CORE,
  },
  {
    id: "spell-lightning-bolt",
    name: "Lightning Bolt",
    category: "Combat",
    tags: ["Indirect Combat"],
    range: "LOS",
    type: "P",
    duration: "I",
    drainValue: 5,
    damage: "P, Special",
    summary: "Strikes a single target with electricity, dealing Electricity elemental damage and the Zapped status.",
    book: CORE,
  },
  {
    id: "spell-lightning-ball",
    name: "Lightning Ball",
    category: "Combat",
    tags: ["Indirect Combat", "Area"],
    range: "LOS (A)",
    type: "P",
    duration: "I",
    drainValue: 6,
    damage: "P, Special",
    summary: "Area-effect version of Lightning Bolt.",
    book: CORE,
  },
  {
    id: "spell-manabolt",
    name: "Manabolt",
    category: "Combat",
    tags: ["Direct Combat"],
    range: "LOS",
    type: "M",
    duration: "I",
    drainValue: 4,
    damage: "P",
    summary: "Pure mana channeled directly into the target as Physical damage; resisted with Willpower + Intuition instead of armor.",
    book: CORE,
  },
  {
    id: "spell-manaball",
    name: "Manaball",
    category: "Combat",
    tags: ["Direct Combat", "Area"],
    range: "LOS (A)",
    type: "M",
    duration: "I",
    drainValue: 5,
    damage: "P",
    summary: "Area-effect version of Manabolt.",
    book: CORE,
  },
  {
    id: "spell-powerbolt",
    name: "Powerbolt",
    category: "Combat",
    tags: ["Direct Combat"],
    range: "LOS",
    type: "P",
    duration: "I",
    drainValue: 4,
    damage: "P",
    summary: "Physical-type direct-damage spell, hitting a single target for Physical damage with no elemental effect.",
    book: CORE,
  },
  {
    id: "spell-powerball",
    name: "Powerball",
    category: "Combat",
    tags: ["Direct Combat", "Area"],
    range: "LOS (A)",
    type: "P",
    duration: "I",
    drainValue: 5,
    damage: "P",
    summary: "Area-effect version of Powerbolt.",
    book: CORE,
  },
  {
    id: "spell-stunbolt",
    name: "Stunbolt",
    category: "Combat",
    tags: ["Direct Combat"],
    range: "LOS",
    type: "M",
    duration: "I",
    drainValue: 3,
    damage: "S",
    summary: "Direct mana spell that knocks a single target out with Stun damage instead of Physical.",
    book: CORE,
  },
  {
    id: "spell-stunball",
    name: "Stunball",
    category: "Combat",
    tags: ["Direct Combat", "Area"],
    range: "LOS (A)",
    type: "M",
    duration: "I",
    drainValue: 4,
    damage: "S",
    summary: "Area-effect version of Stunbolt.",
    book: CORE,
  },

  // --- Detection Spells (book p. 134-136) ---
  {
    id: "spell-analyze-device",
    name: "Analyze Device",
    category: "Detection",
    range: "Touch",
    type: "P",
    duration: "S",
    drainValue: 2,
    summary: "Reveals information about an unknown electronic device based on net hits, and grants Edge the first time it's used while sustained.",
    book: CORE,
  },
  {
    id: "spell-analyze-magic",
    name: "Analyze Magic",
    category: "Detection",
    range: "Touch",
    type: "P",
    duration: "S",
    drainValue: 3,
    summary: "Lets the caster read active magic (foci, spells, wards, rituals) the way an astrally perceiving mage would, without actually going astral.",
    book: CORE,
  },
  {
    id: "spell-analyze-truth",
    name: "Analyze Truth",
    category: "Detection",
    range: "Touch",
    type: "M",
    duration: "S",
    drainValue: 3,
    summary: "Gives the subject a sense of whether a statement they hear is believed true by the speaker.",
    book: CORE,
  },
  {
    id: "spell-clairaudience",
    name: "Clairaudience",
    category: "Detection",
    range: "Touch",
    type: "M",
    duration: "S",
    drainValue: 3,
    summary: "Lets the subject hear sounds from a separate, movable spot instead of their own location.",
    book: CORE,
  },
  {
    id: "spell-clairvoyance",
    name: "Clairvoyance",
    category: "Detection",
    range: "Touch",
    type: "M",
    duration: "S",
    drainValue: 3,
    summary: "Lets the subject see from a separate, movable spot instead of their own location.",
    book: CORE,
  },
  {
    id: "spell-combat-sense",
    name: "Combat Sense",
    category: "Detection",
    range: "Touch",
    type: "M",
    duration: "S",
    drainValue: 3,
    summary: "Sharpens the subject's danger sense, adding net hits to their Defense Rating and Surprise-test dice pool.",
    book: CORE,
  },
  {
    id: "spell-detect-enemies",
    name: "Detect Enemies",
    category: "Detection",
    range: "Touch",
    type: "M",
    duration: "S",
    drainValue: 3,
    summary: "Warns the subject if anyone nearby harbors hostile intent specifically toward them.",
    book: CORE,
  },
  {
    id: "spell-detect-life",
    name: "Detect Life",
    category: "Detection",
    range: "Touch",
    type: "M",
    duration: "S",
    drainValue: 3,
    summary: "Reveals the presence of sentient beings within sensing range, even if hidden from normal sight.",
    book: CORE,
  },
  {
    id: "spell-detect-magic",
    name: "Detect Magic",
    category: "Detection",
    range: "Touch",
    type: "M",
    duration: "S",
    drainValue: 4,
    summary: "Alerts the caster to any active magic (foci, wards, spirits, alchemical preparations) within sensing range.",
    book: CORE,
  },
  {
    id: "spell-mindlink",
    name: "Mindlink",
    category: "Detection",
    range: "Touch",
    type: "M",
    duration: "S",
    drainValue: 3,
    summary: "Opens a two-way telepathic link between caster and subject for as long as they stay within range of each other.",
    book: CORE,
  },
  {
    id: "spell-mind-probe",
    name: "Mind Probe",
    category: "Detection",
    range: "Touch",
    type: "P",
    duration: "S",
    drainValue: 5,
    summary: "Digs into a target's mind against an opposed Willpower + Logic test, pulling out surface thoughts, memories, or deep subconscious information depending on net hits.",
    book: CORE,
  },

  // --- Health Spells (book p. 136-138) ---
  {
    id: "spell-antidote",
    name: "Antidote",
    category: "Health",
    range: "Touch",
    type: "P",
    duration: "P",
    drainValue: 5,
    summary: "Purges toxins from the body; each hit reduces the toxin's power by one until it's eliminated.",
    book: CORE,
  },
  {
    id: "spell-cleansing-heal",
    name: "Cleansing Heal",
    category: "Health",
    range: "Touch",
    type: "P",
    duration: "P",
    drainValue: 5,
    summary: "Heals like Heal, and additionally cures the Corroded status on the target.",
    book: CORE,
  },
  {
    id: "spell-cooling-heal",
    name: "Cooling Heal",
    category: "Health",
    range: "Touch",
    type: "P",
    duration: "P",
    drainValue: 5,
    summary: "Heals like Heal, and additionally cures the Burning status on the target.",
    book: CORE,
  },
  {
    id: "spell-decrease-attribute",
    name: "Decrease Attribute",
    category: "Health",
    range: "Touch",
    type: "P",
    duration: "S",
    drainValue: 3,
    summary: "Temporarily lowers a chosen physical or mental attribute (never Edge, Essence, Magic, or Resonance) by net hits, at the cost of +1 Drain per hit applied beyond the first.",
    book: CORE,
  },
  {
    id: "spell-heal",
    name: "Heal",
    category: "Health",
    range: "Touch",
    type: "P",
    duration: "P",
    drainValue: 3,
    summary: "The standard healing spell: heals one box of Stun, Physical, or Overflow damage per net hit, threshold reduced by the target's Essence loss.",
    book: CORE,
  },
  {
    id: "spell-increase-attribute",
    name: "Increase Attribute",
    category: "Health",
    range: "Touch",
    type: "P",
    duration: "S",
    drainValue: 3,
    summary: "Temporarily raises a chosen physical or mental attribute (never Edge, Essence, Magic, or Resonance) by net hits (max +4), at the cost of +1 Drain per hit applied beyond the first.",
    book: CORE,
  },
  {
    id: "spell-increase-reflexes",
    name: "Increase Reflexes",
    category: "Health",
    range: "Touch",
    type: "P",
    duration: "S",
    drainValue: 5,
    summary: "Temporarily boosts the target's Reaction and Initiative Dice by net hits.",
    book: CORE,
  },
  {
    id: "spell-resist-pain",
    name: "Resist Pain",
    category: "Health",
    range: "Touch",
    type: "M",
    duration: "S",
    drainValue: 3,
    summary: "Lets the target ignore damage-based dice pool penalties, one point per net hit, without actually healing anything.",
    book: CORE,
  },
  {
    id: "spell-stabilize",
    name: "Stabilize",
    category: "Health",
    range: "Touch",
    type: "M",
    duration: "P",
    drainValue: 3,
    summary: "Removes Overflow damage from a dying target if hits meet the number of Overflow boxes they have.",
    book: CORE,
  },
  {
    id: "spell-warming-heal",
    name: "Warming Heal",
    category: "Health",
    range: "Touch",
    type: "P",
    duration: "P",
    drainValue: 5,
    summary: "Heals like Heal, and additionally cures the Chilled status on the target.",
    book: CORE,
  },

  // --- Illusion Spells (book p. 138-142) ---
  {
    id: "spell-agony",
    name: "Agony",
    category: "Illusion",
    tags: ["Single-Sense"],
    range: "LOS",
    type: "M",
    duration: "S",
    drainValue: 3,
    summary: "Inflicts illusory pain that acts as extra damage boxes for penalty purposes without actually harming the target; can be expanded into an area effect.",
    book: CORE,
  },
  {
    id: "spell-confusion",
    name: "Confusion",
    category: "Illusion",
    tags: ["Multi-Sense"],
    range: "LOS",
    type: "M",
    duration: "S",
    drainValue: 3,
    summary: "Disorients a living target with a swirl of false imagery and emotion, imposing a dice pool penalty equal to net hits on everything except damage resistance.",
    book: CORE,
  },
  {
    id: "spell-chaos",
    name: "Chaos",
    category: "Illusion",
    tags: ["Multi-Sense"],
    range: "LOS",
    type: "P",
    duration: "S",
    drainValue: 4,
    summary: "Same effect as Confusion, but also affects cameras, microphones, and other technology.",
    book: CORE,
  },
  {
    id: "spell-hush",
    name: "Hush",
    category: "Illusion",
    tags: ["Single-Sense"],
    range: "Touch",
    type: "M",
    duration: "S",
    drainValue: 3,
    summary: "Silences a target for living listeners, imposing a hearing threshold equal to net hits.",
    book: CORE,
  },
  {
    id: "spell-silence",
    name: "Silence",
    category: "Illusion",
    tags: ["Single-Sense"],
    range: "Touch",
    type: "P",
    duration: "S",
    drainValue: 4,
    summary: "Same effect as Hush, but also silences the target against microphones and other technology.",
    book: CORE,
  },
  {
    id: "spell-invisibility",
    name: "Invisibility",
    category: "Illusion",
    tags: ["Single-Sense"],
    range: "Touch",
    type: "M",
    duration: "S",
    drainValue: 3,
    summary: "Makes the target hard to see by living onlookers, imposing a threshold equal to net hits on any test to spot them.",
    book: CORE,
  },
  {
    id: "spell-improved-invisibility",
    name: "Improved Invisibility",
    category: "Illusion",
    tags: ["Single-Sense"],
    range: "Touch",
    type: "P",
    duration: "S",
    drainValue: 4,
    summary: "Same effect as Invisibility, but also defeats cameras and other technology.",
    book: CORE,
  },
  {
    id: "spell-mask",
    name: "Mask",
    category: "Illusion",
    tags: ["Multi-Sense"],
    range: "Touch",
    type: "M",
    duration: "S",
    drainValue: 3,
    summary: "Disguises the target's appearance, sound, and scent to living observers; net hits set the threshold to see through it.",
    book: CORE,
  },
  {
    id: "spell-physical-mask",
    name: "Physical Mask",
    category: "Illusion",
    tags: ["Multi-Sense"],
    range: "Touch",
    type: "P",
    duration: "S",
    drainValue: 4,
    summary: "Same effect as Mask, but also fools cameras and other technology.",
    book: CORE,
  },
  {
    id: "spell-phantasm",
    name: "Phantasm",
    category: "Illusion",
    tags: ["Multi-Sense"],
    range: "LOS (A)",
    type: "M",
    duration: "S",
    drainValue: 3,
    summary: "Projects a convincing illusory image (with sound and smell) into an area for any living viewer who sees it.",
    book: CORE,
  },
  {
    id: "spell-trid-phantasm",
    name: "Trid Phantasm",
    category: "Illusion",
    tags: ["Multi-Sense"],
    range: "LOS (A)",
    type: "P",
    duration: "S",
    drainValue: 4,
    summary: "Same effect as Phantasm, but also fools cameras, microphones, and other technology.",
    book: CORE,
  },
  {
    id: "spell-sensor-sneak",
    name: "Sensor Sneak",
    category: "Illusion",
    tags: ["Multi-Sense"],
    range: "Touch",
    type: "P",
    duration: "S",
    drainValue: 2,
    summary: "Hides the target from technological sensors only, with no effect on living observers.",
    book: CORE,
  },

  // --- Manipulation Spells (book p. 138-142) ---
  {
    id: "spell-animate-metal",
    name: "Animate Metal",
    category: "Manipulation",
    range: "LOS",
    type: "P",
    duration: "L",
    drainValue: 6,
    summary: "Brings metal objects to life to move under the caster's command; net hits determine the volume animated (see the book's Volume Reference table).",
    book: CORE,
  },
  {
    id: "spell-animate-plastic",
    name: "Animate Plastic",
    category: "Manipulation",
    range: "LOS",
    type: "P",
    duration: "L",
    drainValue: 3,
    summary: "Same as Animate Metal, for plastic objects.",
    book: CORE,
  },
  {
    id: "spell-animate-stone",
    name: "Animate Stone",
    category: "Manipulation",
    range: "LOS",
    type: "P",
    duration: "L",
    drainValue: 5,
    summary: "Same as Animate Metal, for stone objects.",
    book: CORE,
  },
  {
    id: "spell-animate-wood",
    name: "Animate Wood",
    category: "Manipulation",
    range: "LOS",
    type: "P",
    duration: "L",
    drainValue: 4,
    summary: "Same as Animate Metal, for wooden objects.",
    book: CORE,
  },
  {
    id: "spell-armor",
    name: "Armor",
    category: "Manipulation",
    range: "Touch",
    type: "P",
    duration: "S",
    drainValue: 4,
    summary: "Hardens the target's body with mana, adding net hits to their Defense Rating.",
    book: CORE,
  },
  {
    id: "spell-control-actions",
    name: "Control Actions",
    category: "Manipulation",
    range: "LOS",
    type: "M",
    duration: "L",
    drainValue: 4,
    summary: "Puppeteers a target's physical actions against an opposed Willpower + Logic test; the target is aware it's happening.",
    book: CORE,
  },
  {
    id: "spell-control-thoughts",
    name: "Control Thoughts",
    category: "Manipulation",
    range: "LOS",
    type: "M",
    duration: "L",
    drainValue: 4,
    summary: "Like Control Actions, but implants thoughts in the target's mind instead of controlling their body; harder for the target to notice.",
    book: CORE,
  },
  {
    id: "spell-darkness",
    name: "Darkness",
    category: "Manipulation",
    tags: ["Area"],
    range: "LOS (A)",
    type: "P",
    duration: "S",
    drainValue: 3,
    summary: "Lowers ambient light in an area by net hits, favoring the caster's side in environment-based Edge.",
    book: CORE,
  },
  {
    id: "spell-light",
    name: "Light",
    category: "Manipulation",
    tags: ["Area"],
    range: "LOS (A)",
    type: "P",
    duration: "S",
    drainValue: 3,
    summary: "Raises ambient light in an area by net hits; the counterpart to Darkness.",
    book: CORE,
  },
  {
    id: "spell-elemental-armor",
    name: "Elemental Armor",
    category: "Manipulation",
    range: "Touch",
    type: "M",
    duration: "S",
    drainValue: 5,
    summary: "Works like Armor, and also blocks the status effect (Burning, Zapped, etc.) of one chosen elemental damage type.",
    book: CORE,
  },
  {
    id: "spell-fling",
    name: "Fling",
    category: "Manipulation",
    range: "LOS",
    type: "P",
    duration: "I",
    drainValue: 5,
    summary: "Telekinetically hurls half a kilogram of material per net hit at a target, dealing Stun damage equal to the weight thrown.",
    book: CORE,
  },
  {
    id: "spell-focus-burst",
    name: "Focus Burst",
    category: "Manipulation",
    range: "Touch",
    type: "M",
    duration: "L",
    drainValue: 7,
    summary: "Temporarily boosts the effective Force of a focus by net hits; a critical glitch permanently damages the focus instead.",
    book: CORE,
  },
  {
    id: "spell-levitate",
    name: "Levitate",
    category: "Manipulation",
    range: "LOS",
    type: "P",
    duration: "S",
    drainValue: 6,
    summary: "Lifts and moves up to 50 kilos per hit through the air at the caster's command.",
    book: CORE,
  },
  {
    id: "spell-mana-barrier",
    name: "Mana Barrier",
    category: "Manipulation",
    tags: ["Area"],
    range: "LOS (A)",
    type: "M",
    duration: "S",
    drainValue: 5,
    summary: "Raises an invisible astral wall that blocks spirits, foci, and spells while letting people and mundane objects pass freely.",
    book: CORE,
  },
  {
    id: "spell-mystic-armor",
    name: "Mystic Armor",
    category: "Manipulation",
    range: "Touch",
    type: "M",
    duration: "S",
    drainValue: 3,
    summary: "Like Armor, but protects the target's astral form in astral combat and against mana-based Combat spells.",
    book: CORE,
  },
  {
    id: "spell-overclock",
    name: "Overclock",
    category: "Manipulation",
    range: "LOS",
    type: "P",
    duration: "S",
    drainValue: 4,
    summary: "Temporarily boosts a targeted electronic device's Rating, Attack, Data Processing, Firewall, or Sleaze per net hit, at the cost of Matrix damage to the device when the spell drops.",
    book: CORE,
  },
  {
    id: "spell-physical-barrier",
    name: "Physical Barrier",
    category: "Manipulation",
    tags: ["Area"],
    range: "LOS (A)",
    type: "P",
    duration: "S",
    drainValue: 6,
    summary: "Conjures a physical wall with Structure equal to the caster's Magic plus net hits.",
    book: CORE,
  },
  {
    id: "spell-shape-metal",
    name: "Shape Metal",
    category: "Manipulation",
    range: "LOS",
    type: "P",
    duration: "S",
    drainValue: 5,
    summary: "Makes metal malleable so the caster can reshape it while the spell is sustained; the new shape holds once the spell ends.",
    book: CORE,
  },
  {
    id: "spell-shape-plastic",
    name: "Shape Plastic",
    category: "Manipulation",
    range: "LOS",
    type: "P",
    duration: "S",
    drainValue: 2,
    summary: "Same as Shape Metal, for plastic.",
    book: CORE,
  },
  {
    id: "spell-shape-stone",
    name: "Shape Stone",
    category: "Manipulation",
    range: "LOS",
    type: "P",
    duration: "S",
    drainValue: 4,
    summary: "Same as Shape Metal, for stone.",
    book: CORE,
  },
  {
    id: "spell-shape-wood",
    name: "Shape Wood",
    category: "Manipulation",
    range: "LOS",
    type: "P",
    duration: "S",
    drainValue: 3,
    summary: "Same as Shape Metal, for wood.",
    book: CORE,
  },
  {
    id: "spell-strengthen-wall",
    name: "Strengthen Wall",
    category: "Manipulation",
    tags: ["Area"],
    range: "LOS (A)",
    type: "P",
    duration: "S",
    drainValue: 4,
    summary: "Reinforces an existing wall, adding net hits to its Structure rating.",
    book: CORE,
  },
  {
    id: "spell-thunder",
    name: "Thunder",
    category: "Manipulation",
    tags: ["Area"],
    range: "LOS (A)",
    type: "P",
    duration: "S",
    drainValue: 3,
    summary: "Creates a loud, distracting noise of the caster's choosing in an area, imposing a penalty on others' attempts to hear anything else.",
    book: CORE,
  },
  {
    id: "spell-vehicle-armor",
    name: "Vehicle Armor",
    category: "Manipulation",
    range: "Touch",
    type: "P",
    duration: "S",
    drainValue: 6,
    summary: "Grants a vehicle Hardened Armor equal to net hits against an Object Resistance test.",
    book: CORE,
  },
];
