// Spells catalog, Street Wyrd chunk - see spells.ts's header for the overall
// multi-sourcebook rationale.
//
// Transcribed from Street_Wyrd__Magic_Sourebook__noimg.pdf's "The Tome of
// Now" chapter (pp. 25-43: Combat, Health, Detection, Illusion,
// Manipulation), plus two additional named spells (Comfort Zone, Stone
// Fist, Disentangle) presented as fully-statted worked examples in the
// following "Elements of Magic" custom-spell-design chapter (pp. 50-53).
// Stat-block numbers are transcribed as printed; flavor text (the book
// presents this chapter as an in-world "Digital Grimoire" spell-shop chat
// log) is paraphrased into plain rules language in our own words, same
// convention as every other catalog file in this project.
//
// The Tome of Now reprints several Core Rulebook spells verbatim (Manabolt,
// Manaball, Stunbolt, Stunball, Clout, Blast, Flamestrike, Fireball) as part
// of its in-fiction "shop catalog" framing - those are NOT duplicated here
// since they're already in spells.ts's core catalog with identical stats.
// Only genuinely new spells (or spells with different stats/range than
// their core namesake, e.g. Knockout) are included below.
//
// Known gaps in this pass, flagged rather than guessed at:
// - "Elements of Magic" (pp. 44-53) is a custom-spell-*design* system (build
//   a spell from Range/Type/Duration/Drain "ingredients"), not itself a
//   fixed spell catalog - out of scope here, same treatment as Technomancer
//   streams and the custom-PACK-building precedent elsewhere in this app.
// - "Tire Shredder", used as a running example throughout the ingredient
//   list earlier in that chapter, never receives its own clean final stat
//   block (its flavor text appears spliced against Comfort Zone's due to
//   the book's two-column layout) - excluded rather than reconstructed from
//   a bare "Sorcery + Magic (3) test" mention.
// - "Force and Grace" (pp. 72+) is Street Wyrd's Adept Powers chapter (Way
//   powers like Distance Grasp, Elemental Strike, etc.) - not spells, not
//   covered here. Relevant if/when the deferred Adept Powers feature is
//   built.
// - Several spells (Slay, Bane, Corrode/Melt/Sludge/Ram/Wreck/Demolish
//   (Object), Hose/Tsunami/Punch) have damage or drain effects defined
//   narratively rather than as a flat Stun/Physical value (e.g. damage
//   applies to a weapon's Attack Rating or a wall's Structure instead of a
//   living target) - `damage`/`drainValue` is set to "Special" for these,
//   same convention as the core catalog's elemental Combat spells, with the
//   mechanic explained in the summary.

import type { SpellCatalogEntry } from "./spells.js";

const STREET_WYRD = "Street Wyrd";

export const streetWyrdSpells: SpellCatalogEntry[] = [
  // --- Combat (book p. 25-28) ---
  {
    id: "spell-ectomagic-pulse",
    name: "Ectomagic Pulse",
    category: "Combat",
    tags: ["Focus"],
    range: "LOS (A)",
    type: "M",
    duration: "I",
    drainValue: 7,
    damage: "Special",
    summary: "Disrupts foci instead of people: deals 1 box of temporary damage per net hit to every enemy focus in the area, disabling it until it heals.",
    book: STREET_WYRD,
  },
  {
    id: "spell-death-touch",
    name: "Death Touch",
    category: "Combat",
    tags: ["Direct Combat"],
    range: "Touch",
    type: "M",
    duration: "I",
    drainValue: 3,
    damage: "P",
    summary: "A touch-range mana attack spell classed as a restricted weapon; channels magical energy directly into cellular damage.",
    book: STREET_WYRD,
  },
  {
    id: "spell-disrupt",
    name: "Disrupt",
    category: "Combat",
    tags: ["Focus"],
    range: "LOS",
    type: "M",
    duration: "I",
    drainValue: 6,
    damage: "Special",
    summary: "Single-target version of Ectomagic Pulse: deals 1 box of temporary damage per net hit to one enemy focus.",
    book: STREET_WYRD,
  },
  {
    id: "spell-knockout",
    name: "Knockout",
    category: "Combat",
    tags: ["Direct Combat"],
    range: "Touch",
    type: "M",
    duration: "I",
    drainValue: 2,
    damage: "S",
    summary: "A cheap, touch-range Stun attack for quietly putting someone to sleep.",
    book: STREET_WYRD,
  },
  {
    id: "spell-hellblast",
    name: "Hellblast",
    category: "Combat",
    tags: ["Indirect Combat", "Area"],
    range: "LOS (A)",
    type: "P",
    duration: "I",
    drainValue: 8,
    damage: "P, Special",
    summary: "A higher-Drain sibling of Fireball with the same Fire elemental damage and Burning status, plus an added Corroded status equal to net hits.",
    book: STREET_WYRD,
  },
  {
    id: "spell-napalm",
    name: "Napalm",
    category: "Combat",
    tags: ["Indirect Combat"],
    range: "LOS",
    type: "P",
    duration: "I",
    drainValue: 7,
    damage: "P, Special",
    summary: "Sticky superheated fluid that imposes Burning equal to net hits and halves the protection of Fire Resistance armor against it.",
    book: STREET_WYRD,
  },
  {
    id: "spell-thunderstruck",
    name: "Thunderstruck",
    category: "Combat",
    tags: ["Indirect Combat"],
    range: "LOS",
    type: "P",
    duration: "I",
    drainValue: 6,
    damage: "S, Special",
    summary: "A concussive sonic blast that deals Stun damage like Clout and can also Daze and Deafen everyone near the target.",
    book: STREET_WYRD,
  },
  {
    id: "spell-corrode-object",
    name: "Corrode (Object)",
    category: "Combat",
    tags: ["Indirect Combat"],
    range: "Touch",
    type: "P",
    duration: "I",
    drainValue: 2,
    damage: "Special",
    summary: "Dissolves a chosen small object type (learned per-object, e.g. \"Heavy Pistol\") into goo; damage applies to the object's own rating (Defense, Attack, Structure, etc.), not a living target.",
    book: STREET_WYRD,
  },
  {
    id: "spell-melt-object",
    name: "Melt (Object)",
    category: "Combat",
    tags: ["Indirect Combat"],
    range: "LOS",
    type: "P",
    duration: "I",
    drainValue: 3,
    damage: "Special",
    summary: "Ranged version of Corrode (Object).",
    book: STREET_WYRD,
  },
  {
    id: "spell-sludge-object",
    name: "Sludge (Object)",
    category: "Combat",
    tags: ["Indirect Combat", "Area"],
    range: "LOS (A)",
    type: "P",
    duration: "I",
    drainValue: 5,
    damage: "Special",
    summary: "Area-effect version of Melt (Object), dissolving every matching object type in the blast.",
    book: STREET_WYRD,
  },
  {
    id: "spell-ram-object",
    name: "Ram (Object)",
    category: "Combat",
    tags: ["Direct Combat"],
    range: "Touch",
    type: "P",
    duration: "I",
    drainValue: 2,
    damage: "Special",
    summary: "The Direct-Combat counterpart to Corrode (Object): smashes a chosen small object type via Object Resistance instead of dissolving it, with no damage resistance roll.",
    book: STREET_WYRD,
  },
  {
    id: "spell-wreck-object",
    name: "Wreck (Object)",
    category: "Combat",
    tags: ["Direct Combat"],
    range: "LOS",
    type: "P",
    duration: "I",
    drainValue: 4,
    damage: "Special",
    summary: "Ranged version of Ram (Object).",
    book: STREET_WYRD,
  },
  {
    id: "spell-demolish-object",
    name: "Demolish (Object)",
    category: "Combat",
    tags: ["Direct Combat", "Area"],
    range: "LOS (A)",
    type: "P",
    duration: "I",
    drainValue: 6,
    damage: "Special",
    summary: "Area-effect version of Wreck (Object), smashing every matching object type in the blast.",
    book: STREET_WYRD,
  },
  {
    id: "spell-hose",
    name: "Hose",
    category: "Combat",
    tags: ["Indirect Combat"],
    range: "LOS",
    type: "P",
    duration: "I",
    drainValue: 4,
    damage: "Special",
    summary: "Blasts a target with a jet of conjured water, imposing the Wet status and pushing them back if net hits exceed their Body.",
    book: STREET_WYRD,
  },
  {
    id: "spell-tsunami",
    name: "Tsunami",
    category: "Combat",
    tags: ["Indirect Combat", "Area"],
    range: "LOS (A)",
    type: "P",
    duration: "I",
    drainValue: 6,
    damage: "Special",
    summary: "Area-effect version of Hose, capable of knocking every target in the blast Prone.",
    book: STREET_WYRD,
  },
  {
    id: "spell-punch",
    name: "Punch",
    category: "Combat",
    tags: ["Indirect Combat"],
    range: "Touch",
    type: "P",
    duration: "I",
    drainValue: 2,
    damage: "S",
    summary: "A minor telekinetic jab, the weakest of the Punch/Clout/Blast family of force spells.",
    book: STREET_WYRD,
  },
  {
    id: "spell-slay",
    name: "Slay",
    category: "Combat",
    tags: ["Direct Combat", "Target"],
    range: "LOS",
    type: "P",
    duration: "I",
    drainValue: 3,
    damage: "P",
    summary: "Mechanically equivalent to Powerbolt, but only works against one chosen sentient species/metatype/spirit type selected at learning; has no effect on any other target. Tightly restricted - most legal retailers won't sell the formula.",
    book: STREET_WYRD,
  },
  {
    id: "spell-bane",
    name: "Bane",
    category: "Combat",
    tags: ["Direct Combat", "Target"],
    range: "LOS",
    type: "M",
    duration: "I",
    drainValue: 3,
    damage: "P",
    summary: "Mechanically equivalent to Manabolt, but only works against one chosen sentient species/metatype/spirit type selected at learning (the only member of this family that can target the astral plane); has no effect on any other target. Tightly restricted - most legal retailers won't sell the formula.",
    book: STREET_WYRD,
  },

  // --- Health (book p. 29-33, + Comfort Zone from Elements of Magic p. 51) ---
  {
    id: "spell-anaphylaxis",
    name: "Anaphylaxis",
    category: "Health",
    range: "Touch",
    type: "P",
    duration: "S",
    drainValue: 5,
    summary: "Triggers an allergic reaction in the target on touch, regardless of whether they actually have the allergy; restricted for its lethality potential.",
    book: STREET_WYRD,
  },
  {
    id: "spell-ephedrine",
    name: "Ephedrine",
    category: "Health",
    range: "Touch",
    type: "P",
    duration: "S",
    drainValue: 4,
    summary: "The defensive counterpart to Anaphylaxis: suppresses an existing allergic reaction without drowsiness for as long as it's sustained.",
    book: STREET_WYRD,
  },
  {
    id: "spell-diagnose",
    name: "Diagnose",
    category: "Health",
    range: "Touch",
    type: "M",
    duration: "I",
    drainValue: 4,
    summary: "A magical field-medicine scan; net hits reveal increasingly detailed information about the subject's injuries, toxins, cyberware, and general health, and can boost a following Heal or Treat spell.",
    book: STREET_WYRD,
  },
  {
    id: "spell-fast",
    name: "Fast",
    category: "Health",
    range: "Touch",
    type: "P",
    duration: "Special",
    drainValue: 4,
    summary: "Removes the feeling of hunger and thirst for a day per hit without actually nourishing the subject; overuse risks starvation the subject doesn't notice.",
    book: STREET_WYRD,
  },
  {
    id: "spell-healthy-glow",
    name: "Healthy Glow",
    category: "Health",
    range: "Touch",
    type: "P",
    duration: "P",
    drainValue: 4,
    summary: "A cosmetic-only spell that improves the subject's appearance (skin, teeth, minor blemishes) for social Edge, and can lend Edge to a first-aid or healing test performed on them soon after.",
    book: STREET_WYRD,
  },
  {
    id: "spell-nutrition",
    name: "Nutrition",
    category: "Health",
    range: "Touch",
    type: "P",
    duration: "P",
    drainValue: 4,
    summary: "Feeds the subject on pure mana instead of food; each hit staves off starvation and dehydration for twelve hours, up to three days. Prolonged use risks Fae Food Syndrome.",
    book: STREET_WYRD,
  },
  {
    id: "spell-oxygenate",
    name: "Oxygenate",
    category: "Health",
    range: "Touch",
    type: "P",
    duration: "S",
    drainValue: 4,
    summary: "Infuses the subject's body directly with oxygen, granting immunity to suffocation, strangulation, and drowning while sustained.",
    book: STREET_WYRD,
  },
  {
    id: "spell-preserve",
    name: "Preserve",
    category: "Health",
    range: "Touch",
    type: "P",
    duration: "I",
    drainValue: 5,
    summary: "Suspends up to a cubic meter of material (food, cadavers, material links) in stasis for six hours per hit, preventing decay.",
    book: STREET_WYRD,
  },
  {
    id: "spell-rot",
    name: "Rot",
    category: "Health",
    range: "Touch",
    type: "P",
    duration: "P",
    drainValue: 5,
    summary: "Breaks down organic material into unusable mush, destroying material links; can also be turned offensively against a living target to inflict Disabled or Fatigued status.",
    book: STREET_WYRD,
  },
  {
    id: "spell-sterilize",
    name: "Sterilize",
    category: "Health",
    tags: ["Area"],
    range: "LOS (A)",
    type: "P",
    duration: "P",
    drainValue: 4,
    summary: "Kills all bacteria, viruses, and pathogens in an area - safe for anything living except microorganisms, so not usable directly on a person to treat infection.",
    book: STREET_WYRD,
  },
  {
    id: "spell-treat",
    name: "Treat",
    category: "Health",
    range: "Touch",
    type: "M",
    duration: "P",
    drainValue: 4,
    summary: "Reduces or removes debilitating status effects (Blinded, Burning, Corrosive, Deafened, Chilled, Dazed) that Heal alone doesn't address.",
    book: STREET_WYRD,
  },
  {
    id: "spell-comfort-zone",
    name: "Comfort Zone",
    category: "Health",
    range: "Touch",
    type: "P",
    duration: "S",
    drainValue: 6,
    summary: "Shields the subject from harsh weather, countering Wet and Chilled and further insulating them up to 5°C per net hit while sustained. Presented as a worked \"custom spell\" example rather than a Tome of Now catalog entry.",
    book: STREET_WYRD,
  },

  // --- Detection (book p. 33-34) ---
  {
    id: "spell-astral-window",
    name: "Astral Window",
    category: "Detection",
    range: "LOS",
    type: "M",
    duration: "S",
    drainValue: 3,
    summary: "Opens a small sphere through which anyone in LOS can use Perception as astral perception, letting mundanes glimpse the astral plane.",
    book: STREET_WYRD,
  },
  {
    id: "spell-borrow-sense",
    name: "Borrow Sense",
    category: "Detection",
    tags: ["Single Sense"],
    range: "Touch",
    type: "M",
    duration: "S",
    drainValue: 4,
    summary: "Lets the caster perceive one chosen sense through a willing or unwilling subject instead of their own.",
    book: STREET_WYRD,
  },
  {
    id: "spell-passenger",
    name: "Passenger",
    category: "Detection",
    tags: ["Multi-Sense"],
    range: "Touch",
    type: "M",
    duration: "S",
    drainValue: 5,
    summary: "Like Borrow Sense, but shares all of the subject's senses at once - a magical live simsense feed.",
    book: STREET_WYRD,
  },
  {
    id: "spell-animal-sense",
    name: "Animal Sense",
    category: "Detection",
    tags: ["Single Sense"],
    range: "Touch",
    type: "M",
    duration: "S",
    drainValue: 4,
    summary: "Like Borrow Sense, but only works on non-sentient animals (including paranormal ones).",
    book: STREET_WYRD,
  },
  {
    id: "spell-eyes-of-the-pack",
    name: "Eyes of the Pack",
    category: "Detection",
    tags: ["Single Sense"],
    range: "Touch",
    type: "M",
    duration: "S",
    drainValue: 4,
    summary: "Links multiple willing subjects (up to the caster's Magic rating) so any of them can switch to perceiving through another's chosen sense.",
    book: STREET_WYRD,
  },
  {
    id: "spell-scrutinize",
    name: "Scrutinize",
    category: "Detection",
    range: "Touch",
    type: "M",
    duration: "S",
    drainValue: 4,
    summary: "Turns Observe in Detail on a single object into a Minor Action while sustained, revealing fine details (count, dimensions, weight, texture) per net hit.",
    book: STREET_WYRD,
  },
  {
    id: "spell-catalog",
    name: "Catalog",
    category: "Detection",
    range: "Touch",
    type: "M",
    duration: "S",
    drainValue: 5,
    summary: "Area version of Scrutinize: hyper-awareness of an entire area, letting the caster view it from any perspective and gain Edge against surprise or invisible attackers.",
    book: STREET_WYRD,
  },
  {
    id: "spell-mana-window",
    name: "Mana Window",
    category: "Detection",
    range: "LOS",
    type: "M",
    duration: "S",
    drainValue: 3,
    summary: "Opens a temporary hole in a mana barrier for perceiving and casting spells through, without removing the barrier itself.",
    book: STREET_WYRD,
  },
  {
    id: "spell-translate",
    name: "Translate",
    category: "Detection",
    range: "Touch",
    type: "M",
    duration: "S",
    drainValue: 4,
    summary: "Creates a low-level telepathic link so speech is understood in the listener's own language; not reliable enough for Edge-sensitive negotiations.",
    book: STREET_WYRD,
  },

  // --- Illusion (book p. 35-38) ---
  {
    id: "spell-babble",
    name: "Babble",
    category: "Illusion",
    range: "Touch",
    type: "M",
    duration: "S",
    drainValue: 3,
    summary: "Anyone eavesdropping on the caster's conversation instead hears a boring, unrelated one - works against living listeners only.",
    book: STREET_WYRD,
  },
  {
    id: "spell-thieves-cant",
    name: "Thieves' Cant",
    category: "Illusion",
    range: "Touch",
    type: "P",
    duration: "S",
    drainValue: 4,
    summary: "Same effect as Babble, but also fools microphones and other recording technology.",
    book: STREET_WYRD,
  },
  {
    id: "spell-chaff",
    name: "Chaff",
    category: "Illusion",
    tags: ["Area"],
    range: "LOS (A)",
    type: "P",
    duration: "L",
    drainValue: 5,
    summary: "A fire-and-forget burst of sensory static that disrupts wireless signals in the area, generating Matrix noise equal to net hits.",
    book: STREET_WYRD,
  },
  {
    id: "spell-double-image",
    name: "Double Image",
    category: "Illusion",
    tags: ["Realistic", "Multi-Sense"],
    range: "Touch",
    type: "M",
    duration: "S",
    drainValue: 3,
    summary: "Creates a realistic illusory duplicate of the touched subject that moves like them, useful for splitting pursuers; can only target each person once.",
    book: STREET_WYRD,
  },
  {
    id: "spell-dreams",
    name: "Dreams",
    category: "Illusion",
    tags: ["Realistic", "Multi-Sense"],
    range: "LOS",
    type: "M",
    duration: "S",
    drainValue: 3,
    summary: "Crafts and transmits a vivid dream into a sleeping or unconscious subject's mind; enough net hits can disrupt their natural healing for the day.",
    book: STREET_WYRD,
  },
  {
    id: "spell-foreboding",
    name: "Foreboding",
    category: "Illusion",
    tags: ["Realistic", "Multi-Sense"],
    range: "LOS (A)",
    type: "M",
    duration: "S",
    drainValue: 4,
    summary: "Broadcasts dread into an area, inflicting Frightened (and, on enough net hits, Panicked) on any sentient being who fails to resist and enters it.",
    book: STREET_WYRD,
  },
  {
    id: "spell-disquiet",
    name: "Disquiet",
    category: "Illusion",
    tags: ["Realistic", "Multi-Sense"],
    range: "LOS (A)",
    type: "M",
    duration: "S",
    drainValue: 3,
    summary: "Same effect as Foreboding, but only affects animals instead of sentient beings.",
    book: STREET_WYRD,
  },
  {
    id: "spell-false-impression",
    name: "False Impression",
    category: "Illusion",
    range: "LOS",
    type: "M",
    duration: "S",
    drainValue: 3,
    summary: "Alters how the caster's own aura reads to astral or Assensing observers, hiding or disguising initiate rank, tradition, or magical activity.",
    book: STREET_WYRD,
  },
  {
    id: "spell-manascape",
    name: "Manascape",
    category: "Illusion",
    tags: ["Area"],
    range: "LOS (A)",
    type: "M",
    duration: "S",
    drainValue: 4,
    summary: "Area version of False Impression, masking or altering the auras of everyone and everything magical within it.",
    book: STREET_WYRD,
  },
  {
    id: "spell-hot-potato",
    name: "Hot Potato",
    category: "Illusion",
    tags: ["Realistic", "Single Sense"],
    range: "LOS",
    type: "M",
    duration: "I",
    drainValue: 3,
    summary: "Makes a held item feel molten hot, forcing the target to drop whatever they're holding if they fail to resist.",
    book: STREET_WYRD,
  },
  {
    id: "spell-vehicle-mask",
    name: "Vehicle Mask",
    category: "Illusion",
    tags: ["Multi-Sense"],
    range: "Touch",
    type: "P",
    duration: "S",
    drainValue: 4,
    summary: "Illusory disguise for a vehicle or drone's appearance; doesn't change its actual physical attributes, and the Increase Area effect covers larger vehicle classes.",
    book: STREET_WYRD,
  },
  {
    id: "spell-phantomscape",
    name: "Phantomscape",
    category: "Illusion",
    tags: ["Multi-Sense"],
    range: "LOS (A)",
    type: "P",
    duration: "S",
    drainValue: 5,
    summary: "Redecorates a room or area with illusory background scenery and textures; only affects inanimate background, not items meant to be touched and used.",
    book: STREET_WYRD,
  },

  // --- Manipulation (book p. 38-43, + Stone Fist/Disentangle from Elements of Magic p. 52-53) ---
  {
    id: "spell-vine",
    name: "Vine",
    category: "Manipulation",
    range: "LOS",
    type: "P",
    duration: "P",
    drainValue: 4,
    summary: "Accelerates the growth of a living, willing plant; each hit represents a week of growth or healing.",
    book: STREET_WYRD,
  },
  {
    id: "spell-rosebush",
    name: "Rosebush",
    category: "Manipulation",
    tags: ["Area"],
    range: "LOS (A)",
    type: "P",
    duration: "P",
    drainValue: 5,
    summary: "Area version of Vine; can also be used offensively, entangling anyone moving through the burst of vegetation with Off-Balance or Hobbled status.",
    book: STREET_WYRD,
  },
  {
    id: "spell-fashion",
    name: "Fashion",
    category: "Manipulation",
    tags: ["Environmental", "Area"],
    range: "Touch",
    type: "P",
    duration: "P",
    drainValue: 4,
    summary: "Restyles clothing on the spot - cleans stains, mends tears, and (with enough net hits) changes color, pattern, or cut - without changing the garment's weight or volume.",
    book: STREET_WYRD,
  },
  {
    id: "spell-catfall",
    name: "Catfall",
    category: "Manipulation",
    range: "Touch",
    type: "P",
    duration: "S",
    drainValue: 3,
    summary: "Softens a fall: each net hit adds 3 meters of safe falling distance and grants Edge on the resulting Athletics or Damage Resistance test.",
    book: STREET_WYRD,
  },
  {
    id: "spell-gecko-crawl",
    name: "Gecko Crawl",
    category: "Manipulation",
    range: "Touch",
    type: "P",
    duration: "S",
    drainValue: 4,
    summary: "Grants the subject sticky hands and feet for climbing vertical or even upside-down surfaces, reducing the climbing test threshold to zero while sustained.",
    book: STREET_WYRD,
  },
  {
    id: "spell-glue",
    name: "Glue",
    category: "Manipulation",
    range: "LOS",
    type: "P",
    duration: "S",
    drainValue: "Special",
    summary: "Adheres a touched object or person to a surface, inflicting Immobilized until forcibly separated; Drain is half the target's Structure or Object Resistance rating.",
    book: STREET_WYRD,
  },
  {
    id: "spell-ice-sheet",
    name: "Ice Sheet",
    category: "Manipulation",
    range: "LOS",
    type: "P",
    duration: "S",
    drainValue: 5,
    summary: "Coats an area in slick ice, imposing Off-Balance on anyone standing on it and forcing a Handling test on vehicles driving over it.",
    book: STREET_WYRD,
  },
  {
    id: "spell-looking-glass",
    name: "Looking Glass",
    category: "Manipulation",
    range: "LOS",
    type: "P",
    duration: "S",
    drainValue: "Special",
    summary: "Makes a material transparent (but not illuminated) so line of sight passes through it; Drain is half the object's Structure rating.",
    book: STREET_WYRD,
  },
  {
    id: "spell-magic-fingers",
    name: "Magic Fingers",
    category: "Manipulation",
    range: "LOS",
    type: "P",
    duration: "S",
    drainValue: 4,
    summary: "Creates a pair of invisible telekinetic hands within a small sphere, usable for simple manipulation but not fine motor tasks; no Edge on actions performed through them.",
    book: STREET_WYRD,
  },
  {
    id: "spell-makeover",
    name: "Makeover",
    category: "Manipulation",
    range: "Touch",
    type: "P",
    duration: "P",
    drainValue: 4,
    summary: "Cosmetic touch-up spell (hair, nails, makeup) that grants social Edge; net hits determine how elaborate the result is, once per subject per day.",
    book: STREET_WYRD,
  },
  {
    id: "spell-disregard",
    name: "Disregard",
    category: "Manipulation",
    tags: ["Area"],
    range: "LOS (A)",
    type: "M",
    duration: "S",
    drainValue: 5,
    summary: "Makes one or more chosen subjects mentally unimportant to everyone else in the area - not invisible, just irrelevant - until the spell is broken by harm, alarm, or interference with someone's task.",
    book: STREET_WYRD,
  },
  {
    id: "spell-mob-mood",
    name: "Mob Mood",
    category: "Manipulation",
    tags: ["Area"],
    range: "LOS (A)",
    type: "M",
    duration: "S",
    drainValue: 5,
    summary: "Shifts the general emotional state of everyone in an area toward one the caster chooses, at the cost of a dice pool penalty to their actions.",
    book: STREET_WYRD,
  },
  {
    id: "spell-mob-mind",
    name: "Mob Mind",
    category: "Manipulation",
    tags: ["Area"],
    range: "LOS (A)",
    type: "M",
    duration: "S",
    drainValue: 5,
    summary: "Shifts everyone in an area's attitude toward a subject the caster chooses (Hostile/Dislike/Neutral/Friendly); enough net hits on either this or Mob Mood can spark a grunt-group riot.",
    book: STREET_WYRD,
  },
  {
    id: "spell-lokis-musical-number",
    name: "Loki's Musical Number",
    category: "Manipulation",
    tags: ["Area"],
    range: "LOS (A)",
    type: "M",
    duration: "S",
    drainValue: 5,
    summary: "Links everyone in the area in a shared musical hallucination, letting them Assist each other's actions in time with the music as long as someone keeps performing.",
    book: STREET_WYRD,
  },
  {
    id: "spell-stone-fist",
    name: "Stone Fist",
    category: "Manipulation",
    range: "Touch",
    type: "P",
    duration: "S",
    drainValue: 5,
    summary: "Hardens the target's fists to stone, raising their Unarmed Combat damage to 3S (4S at Strength 5+) and adding hits to the Attack Rating. Presented as a worked \"custom spell\" example rather than a Tome of Now catalog entry.",
    book: STREET_WYRD,
  },
  {
    id: "spell-disentangle",
    name: "Disentangle",
    category: "Manipulation",
    range: "Touch",
    type: "P",
    duration: "P",
    drainValue: 5,
    summary: "Helps a Hobbled or Immobilized target shake off the effect, granting bonus dice to resist it again from the same source. Presented as a worked \"custom spell\" example rather than a Tome of Now catalog entry.",
    book: STREET_WYRD,
  },
];
