// Gear catalog, Vehicles chunk - seventh in the Companion PACKs-aligned
// sequence (see gear.ts's header for the full rationale and chunk
// ordering).
//
// Transcribed from SR6_Core_RuleBook_noimg.pdf, book pp. 295-298: Bikes,
// Cars, Trucks and Vans, Boats, Submarines, Fixed-Wing Aircraft, Rotorcraft,
// VTOL/VSTOL - everything in the book's "Vehicles and Drones" section up to
// (not including) Microdrones, where Drones start (book p. 299 onward -
// that's the next chunk, split out per the README's own chunk 7/8 division).
// Bikes are included here even though the README's chunk-7 one-line summary
// only named "Cars, Trucks and Vans, Boats" - they're the same continuous
// vehicle stat table sequence in the book (before Cars, not called out
// separately in the TOC), the same kind of unlisted-but-present correction
// the Weapons chunk needed for its Melee/Thrown/Taser sections.
//
// The book prints one stat block per named vehicle (Handling, Acceleration,
// Speed Interval, Top Speed, Body, Armor, Pilot, Sensor, Seats), captured
// here in the free-form `stats` field, same convention as weapon stat
// blocks in gear.ts. Flavor text is paraphrased in our own words, same
// convention as every prior chunk.
//
// Known gaps in this pass, flagged rather than guessed at:
// - The book's "Other Makes and Models" table (p. 296) lists rebadged
//   equivalents with identical stats for flavor/worldbuilding (e.g. "Hyundai
//   Hopper" uses the Dodge Scoot's stats) - not catalogued as separate
//   purchasable entries since they're explicitly the same item under a
//   different name, not new stats.
// - A "Vehicle Modifications" table (Rigger Interface, Standard/Heavy Weapon
//   Mount, Manual Operation) sits at the very start of this section, before
//   the vehicle tables themselves - deliberately NOT catalogued here, it
//   belongs to the README's separate "Vehicle upgrades" chunk (9).
// - Federated Boeing Commuter/Osprey X (VTOL/VSTOL) is printed as a single
//   table row with two variants sharing most stats but differing in Speed
//   Interval, Armor, Pilot, Sensor, Seats, Availability, and Cost (civilian
//   Commuter vs. military Osprey X) - catalogued as one entry at the
//   Commuter's civilian price, with the Osprey X's higher stats/price noted
//   in the summary, same treatment as the Weapons chunk's Colt Government/
//   Manhunter variant pricing.
// - Vehicles with a "seats" value like "2/10" (crew/cargo or crew/passenger
//   split) are transcribed as printed rather than collapsed to one number.

import type { GearCatalogEntry } from "./gear.js";

export const vehiclesGear: GearCatalogEntry[] = [
  // --- Bikes (book p. 295-296) ---
  {
    id: "vehicle-dodge-scoot",
    name: "Dodge Scoot",
    category: "vehicle",
    subcategory: "Bikes",
    cost: 3000,
    availability: "2",
    stats: {
      "Handling (On/Off-road)": "5/7",
      Acceleration: "4",
      "Speed Interval": "10",
      "Top Speed": "80",
      Body: "2",
      Armor: "0",
      Pilot: "1",
      Sensor: "0",
      Seats: "2",
    },
    summary: "Compact, fuel-efficient, super-affordable electric sprawl commuter bike - not built for shadowrunning, but great for blending in.",
  },
  {
    id: "vehicle-harley-davidson-scorpion",
    name: "Harley-Davidson Scorpion",
    category: "vehicle",
    subcategory: "Bikes",
    cost: 14000,
    availability: "2",
    stats: {
      "Handling (On/Off-road)": "3/5",
      Acceleration: "16",
      "Speed Interval": "30",
      "Top Speed": "200",
      Body: "7",
      Armor: "6",
      Pilot: "1",
      Sensor: "1",
      Seats: "2",
    },
    summary: "Big, bad, chromed road hog with some armor and a lot of attitude - popular with go-gangers and the general public alike.",
  },
  {
    id: "vehicle-yamaha-growler",
    name: "Yamaha Growler",
    category: "vehicle",
    subcategory: "Bikes",
    cost: 8000,
    availability: "2",
    stats: {
      "Handling (On/Off-road)": "3/3",
      Acceleration: "15",
      "Speed Interval": "20",
      "Top Speed": "180",
      Body: "6",
      Armor: "4",
      Pilot: "1",
      Sensor: "1",
      Seats: "2",
    },
    summary: "Popular with thrill seekers, wilderness buffs, and light-freight drug smugglers.",
  },
  {
    id: "vehicle-suzuki-mirage",
    name: "Suzuki Mirage",
    category: "vehicle",
    subcategory: "Bikes",
    cost: 12000,
    availability: "2",
    stats: {
      "Handling (On/Off-road)": "2/6",
      Acceleration: "29",
      "Speed Interval": "30",
      "Top Speed": "260",
      Body: "4",
      Armor: "2",
      Pilot: "1",
      Sensor: "1",
      Seats: "1",
    },
    summary: "A racing bike built for speed, popular with go-gangers and other speed freaks.",
  },

  // --- Cars (book p. 296) ---
  {
    id: "vehicle-chrysler-nissan-jackrabbit",
    name: "Chrysler-Nissan Jackrabbit",
    category: "vehicle",
    subcategory: "Cars",
    cost: 11000,
    availability: "2",
    stats: {
      "Handling (On/Off-road)": "3/5",
      Acceleration: "20",
      "Speed Interval": "15",
      "Top Speed": "160",
      Body: "8",
      Armor: "4",
      Pilot: "2",
      Sensor: "1",
      Seats: "3",
    },
    summary: "Ubiquitous electric subcompact. Its anonymity draws runners for stakeouts and tailing targets - just don't get into a car chase.",
  },
  {
    id: "vehicle-honda-spirit",
    name: "Honda Spirit",
    category: "vehicle",
    subcategory: "Cars",
    cost: 13000,
    availability: "2",
    stats: {
      "Handling (On/Off-road)": "4/5",
      Acceleration: "15",
      "Speed Interval": "20",
      "Top Speed": "150",
      Body: "10",
      Armor: "3",
      Pilot: "1",
      Sensor: "1",
      Seats: "4",
    },
    summary: "Three-wheeled electric sprawl commuter with only two real seats, but a low price and everywhere you look.",
  },
  {
    id: "vehicle-eurocar-westwind-x80",
    name: "Eurocar Westwind X80",
    category: "vehicle",
    subcategory: "Cars",
    cost: 115000,
    availability: "3",
    stats: {
      "Handling (On/Off-road)": "2/6",
      Acceleration: "24",
      "Speed Interval": "30",
      "Top Speed": "250",
      Body: "6",
      Armor: "1",
      Pilot: "4",
      Sensor: "3",
      Seats: "2",
    },
    summary: "Speed and opulence in one hot package - a remodeled luxury street machine pushing the limits of performance and street legality.",
  },
  {
    id: "vehicle-hyundai-shin-hyung",
    name: "Hyundai Shin-Hyung",
    category: "vehicle",
    subcategory: "Cars",
    cost: 20000,
    availability: "2",
    stats: {
      "Handling (On/Off-road)": "3/5",
      Acceleration: "12",
      "Speed Interval": "25",
      "Top Speed": "200",
      Body: "7",
      Armor: "1",
      Pilot: "1",
      Sensor: "1",
      Seats: "3",
    },
    summary: "A tuner favorite built around a powerful motor - flash and performance can all be bought with the right investment.",
  },
  {
    id: "vehicle-ford-americar",
    name: "Ford Americar",
    category: "vehicle",
    subcategory: "Cars",
    cost: 16000,
    availability: "2",
    stats: {
      "Handling (On/Off-road)": "4/5",
      Acceleration: "9",
      "Speed Interval": "20",
      "Top Speed": "160",
      Body: "11",
      Armor: "4",
      Pilot: "1",
      Sensor: "2",
      Seats: "4",
    },
    summary: "Redesigned four-door sedan, just as boring as before - unremarkable enough that nobody gives it a second glance.",
  },
  {
    id: "vehicle-sk-bentley-concordat",
    name: "Saeder-Krupp-Bentley Concordat",
    category: "vehicle",
    subcategory: "Cars",
    cost: 65000,
    availability: "3",
    stats: {
      "Handling (On/Off-road)": "3/5",
      Acceleration: "18",
      "Speed Interval": "30",
      "Top Speed": "180",
      Body: "14",
      Armor: "8",
      Pilot: "3",
      Sensor: "3",
      Seats: "4",
    },
    summary: "The car simstars and orxploitation rappers drive after an extremely ostentatious paint job - a dream car for corp youth.",
  },
  {
    id: "vehicle-mitsubishi-nightsky",
    name: "Mitsubishi Nightsky",
    category: "vehicle",
    subcategory: "Cars",
    cost: 259000,
    availability: "3",
    stats: {
      "Handling (On/Off-road)": "4/6",
      Acceleration: "10",
      "Speed Interval": "10",
      "Top Speed": "160",
      Body: "18",
      Armor: "10",
      Pilot: "3",
      Sensor: "4",
      Seats: "8",
    },
    summary: "Armored limousine used by corp executives, media stars, and Mr. Johnsons - sleek, stylish, and no slouch on performance.",
  },

  // --- Trucks and Vans (book p. 297) ---
  {
    id: "vehicle-toyota-gopher",
    name: "Toyota Gopher",
    category: "vehicle",
    subcategory: "Trucks and Vans",
    cost: 25000,
    availability: "2",
    stats: {
      "Handling (On/Off-road)": "4/4",
      Acceleration: "15",
      "Speed Interval": "15",
      "Top Speed": "150",
      Body: "12",
      Armor: "6",
      Pilot: "1",
      Sensor: "1",
      Seats: "4",
    },
    summary: "The pinnacle pickup - off-road capability, great storage, and a roomy four-door cabin with plenty of creature comforts.",
  },
  {
    id: "vehicle-gmc-bulldog-step-van",
    name: "GMC Bulldog Step-Van",
    category: "vehicle",
    subcategory: "Trucks and Vans",
    cost: 35000,
    availability: "2",
    stats: {
      "Handling (On/Off-road)": "5/7",
      Acceleration: "10",
      "Speed Interval": "10",
      "Top Speed": "140",
      Body: "16",
      Armor: "12",
      Pilot: "2",
      Sensor: "3",
      Seats: "2/10",
    },
    summary: "Best-selling delivery van with built-in armor - a staple of runners who enjoy the protection and anonymity of an abundant hauler.",
  },
  {
    id: "vehicle-range-rover-model-2080",
    name: "Range Rover Model 2080",
    category: "vehicle",
    subcategory: "Trucks and Vans",
    cost: 73000,
    availability: "3",
    stats: {
      "Handling (On/Off-road)": "4/5",
      Acceleration: "12",
      "Speed Interval": "20",
      "Top Speed": "160",
      Body: "16",
      Armor: "10",
      Pilot: "4",
      Sensor: "4",
      Seats: "7",
    },
    summary: "A rich-neighborhood status symbol fully capable of taking a run in the dirt or mud. Popular secondhand among security firms.",
  },
  {
    id: "vehicle-ares-roadmaster",
    name: "Ares Roadmaster",
    category: "vehicle",
    subcategory: "Trucks and Vans",
    cost: 68000,
    availability: "2",
    stats: {
      "Handling (On/Off-road)": "5/7",
      Acceleration: "8",
      "Speed Interval": "10",
      "Top Speed": "120",
      Body: "18",
      Armor: "16",
      Pilot: "2",
      Sensor: "2",
      Seats: "2/12",
    },
    summary: "Long-haul commercial van built like a tank, heavily armored and designed for easy installation of a pair of remote turrets.",
  },

  // --- Boats (book p. 297) ---
  {
    id: "vehicle-samuvani-criscraft-otter",
    name: "Samuvani-Criscraft Otter",
    category: "vehicle",
    subcategory: "Boats",
    cost: 25000,
    availability: "2",
    stats: {
      Handling: "4",
      Acceleration: "10",
      "Speed Interval": "15",
      "Top Speed": "90",
      Body: "6",
      Armor: "4",
      Pilot: "2",
      Sensor: "2",
      Seats: "6",
    },
    summary: "A pretty but boring five-meter craft sold kitted for pleasure boating, fishing, light hauling, and utility work.",
  },
  {
    id: "vehicle-aztechnology-sunrunner-nightrunner",
    name: "Aztechnology Sunrunner/Nightrunner",
    category: "vehicle",
    subcategory: "Boats",
    cost: 39000,
    availability: "3",
    stats: {
      Handling: "3",
      Acceleration: "20",
      "Speed Interval": "20",
      "Top Speed": "120",
      Body: "10",
      Armor: "8",
      Pilot: "3",
      Sensor: "3",
      Seats: "5",
    },
    summary:
      "A distinctive sealable canopy and excess cargo space (ample berths for cruising). Formerly the illicit Nightrunner, overhauled and retagged after government contracts.",
  },
  {
    id: "vehicle-gmc-riverine",
    name: "GMC Riverine",
    category: "vehicle",
    subcategory: "Boats",
    cost: 113000,
    availability: "4",
    stats: {
      Handling: "4",
      Acceleration: "15",
      "Speed Interval": "15",
      "Top Speed": "100",
      Body: "14",
      Armor: "12",
      Pilot: "4",
      Sensor: "4",
      Seats: "8",
    },
    summary: "A gunboat, plain and simple - big guns and sweet sensors, though several owners keep the arms hidden to avoid looking like the law.",
  },

  // --- Submarines (book p. 297) ---
  {
    id: "vehicle-proteus-lamprey-sea-snake",
    name: "Proteus Lamprey/Sea Snake",
    category: "vehicle",
    subcategory: "Submarines",
    cost: 15000,
    availability: "2/4",
    stats: {
      Handling: "3",
      Acceleration: "13",
      "Speed Interval": "10",
      "Top Speed": "60",
      Body: "2",
      Armor: "1",
      Pilot: "2",
      Sensor: "1",
      Seats: "4",
    },
    summary:
      "A sea-sled for underwater inspection and transportation, seating four with scuba gear or sixteen metahuman-hours of built-in air. The military Sea Snake variant is used for aquatic insertions. Depths limited to 100m crewed, 200m drone-loaded on tether.",
  },
  {
    id: "vehicle-ynt-delfin",
    name: "YNT Delfin",
    category: "vehicle",
    subcategory: "Submarines",
    cost: 110000,
    availability: "3",
    stats: {
      Handling: "5",
      Acceleration: "18",
      "Speed Interval": "10",
      "Top Speed": "70",
      Body: "6",
      Armor: "12",
      Pilot: "3",
      Sensor: "3",
      Seats: "3",
    },
    summary: "Three-person sub with interchangeable attachments (some offensive) for deep-sea rescue, arkoblock patrols, or recon and resupply.",
  },

  // --- Fixed-Wing Aircraft (book p. 297-298) ---
  {
    id: "vehicle-artemis-nightwing",
    name: "Artemis Industries Nightwing",
    category: "vehicle",
    subcategory: "Fixed-Wing Aircraft",
    cost: 20000,
    availability: "2",
    stats: {
      Handling: "4",
      Acceleration: "15",
      "Speed Interval": "25",
      "Top Speed": "150",
      Body: "2",
      Armor: "0",
      Pilot: "1",
      Sensor: "1",
      Seats: "1",
    },
    summary: "A stealth glider masquerading as an amateur aviation toy - near-silent shrouded electric motor, heat signature of a large hawk.",
  },
  {
    id: "vehicle-cessna-c750",
    name: "Cessna C750",
    category: "vehicle",
    subcategory: "Fixed-Wing Aircraft",
    cost: 150000,
    availability: "2",
    stats: {
      Handling: "5",
      Acceleration: "20",
      "Speed Interval": "25",
      "Top Speed": "250",
      Body: "8",
      Armor: "2",
      Pilot: "2",
      Sensor: "1",
      Seats: "4",
    },
    summary: "Affordable, easy-to-maintain twin-prop civilian aircraft for passengers and light cargo (legit or smuggled), or surveillance in a pinch.",
  },
  {
    id: "vehicle-mct-sikorsky-bell-seahawk",
    name: "MCT-Sikorsky-Bell Seahawk",
    category: "vehicle",
    subcategory: "Fixed-Wing Aircraft",
    cost: 300000,
    availability: "2",
    stats: {
      Handling: "5",
      Acceleration: "30",
      "Speed Interval": "50",
      "Top Speed": "500",
      Body: "12",
      Armor: "4",
      Pilot: "2",
      Sensor: "2",
      Seats: "8",
    },
    summary: "High-speed personal amphibious jet hauling six passengers or a decent stack of cargo. Standard buoyancy/flotation - takes off from land or water.",
  },

  // --- Rotorcraft (book p. 298) ---
  {
    id: "vehicle-ares-dragon",
    name: "Ares Dragon",
    category: "vehicle",
    subcategory: "Rotorcraft",
    cost: 360000,
    availability: "2",
    stats: {
      Handling: "4",
      Acceleration: "10",
      "Speed Interval": "30",
      "Top Speed": "260",
      Body: "22",
      Armor: "10",
      Pilot: "2",
      Sensor: "3",
      Seats: "2/16",
    },
    summary: "A heavily armed troop-transport rotorcraft, popular for close air support.",
  },
  {
    id: "vehicle-mct-sikorsky-bell-wolfhound",
    name: "MCT-Sikorsky-Bell Wolfhound",
    category: "vehicle",
    subcategory: "Rotorcraft",
    cost: 423000,
    availability: "4",
    stats: {
      Handling: "3",
      Acceleration: "20",
      "Speed Interval": "40",
      "Top Speed": "320",
      Body: "12",
      Armor: "14",
      Pilot: "4",
      Sensor: "4",
      Seats: "8",
    },
    summary: "A heavily armored, sensor-laden rotorcraft with substantial passenger capacity.",
  },
  {
    id: "vehicle-northrup-wasp",
    name: "Northrup Wasp",
    category: "vehicle",
    subcategory: "Rotorcraft",
    cost: 93000,
    availability: "3",
    stats: {
      Handling: "3",
      Acceleration: "25",
      "Speed Interval": "30",
      "Top Speed": "330",
      Body: "10",
      Armor: "8",
      Pilot: "3",
      Sensor: "3",
      Seats: "2",
    },
    summary: "Single-seater standard fare for police and light military patrol work.",
  },

  // --- VTOL/VSTOL (book p. 298) ---
  {
    id: "vehicle-ares-venture",
    name: "Ares Venture",
    category: "vehicle",
    subcategory: "VTOL/VSTOL",
    cost: 400000,
    availability: "3",
    stats: {
      Handling: "4",
      Acceleration: "40",
      "Speed Interval": "60",
      "Top Speed": "680",
      Body: "16",
      Armor: "12",
      Pilot: "2",
      Sensor: "2",
      Seats: "2/8",
    },
    summary: "A fast military-grade VTOL transport.",
  },
  {
    id: "vehicle-gmc-banshee",
    name: "GMC Banshee",
    category: "vehicle",
    subcategory: "VTOL/VSTOL",
    cost: 1300000,
    availability: "4",
    stats: {
      Handling: "3",
      Acceleration: "60",
      "Speed Interval": "90",
      "Top Speed": "900",
      Body: "18",
      Armor: "18",
      Pilot: "4",
      Sensor: "4",
      Seats: "2/12",
    },
    summary: "A heavily armored, top-of-the-line VTOL gunship-transport.",
  },
  {
    id: "vehicle-federated-boeing-commuter",
    name: "Federated Boeing Commuter",
    category: "vehicle",
    subcategory: "VTOL/VSTOL",
    cost: 350000,
    availability: "2/4",
    stats: {
      Handling: "3",
      Acceleration: "35",
      "Speed Interval": "60",
      "Top Speed": "420",
      Body: "16",
      Armor: "10",
      Pilot: "2",
      Sensor: "2",
      Seats: "2/10",
    },
    summary:
      "Civilian VTOL people-mover. A military variant, the Osprey X, shares this airframe at 800,000¥ with upgraded stats: Speed Interval 80, Armor 16, Pilot 4, Sensor 4, Availability 4.",
  },
];
